<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateAttachmentData;
use Axyr\Productive\Data\Input\UpdateAttachmentData;
use Axyr\Productive\Data\Models\Attachment;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * An uploaded file attached to a task, comment, expense, or other entity.
 *
 * @see https://developer.productive.io/reference/resources/attachments
 */
final class AttachmentResource extends Resource
{
    protected const string TYPE = 'attachments';

    protected const string PATH = 'attachments';

    /**
     * Get attachments.
     *
     * GET /attachments
     *
     * @return PendingQuery<Attachment>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Attachment::class, 'attachments.index');
    }

    /**
     * Get an attachment.
     *
     * GET /attachments/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Attachment
    {
        return $this->fetchOne(Attachment::class, $this->path($id), 'attachments.show', (new Query())->include(...$include));
    }

    /**
     * Create an attachment.
     *
     * POST /attachments
     *
     * @param  CreateAttachmentData|array<string, mixed>  $data
     */
    public function create(CreateAttachmentData|array $data): Attachment
    {
        return $this->write(Attachment::class, Method::Post, $this->path(), 'attachments.create', $data);
    }

    /**
     * Update an attachment.
     *
     * PATCH /attachments/{id}
     *
     * @param  UpdateAttachmentData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateAttachmentData|array $data): Attachment
    {
        return $this->write(Attachment::class, Method::Patch, $this->path($id), 'attachments.update', $data, (string) $id);
    }

    /**
     * Delete an attachment.
     *
     * DELETE /attachments/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'attachments.destroy');
    }
}
