<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateBankAccountData;
use Axyr\Productive\Data\Input\UpdateBankAccountData;
use Axyr\Productive\Data\Models\BankAccount;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A bank account linked to a subsidiary, storing bank name, account number, currency, and SWIFT details.
 *
 * @see https://developer.productive.io/reference/resources/bank-accounts
 */
final class BankAccountResource extends Resource
{
    protected const string TYPE = 'bank_accounts';

    protected const string PATH = 'bank_accounts';

    /**
     * Get bank accounts.
     *
     * GET /bank_accounts
     *
     * @return PendingQuery<BankAccount>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(BankAccount::class, 'bank_accounts.index');
    }

    /**
     * Gets a bank account.
     *
     * GET /bank_accounts/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): BankAccount
    {
        return $this->fetchOne(BankAccount::class, $this->path($id), 'bank_accounts.show', (new Query())->include(...$include));
    }

    /**
     * Create a bank account.
     *
     * POST /bank_accounts
     *
     * @param  CreateBankAccountData|array<string, mixed>  $data
     */
    public function create(CreateBankAccountData|array $data): BankAccount
    {
        return $this->write(BankAccount::class, Method::Post, $this->path(), 'bank_accounts.create', $data);
    }

    /**
     * Update a bank account.
     *
     * PATCH /bank_accounts/{id}
     *
     * @param  UpdateBankAccountData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateBankAccountData|array $data): BankAccount
    {
        return $this->write(BankAccount::class, Method::Patch, $this->path($id), 'bank_accounts.update', $data, (string) $id);
    }

    /**
     * Archives a bank account.
     *
     * PATCH /bank_accounts/{id}/archive
     */
    public function archive(int|string $id): BankAccount
    {
        return $this->write(BankAccount::class, Method::Patch, $this->path($id, 'archive'), 'bank_accounts.archive', null);
    }

    /**
     * Restores an archived bank account.
     *
     * PATCH /bank_accounts/{id}/restore
     */
    public function restore(int|string $id): BankAccount
    {
        return $this->write(BankAccount::class, Method::Patch, $this->path($id, 'restore'), 'bank_accounts.restore', null);
    }
}
