<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateBillData;
use Axyr\Productive\Data\Input\UpdateBillData;
use Axyr\Productive\Data\Models\Bill;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * Receipt record against a purchase order. Tracks the vendor invoice number, date, due date, description, and total amounts received and cost. Links to a deal and has an optional attachment for the vendor invoice document.
 *
 * @see https://developer.productive.io/reference/resources/bills
 */
final class BillResource extends Resource
{
    protected const string TYPE = 'bills';

    protected const string PATH = 'bills';

    /**
     * Gets a bill.
     *
     * GET /bills/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Bill
    {
        return $this->fetchOne(Bill::class, $this->path($id), 'bills.show', (new Query())->include(...$include));
    }

    /**
     * Create a bill.
     *
     * POST /bills
     *
     * @param  CreateBillData|array<string, mixed>  $data
     */
    public function create(CreateBillData|array $data): Bill
    {
        return $this->write(Bill::class, Method::Post, $this->path(), 'bills.create', $data);
    }

    /**
     * Update a bill.
     *
     * PATCH /bills/{id}
     *
     * @param  UpdateBillData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateBillData|array $data): Bill
    {
        return $this->write(Bill::class, Method::Patch, $this->path($id), 'bills.update', $data, (string) $id);
    }

    /**
     * Deletes a bill.
     *
     * DELETE /bills/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'bills.destroy');
    }
}
