<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateBookingData;
use Axyr\Productive\Data\Input\UpdateBookingData;
use Axyr\Productive\Data\Models\Booking;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A booking represents planned work or an absence scheduled for a person, linked to a service or absence category.
 *
 * @see https://developer.productive.io/reference/resources/bookings
 */
final class BookingResource extends Resource
{
    protected const string TYPE = 'bookings';

    protected const string PATH = 'bookings';

    /**
     * Get bookings.
     *
     * GET /bookings
     *
     * @return PendingQuery<Booking>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Booking::class, 'bookings.index');
    }

    /**
     * Gets a booking.
     *
     * GET /bookings/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Booking
    {
        return $this->fetchOne(Booking::class, $this->path($id), 'bookings.show', (new Query())->include(...$include));
    }

    /**
     * Create a booking.
     *
     * POST /bookings
     *
     * @param  CreateBookingData|array<string, mixed>  $data
     */
    public function create(CreateBookingData|array $data): Booking
    {
        return $this->write(Booking::class, Method::Post, $this->path(), 'bookings.create', $data);
    }

    /**
     * Update a booking.
     *
     * PATCH /bookings/{id}
     *
     * @param  UpdateBookingData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateBookingData|array $data): Booking
    {
        return $this->write(Booking::class, Method::Patch, $this->path($id), 'bookings.update', $data, (string) $id);
    }

    /**
     * Deletes a booking.
     *
     * DELETE /bookings/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'bookings.destroy');
    }
}
