<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateContactEntryData;
use Axyr\Productive\Data\Input\UpdateContactEntryData;
use Axyr\Productive\Data\Models\ContactEntry;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * Contact information record (email, phone, website, or postal address) for a company or person. Supports multiple entries per contact with type classification. Billing-specific fields (billing_address, billing_email, VAT) are available for company contacts with financials enabled.
 *
 * @see https://developer.productive.io/reference/resources/contact-entries
 */
final class ContactEntryResource extends Resource
{
    protected const string TYPE = 'contact_entries';

    protected const string PATH = 'contact_entries';

    /**
     * Get contact entries.
     *
     * GET /contact_entries
     *
     * @return PendingQuery<ContactEntry>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(ContactEntry::class, 'contact_entries.index');
    }

    /**
     * Gets a contact entry.
     *
     * GET /contact_entries/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): ContactEntry
    {
        return $this->fetchOne(ContactEntry::class, $this->path($id), 'contact_entries.show', (new Query())->include(...$include));
    }

    /**
     * Create a contact entry.
     *
     * POST /contact_entries
     *
     * @param  CreateContactEntryData|array<string, mixed>  $data
     */
    public function create(CreateContactEntryData|array $data): ContactEntry
    {
        return $this->write(ContactEntry::class, Method::Post, $this->path(), 'contact_entries.create', $data);
    }

    /**
     * Update a contact entry.
     *
     * PATCH /contact_entries/{id}
     *
     * @param  UpdateContactEntryData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateContactEntryData|array $data): ContactEntry
    {
        return $this->write(ContactEntry::class, Method::Patch, $this->path($id), 'contact_entries.update', $data, (string) $id);
    }

    /**
     * Deletes a contact entry.
     *
     * DELETE /contact_entries/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'contact_entries.destroy');
    }
}
