<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateCustomFieldData;
use Axyr\Productive\Data\Input\UpdateCustomFieldData;
use Axyr\Productive\Data\Models\CustomField;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * User-defined field on tasks, deals, people, pages, or other resources. Supports text, number, date, dropdown, multi-select, person, and file data types. Can be marked required, sensitive, global, or scoped to a project or section. Dropdown fields have selectable options via custom_field_options.
 *
 * @see https://developer.productive.io/reference/resources/custom-fields
 */
final class CustomFieldResource extends Resource
{
    protected const string TYPE = 'custom_fields';

    protected const string PATH = 'custom_fields';

    /**
     * Get custom fields.
     *
     * GET /custom_fields
     *
     * @return PendingQuery<CustomField>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(CustomField::class, 'custom_fields.index');
    }

    /**
     * Gets a custom field.
     *
     * GET /custom_fields/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): CustomField
    {
        return $this->fetchOne(CustomField::class, $this->path($id), 'custom_fields.show', (new Query())->include(...$include));
    }

    /**
     * Creates a custom field.
     *
     * POST /custom_fields
     *
     * @param  CreateCustomFieldData|array<string, mixed>  $data
     */
    public function create(CreateCustomFieldData|array $data): CustomField
    {
        return $this->write(CustomField::class, Method::Post, $this->path(), 'custom_fields.create', $data);
    }

    /**
     * Updates a custom field.
     *
     * PATCH /custom_fields/{id}
     *
     * @param  UpdateCustomFieldData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateCustomFieldData|array $data): CustomField
    {
        return $this->write(CustomField::class, Method::Patch, $this->path($id), 'custom_fields.update', $data, (string) $id);
    }

    /**
     * Archives a custom field.
     *
     * PATCH /custom_fields/{id}/archive
     */
    public function archive(int|string $id): CustomField
    {
        return $this->write(CustomField::class, Method::Patch, $this->path($id, 'archive'), 'custom_fields.archive', null);
    }
}
