<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CopyDealData;
use Axyr\Productive\Data\Input\CreateDealData;
use Axyr\Productive\Data\Input\UpdateDealData;
use Axyr\Productive\Data\Models\Deal;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A deal or budget representing a sales opportunity or production budget, with services, financials, and pipeline tracking.
 *
 * @see https://developer.productive.io/reference/resources/deals
 */
final class DealResource extends Resource
{
    protected const string TYPE = 'deals';

    protected const string PATH = 'deals';

    /**
     * Get deals.
     *
     * GET /deals
     *
     * @return PendingQuery<Deal>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Deal::class, 'deals.index');
    }

    /**
     * Gets a deal.
     *
     * GET /deals/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Deal
    {
        return $this->fetchOne(Deal::class, $this->path($id), 'deals.show', (new Query())->include(...$include));
    }

    /**
     * Create a deal.
     *
     * POST /deals
     *
     * @param  CreateDealData|array<string, mixed>  $data
     */
    public function create(CreateDealData|array $data): Deal
    {
        return $this->write(Deal::class, Method::Post, $this->path(), 'deals.create', $data);
    }

    /**
     * Update a deal.
     *
     * PATCH /deals/{id}
     *
     * @param  UpdateDealData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateDealData|array $data): Deal
    {
        return $this->write(Deal::class, Method::Patch, $this->path($id), 'deals.update', $data, (string) $id);
    }

    /**
     * Deletes a deal.
     *
     * DELETE /deals/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'deals.destroy');
    }

    /**
     * Closes a deal.
     *
     * PATCH /deals/{id}/close
     */
    public function close(int|string $id): Deal
    {
        return $this->write(Deal::class, Method::Patch, $this->path($id, 'close'), 'deals.close', null);
    }

    /**
     * Copies a deal.
     *
     * POST /deals/copy
     *
     * @param  CopyDealData|array<string, mixed>  $data
     */
    public function copy(CopyDealData|array $data): ?Deal
    {
        return $this->writeAsBulk(Deal::class, Method::Post, $this->path('copy'), 'deals.copy', $data);
    }

    /**
     * Creates a budget from origin deal.
     *
     * POST /deals/create_from_origin
     *
     * @param  array<string, mixed>  $data  Attributes, if the endpoint needs any: the spec documents none. Nothing is sent when empty.
     */
    public function createFromOrigin(array $data = []): ?Deal
    {
        return $this->writeOptional(Deal::class, Method::Post, $this->path('create_from_origin'), 'deals.create_from_origin', $data === [] ? null : $data);
    }

    /**
     * Opens a deal.
     *
     * PATCH /deals/{id}/open
     */
    public function open(int|string $id): Deal
    {
        return $this->write(Deal::class, Method::Patch, $this->path($id, 'open'), 'deals.open', null);
    }
}
