<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateDealCostRateData;
use Axyr\Productive\Data\Input\UpdateDealCostRateData;
use Axyr\Productive\Data\Models\DealCostRate;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A person-specific cost rate override for a deal, used when the person's cost differs from the standard salary rate.
 *
 * @see https://developer.productive.io/reference/resources/deal-cost-rates
 */
final class DealCostRateResource extends Resource
{
    protected const string TYPE = 'deal_cost_rates';

    protected const string PATH = 'deal_cost_rates';

    /**
     * Get deal cost rates.
     *
     * GET /deal_cost_rates
     *
     * @return PendingQuery<DealCostRate>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(DealCostRate::class, 'deal_cost_rates.index');
    }

    /**
     * Gets a deal cost rate.
     *
     * GET /deal_cost_rates/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): DealCostRate
    {
        return $this->fetchOne(DealCostRate::class, $this->path($id), 'deal_cost_rates.show', (new Query())->include(...$include));
    }

    /**
     * Create a deal cost rate.
     *
     * POST /deal_cost_rates
     *
     * @param  CreateDealCostRateData|array<string, mixed>  $data
     */
    public function create(CreateDealCostRateData|array $data): DealCostRate
    {
        return $this->write(DealCostRate::class, Method::Post, $this->path(), 'deal_cost_rates.create', $data);
    }

    /**
     * Update a deal cost rate.
     *
     * PATCH /deal_cost_rates/{id}
     *
     * @param  UpdateDealCostRateData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateDealCostRateData|array $data): DealCostRate
    {
        return $this->write(DealCostRate::class, Method::Patch, $this->path($id), 'deal_cost_rates.update', $data, (string) $id);
    }

    /**
     * Deletes a deal cost rate.
     *
     * DELETE /deal_cost_rates/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'deal_cost_rates.destroy');
    }
}
