<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateEinvoiceIdentityData;
use Axyr\Productive\Data\Input\UpdateEinvoiceIdentityData;
use Axyr\Productive\Data\Models\EinvoiceIdentity;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * @see https://developer.productive.io/reference/resources/einvoice-identities
 */
final class EinvoiceIdentityResource extends Resource
{
    protected const string TYPE = 'einvoice_identities';

    protected const string PATH = 'einvoice_identities';

    /**
     * Gets a list of e-invoice identities.
     *
     * GET /einvoice_identities
     *
     * @return PendingQuery<EinvoiceIdentity>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(EinvoiceIdentity::class, 'einvoice_identities.index');
    }

    /**
     * Gets an e-invoice identity.
     *
     * GET /einvoice_identities/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): EinvoiceIdentity
    {
        return $this->fetchOne(EinvoiceIdentity::class, $this->path($id), 'einvoice_identities.show', (new Query())->include(...$include));
    }

    /**
     * Creates an e-invoice identity.
     *
     * POST /einvoice_identities
     *
     * @param  CreateEinvoiceIdentityData|array<string, mixed>  $data
     */
    public function create(CreateEinvoiceIdentityData|array $data): EinvoiceIdentity
    {
        return $this->write(EinvoiceIdentity::class, Method::Post, $this->path(), 'einvoice_identities.create', $data);
    }

    /**
     * Updates an e-invoice identity.
     *
     * PATCH /einvoice_identities/{id}
     *
     * @param  UpdateEinvoiceIdentityData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateEinvoiceIdentityData|array $data): EinvoiceIdentity
    {
        return $this->write(EinvoiceIdentity::class, Method::Patch, $this->path($id), 'einvoice_identities.update', $data, (string) $id);
    }
}
