<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateExpenseLineItemData;
use Axyr\Productive\Data\Input\UpdateExpenseLineItemData;
use Axyr\Productive\Data\Models\ExpenseLineItem;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Pagination\ModelCollection;
use Axyr\Productive\Query\Query;

/**
 * @see https://developer.productive.io/reference/resources/expense-line-items
 */
final class ExpenseLineItemResource extends Resource
{
    protected const string TYPE = 'expense_line_items';

    protected const string PATH = 'expense_line_items';

    /**
     * Get expense line items.
     *
     * GET /expense_line_items
     *
     * @return PendingQuery<ExpenseLineItem>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(ExpenseLineItem::class, 'expense_line_items.index');
    }

    /**
     * Gets an expense line item.
     *
     * GET /expense_line_items/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): ExpenseLineItem
    {
        return $this->fetchOne(ExpenseLineItem::class, $this->path($id), 'expense_line_items.show', (new Query())->include(...$include));
    }

    /**
     * Create a single resource (synthesized: the spec only documents the bulk variant).
     *
     * POST /expense_line_items
     *
     * @param  CreateExpenseLineItemData|array<string, mixed>  $data
     */
    public function create(CreateExpenseLineItemData|array $data): ExpenseLineItem
    {
        return $this->write(ExpenseLineItem::class, Method::Post, $this->path(), 'expense_line_items.create', $data);
    }

    /**
     * Create expense line items.
     *
     * POST /expense_line_items (bulk)
     *
     * @param  list<CreateExpenseLineItemData|array<string, mixed>>  $entries
     * @return ModelCollection<ExpenseLineItem>
     */
    public function bulkCreate(array $entries): ModelCollection
    {
        $items = array_map(fn(CreateExpenseLineItemData|array $entry): array => ['attributes' => self::attributes($entry)], $entries);

        /** @var ModelCollection<ExpenseLineItem> */
        return $this->bulkWrite(Method::Post, 'expense_line_items.create_bulk', $items);
    }

    /**
     * Update expense line items.
     *
     * PATCH /expense_line_items (bulk)
     *
     * @param  array<int|string, UpdateExpenseLineItemData|array<string, mixed>>  $updates  Keyed by ID.
     * @return ModelCollection<ExpenseLineItem>
     */
    public function bulkUpdate(array $updates): ModelCollection
    {
        $items = [];

        foreach ($updates as $id => $update) {
            $items[] = ['id' => (string) $id, 'attributes' => self::attributes($update)];
        }

        /** @var ModelCollection<ExpenseLineItem> */
        return $this->bulkWrite(Method::Patch, 'expense_line_items.update_bulk', $items);
    }

    /**
     * Delete expense line items.
     *
     * DELETE /expense_line_items (bulk)
     *
     * @param  list<int|string>  $ids
     */
    public function bulkDelete(array $ids): void
    {
        $this->bulkWithoutResponse(Method::Delete, $this->path(), 'expense_line_items.destroy_bulk', $ids);
    }
}
