<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateInvoiceData;
use Axyr\Productive\Data\Input\SendEinvoiceInvoiceData;
use Axyr\Productive\Data\Input\UpdateInvoiceData;
use Axyr\Productive\Data\Models\Invoice;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A billing document issued to a client. Invoices progress through draft, finalized, sent, and paid stages, and contain line items drawn from budget services.
 *
 * @see https://developer.productive.io/reference/resources/invoices
 */
final class InvoiceResource extends Resource
{
    protected const string TYPE = 'invoices';

    protected const string PATH = 'invoices';

    /**
     * Get invoices.
     *
     * GET /invoices
     *
     * @return PendingQuery<Invoice>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Invoice::class, 'invoices.index');
    }

    /**
     * Gets an invoice.
     *
     * GET /invoices/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Invoice
    {
        return $this->fetchOne(Invoice::class, $this->path($id), 'invoices.show', (new Query())->include(...$include));
    }

    /**
     * Create an invoice.
     *
     * POST /invoices
     *
     * @param  CreateInvoiceData|array<string, mixed>  $data
     */
    public function create(CreateInvoiceData|array $data): Invoice
    {
        return $this->write(Invoice::class, Method::Post, $this->path(), 'invoices.create', $data);
    }

    /**
     * Update an invoice.
     *
     * PATCH /invoices/{id}
     *
     * @param  UpdateInvoiceData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateInvoiceData|array $data): Invoice
    {
        return $this->write(Invoice::class, Method::Patch, $this->path($id), 'invoices.update', $data, (string) $id);
    }

    /**
     * Deletes an invoice.
     *
     * DELETE /invoices/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'invoices.destroy');
    }

    /**
     * Exports an invoice.
     *
     * PATCH /invoices/{id}/export
     */
    public function export(int|string $id): Invoice
    {
        return $this->write(Invoice::class, Method::Patch, $this->path($id, 'export'), 'invoices.export', null);
    }

    /**
     * Updates an exported invoice.
     *
     * PATCH /invoices/{id}/export_update
     */
    public function exportUpdate(int|string $id): Invoice
    {
        return $this->write(Invoice::class, Method::Patch, $this->path($id, 'export_update'), 'invoices.export_update', null);
    }

    /**
     * Finalizes an invoice.
     *
     * PATCH /invoices/{id}/finalize
     */
    public function finalize(int|string $id): Invoice
    {
        return $this->write(Invoice::class, Method::Patch, $this->path($id, 'finalize'), 'invoices.finalize', null);
    }

    /**
     * Preview invoice.
     *
     * GET /invoices/{id}/preview
     */
    public function preview(int|string $id): Invoice
    {
        return $this->fetchOne(Invoice::class, $this->path($id, 'preview'), 'invoices.preview');
    }

    /**
     * Sends an invoice.
     *
     * PATCH /invoices/{id}/send
     */
    public function send(int|string $id): Invoice
    {
        return $this->write(Invoice::class, Method::Patch, $this->path($id, 'send'), 'invoices.send', null);
    }

    /**
     * Sends an e-invoice.
     *
     * PATCH /invoices/{id}/send_einvoice
     *
     * @param  SendEinvoiceInvoiceData|array<string, mixed>  $data
     */
    public function sendEinvoice(int|string $id, SendEinvoiceInvoiceData|array $data): Invoice
    {
        return $this->write(Invoice::class, Method::Patch, $this->path($id, 'send_einvoice'), 'invoices.send_einvoice', $data, (string) $id);
    }
}
