<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateLostReasonData;
use Axyr\Productive\Data\Input\UpdateLostReasonData;
use Axyr\Productive\Data\Models\LostReason;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A label explaining why a deal was lost, used for sales pipeline analytics.
 *
 * @see https://developer.productive.io/reference/resources/lost-reasons
 */
final class LostReasonResource extends Resource
{
    protected const string TYPE = 'lost_reasons';

    protected const string PATH = 'lost_reasons';

    /**
     * Get lost reasons.
     *
     * GET /lost_reasons
     *
     * @return PendingQuery<LostReason>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(LostReason::class, 'lost_reasons.index');
    }

    /**
     * Gets a lost reason.
     *
     * GET /lost_reasons/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): LostReason
    {
        return $this->fetchOne(LostReason::class, $this->path($id), 'lost_reasons.show', (new Query())->include(...$include));
    }

    /**
     * Create a lost reason.
     *
     * POST /lost_reasons
     *
     * @param  CreateLostReasonData|array<string, mixed>  $data
     */
    public function create(CreateLostReasonData|array $data): LostReason
    {
        return $this->write(LostReason::class, Method::Post, $this->path(), 'lost_reasons.create', $data);
    }

    /**
     * Update a lost reason.
     *
     * PATCH /lost_reasons/{id}
     *
     * @param  UpdateLostReasonData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateLostReasonData|array $data): LostReason
    {
        return $this->write(LostReason::class, Method::Patch, $this->path($id), 'lost_reasons.update', $data, (string) $id);
    }

    /**
     * Archives a lost reason.
     *
     * PATCH /lost_reasons/{id}/archive
     */
    public function archive(int|string $id): LostReason
    {
        return $this->write(LostReason::class, Method::Patch, $this->path($id, 'archive'), 'lost_reasons.archive', null);
    }
}
