<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateMembershipData;
use Axyr\Productive\Data\Input\UpdateMembershipData;
use Axyr\Productive\Data\Models\Membership;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * Access control record granting a person or team access to a project, deal, page, dashboard, filter, survey, or agent. Defines the access level (type_id) and optional restrictions (options). Memberships drive visibility and edit permissions for shared resources.
 *
 * @see https://developer.productive.io/reference/resources/memberships
 */
final class MembershipResource extends Resource
{
    protected const string TYPE = 'memberships';

    protected const string PATH = 'memberships';

    /**
     * Get memberships.
     *
     * GET /memberships
     *
     * @return PendingQuery<Membership>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Membership::class, 'memberships.index');
    }

    /**
     * Gets a membership.
     *
     * GET /memberships/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Membership
    {
        return $this->fetchOne(Membership::class, $this->path($id), 'memberships.show', (new Query())->include(...$include));
    }

    /**
     * Create a membership.
     *
     * POST /memberships
     *
     * @param  CreateMembershipData|array<string, mixed>  $data
     */
    public function create(CreateMembershipData|array $data): Membership
    {
        return $this->write(Membership::class, Method::Post, $this->path(), 'memberships.create', $data);
    }

    /**
     * Update a membership.
     *
     * PATCH /memberships/{id}
     *
     * @param  UpdateMembershipData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateMembershipData|array $data): Membership
    {
        return $this->write(Membership::class, Method::Patch, $this->path($id), 'memberships.update', $data, (string) $id);
    }

    /**
     * Deletes a membership.
     *
     * DELETE /memberships/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'memberships.destroy');
    }
}
