<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Models\Notification;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * An inbox notification for a user about changes to subscribed entities.
 *
 * @see https://developer.productive.io/reference/resources/notifications
 */
final class NotificationResource extends Resource
{
    protected const string TYPE = 'notifications';

    protected const string PATH = 'notifications';

    /**
     * Get notifications.
     *
     * GET /notifications
     *
     * @return PendingQuery<Notification>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Notification::class, 'notifications.index');
    }

    /**
     * Shows a notification.
     *
     * GET /notifications/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Notification
    {
        return $this->fetchOne(Notification::class, $this->path($id), 'notifications.show', (new Query())->include(...$include));
    }

    /**
     * Dismisses a notification.
     *
     * PATCH /notifications/{id}/dismiss
     */
    public function dismiss(int|string $id): Notification
    {
        return $this->write(Notification::class, Method::Patch, $this->path($id, 'dismiss'), 'notifications.dismiss', null);
    }

    /**
     * Reads a notification.
     *
     * PATCH /notifications/{id}/read
     */
    public function read(int|string $id): Notification
    {
        return $this->write(Notification::class, Method::Patch, $this->path($id, 'read'), 'notifications.read', null);
    }

    /**
     * Undismisses a notification.
     *
     * PATCH /notifications/{id}/undismiss
     */
    public function undismiss(int|string $id): Notification
    {
        return $this->write(Notification::class, Method::Patch, $this->path($id, 'undismiss'), 'notifications.undismiss', null);
    }

    /**
     * Marks a notification as unread.
     *
     * PATCH /notifications/{id}/unread
     */
    public function unread(int|string $id): Notification
    {
        return $this->write(Notification::class, Method::Patch, $this->path($id, 'unread'), 'notifications.unread', null);
    }
}
