<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\UpdateOrganizationData;
use Axyr\Productive\Data\Models\Organization;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * The organization resource representing the top-level account with global settings, preferences, and configuration.
 *
 * @see https://developer.productive.io/reference/resources/organizations
 */
final class OrganizationResource extends Resource
{
    protected const string TYPE = 'organizations';

    protected const string PATH = 'organizations';

    /**
     * Get organizations.
     *
     * GET /organizations
     *
     * @return PendingQuery<Organization>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Organization::class, 'organizations.index');
    }

    /**
     * Get an organization.
     *
     * GET /organizations/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Organization
    {
        return $this->fetchOne(Organization::class, $this->path($id), 'organizations.show', (new Query())->include(...$include));
    }

    /**
     * Update an organization.
     *
     * PATCH /organizations/{id}
     *
     * @param  UpdateOrganizationData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateOrganizationData|array $data): Organization
    {
        return $this->write(Organization::class, Method::Patch, $this->path($id), 'organizations.update', $data, (string) $id);
    }

    /**
     * Delete an organization.
     *
     * DELETE /organizations/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'organizations.destroy');
    }

    /**
     * Resend verification code.
     *
     * PATCH /organizations/{id}/resend_code
     */
    public function resendCode(int|string $id): ?Organization
    {
        return $this->writeOptional(Organization::class, Method::Patch, $this->path($id, 'resend_code'), 'organizations.resend_code', null);
    }
}
