<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreatePasswordData;
use Axyr\Productive\Data\Input\UpdatePasswordData;
use Axyr\Productive\Data\Models\Password;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A password reset or change request, identified by a reset token.
 *
 * @see https://developer.productive.io/reference/resources/passwords
 */
final class PasswordResource extends Resource
{
    protected const string TYPE = 'passwords';

    protected const string PATH = 'passwords';

    /**
     * Gets a password.
     *
     * GET /passwords/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Password
    {
        return $this->fetchOne(Password::class, $this->path($id), 'passwords.show', (new Query())->include(...$include));
    }

    /**
     * Create a password.
     *
     * POST /passwords
     *
     * @param  CreatePasswordData|array<string, mixed>  $data
     */
    public function create(CreatePasswordData|array $data): ?Password
    {
        return $this->writeOptional(Password::class, Method::Post, $this->path(), 'passwords.create', $data);
    }

    /**
     * Update a password.
     *
     * PATCH /passwords/{id}
     *
     * @param  UpdatePasswordData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdatePasswordData|array $data): ?Password
    {
        return $this->writeOptional(Password::class, Method::Patch, $this->path($id), 'passwords.update', $data, (string) $id);
    }
}
