<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreatePipelineData;
use Axyr\Productive\Data\Input\UpdatePipelineData;
use Axyr\Productive\Data\Models\Pipeline;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A sales or production pipeline defining the stages that deals progress through.
 *
 * @see https://developer.productive.io/reference/resources/pipelines
 */
final class PipelineResource extends Resource
{
    protected const string TYPE = 'pipelines';

    protected const string PATH = 'pipelines';

    /**
     * Get pipelines.
     *
     * GET /pipelines
     *
     * @return PendingQuery<Pipeline>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Pipeline::class, 'pipelines.index');
    }

    /**
     * Gets a pipeline.
     *
     * GET /pipelines/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Pipeline
    {
        return $this->fetchOne(Pipeline::class, $this->path($id), 'pipelines.show', (new Query())->include(...$include));
    }

    /**
     * Create a pipeline.
     *
     * POST /pipelines
     *
     * @param  CreatePipelineData|array<string, mixed>  $data
     */
    public function create(CreatePipelineData|array $data): Pipeline
    {
        return $this->write(Pipeline::class, Method::Post, $this->path(), 'pipelines.create', $data);
    }

    /**
     * Update a pipeline.
     *
     * PATCH /pipelines/{id}
     *
     * @param  UpdatePipelineData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdatePipelineData|array $data): Pipeline
    {
        return $this->write(Pipeline::class, Method::Patch, $this->path($id), 'pipelines.update', $data, (string) $id);
    }

    /**
     * Deletes a pipeline.
     *
     * DELETE /pipelines/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'pipelines.destroy');
    }
}
