<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreatePlaceholderUsageData;
use Axyr\Productive\Data\Input\UpdatePlaceholderUsageData;
use Axyr\Productive\Data\Models\PlaceholderUsage;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A record linking a placeholder to a specific task or todo field, optionally with a date offset interval.
 *
 * @see https://developer.productive.io/reference/resources/placeholder-usages
 */
final class PlaceholderUsageResource extends Resource
{
    protected const string TYPE = 'placeholder_usages';

    protected const string PATH = 'placeholder_usages';

    /**
     * Get placeholder usages.
     *
     * GET /placeholder_usages
     *
     * @return PendingQuery<PlaceholderUsage>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(PlaceholderUsage::class, 'placeholder_usages.index');
    }

    /**
     * Gets a placeholder usage.
     *
     * GET /placeholder_usages/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): PlaceholderUsage
    {
        return $this->fetchOne(PlaceholderUsage::class, $this->path($id), 'placeholder_usages.show', (new Query())->include(...$include));
    }

    /**
     * Create a placeholder usage.
     *
     * POST /placeholder_usages
     *
     * @param  CreatePlaceholderUsageData|array<string, mixed>  $data
     */
    public function create(CreatePlaceholderUsageData|array $data): PlaceholderUsage
    {
        return $this->write(PlaceholderUsage::class, Method::Post, $this->path(), 'placeholder_usages.create', $data);
    }

    /**
     * Update a placeholder usage.
     *
     * PATCH /placeholder_usages/{id}
     *
     * @param  UpdatePlaceholderUsageData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdatePlaceholderUsageData|array $data): PlaceholderUsage
    {
        return $this->write(PlaceholderUsage::class, Method::Patch, $this->path($id), 'placeholder_usages.update', $data, (string) $id);
    }

    /**
     * Deletes a placeholder usage.
     *
     * DELETE /placeholder_usages/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'placeholder_usages.destroy');
    }
}
