<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreatePriceData;
use Axyr\Productive\Data\Input\UpdatePriceData;
use Axyr\Productive\Data\Models\Price;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A rate card line item defining billing type, hourly/daily rate, tracking unit, and default settings for new services.
 *
 * @see https://developer.productive.io/reference/resources/prices
 */
final class PriceResource extends Resource
{
    protected const string TYPE = 'prices';

    protected const string PATH = 'prices';

    /**
     * Get prices.
     *
     * GET /prices
     *
     * @return PendingQuery<Price>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Price::class, 'prices.index');
    }

    /**
     * Gets a price.
     *
     * GET /prices/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Price
    {
        return $this->fetchOne(Price::class, $this->path($id), 'prices.show', (new Query())->include(...$include));
    }

    /**
     * Create a price.
     *
     * POST /prices
     *
     * @param  CreatePriceData|array<string, mixed>  $data
     */
    public function create(CreatePriceData|array $data): Price
    {
        return $this->write(Price::class, Method::Post, $this->path(), 'prices.create', $data);
    }

    /**
     * Update a price.
     *
     * PATCH /prices/{id}
     *
     * @param  UpdatePriceData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdatePriceData|array $data): Price
    {
        return $this->write(Price::class, Method::Patch, $this->path($id), 'prices.update', $data, (string) $id);
    }

    /**
     * Deletes a price.
     *
     * DELETE /prices/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'prices.destroy');
    }
}
