<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\ApplyNavigationTabsProjectData;
use Axyr\Productive\Data\Input\ChangeWorkflowProjectData;
use Axyr\Productive\Data\Input\CopyProjectData;
use Axyr\Productive\Data\Input\CreateProjectData;
use Axyr\Productive\Data\Input\UpdateProjectData;
use Axyr\Productive\Data\Models\Project;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A workspace for tasks, documents, surveys, and budgets. Projects can be billable (client work) or internal (overhead), and provide the organizational structure for team collaboration.
 *
 * @see https://developer.productive.io/reference/resources/projects
 */
final class ProjectResource extends Resource
{
    protected const string TYPE = 'projects';

    protected const string PATH = 'projects';

    /**
     * Get projects.
     *
     * GET /projects
     *
     * @return PendingQuery<Project>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Project::class, 'projects.index');
    }

    /**
     * Gets a project.
     *
     * GET /projects/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Project
    {
        return $this->fetchOne(Project::class, $this->path($id), 'projects.show', (new Query())->include(...$include));
    }

    /**
     * Create a project.
     *
     * POST /projects
     *
     * @param  CreateProjectData|array<string, mixed>  $data
     */
    public function create(CreateProjectData|array $data): Project
    {
        return $this->write(Project::class, Method::Post, $this->path(), 'projects.create', $data);
    }

    /**
     * Update a project.
     *
     * PATCH /projects/{id}
     *
     * @param  UpdateProjectData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateProjectData|array $data): Project
    {
        return $this->write(Project::class, Method::Patch, $this->path($id), 'projects.update', $data, (string) $id);
    }

    /**
     * Deletes a project.
     *
     * DELETE /projects/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'projects.destroy');
    }

    /**
     * Applies navigation tabs from a template to the project.
     *
     * PATCH /projects/{id}/apply_navigation_tabs
     *
     * @param  ApplyNavigationTabsProjectData|array<string, mixed>  $data
     */
    public function applyNavigationTabs(int|string $id, ApplyNavigationTabsProjectData|array $data): Project
    {
        return $this->write(Project::class, Method::Patch, $this->path($id, 'apply_navigation_tabs'), 'projects.apply_navigation_tabs', $data, (string) $id);
    }

    /**
     * Archives a project.
     *
     * PATCH /projects/{id}/archive
     */
    public function archive(int|string $id): Project
    {
        return $this->write(Project::class, Method::Patch, $this->path($id, 'archive'), 'projects.archive', null);
    }

    /**
     * Changes workflow on project.
     *
     * PATCH /projects/{id}/change_workflow
     *
     * @param  ChangeWorkflowProjectData|array<string, mixed>  $data
     */
    public function changeWorkflow(int|string $id, ChangeWorkflowProjectData|array $data): Project
    {
        return $this->write(Project::class, Method::Patch, $this->path($id, 'change_workflow'), 'projects.change_workflow', $data, (string) $id);
    }

    /**
     * Copies a project.
     *
     * POST /projects/copy
     *
     * @param  CopyProjectData|array<string, mixed>  $data
     */
    public function copy(CopyProjectData|array $data): Project
    {
        return $this->write(Project::class, Method::Post, $this->path('copy'), 'projects.copy', $data);
    }

    /**
     * Restores a project.
     *
     * PATCH /projects/{id}/restore
     */
    public function restore(int|string $id): Project
    {
        return $this->write(Project::class, Method::Patch, $this->path($id, 'restore'), 'projects.restore', null);
    }

    /**
     * Subscribes to project.
     *
     * PATCH /projects/{id}/subscribe
     */
    public function subscribe(int|string $id): Project
    {
        return $this->write(Project::class, Method::Patch, $this->path($id, 'subscribe'), 'projects.subscribe', null);
    }

    /**
     * Unsubscribes from project.
     *
     * PATCH /projects/{id}/unsubscribe
     */
    public function unsubscribe(int|string $id): Project
    {
        return $this->write(Project::class, Method::Patch, $this->path($id, 'unsubscribe'), 'projects.unsubscribe', null);
    }
}
