<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateProjectPreferenceData;
use Axyr\Productive\Data\Input\UpdateProjectPreferenceData;
use Axyr\Productive\Data\Models\ProjectPreference;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A person's assignment to a project together with their personal preferences for it — task layout, watch state and free-form view settings.
 *
 * @see https://developer.productive.io/reference/resources/project-preferences
 */
final class ProjectPreferenceResource extends Resource
{
    protected const string TYPE = 'project_preferences';

    protected const string PATH = 'project_preferences';

    /**
     * Get project preferences.
     *
     * GET /project_preferences
     *
     * @return PendingQuery<ProjectPreference>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(ProjectPreference::class, 'project_preferences.index');
    }

    /**
     * Get a project preference.
     *
     * GET /project_preferences/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): ProjectPreference
    {
        return $this->fetchOne(ProjectPreference::class, $this->path($id), 'project_preferences.show', (new Query())->include(...$include));
    }

    /**
     * Create a project preference.
     *
     * POST /project_preferences
     *
     * @param  CreateProjectPreferenceData|array<string, mixed>  $data
     */
    public function create(CreateProjectPreferenceData|array $data): ProjectPreference
    {
        return $this->write(ProjectPreference::class, Method::Post, $this->path(), 'project_preferences.create', $data);
    }

    /**
     * Update a project preference.
     *
     * PATCH /project_preferences/{id}
     *
     * @param  UpdateProjectPreferenceData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateProjectPreferenceData|array $data): ProjectPreference
    {
        return $this->write(ProjectPreference::class, Method::Patch, $this->path($id), 'project_preferences.update', $data, (string) $id);
    }

    /**
     * Delete a project preference.
     *
     * DELETE /project_preferences/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'project_preferences.destroy');
    }
}
