<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CopyPurchaseOrderData;
use Axyr\Productive\Data\Input\CreatePurchaseOrderData;
use Axyr\Productive\Data\Input\ExportPurchaseOrderData;
use Axyr\Productive\Data\Input\ExportUpdatePurchaseOrderData;
use Axyr\Productive\Data\Input\SendPurchaseOrderData;
use Axyr\Productive\Data\Input\UpdatePurchaseOrderData;
use Axyr\Productive\Data\Models\PurchaseOrder;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Pagination\ModelCollection;
use Axyr\Productive\Query\Query;

/**
 * Vendor procurement document on a budget. Tracks subject, status, issued/delivery/received dates, vendor, amounts, and export status for accounting integration. Line items (expenses) are created from the PO and billed via bills.
 *
 * @see https://developer.productive.io/reference/resources/purchase-orders
 */
final class PurchaseOrderResource extends Resource
{
    protected const string TYPE = 'purchase_orders';

    protected const string PATH = 'purchase_orders';

    /**
     * Get purchase orders.
     *
     * GET /purchase_orders
     *
     * @return PendingQuery<PurchaseOrder>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(PurchaseOrder::class, 'purchase_orders.index');
    }

    /**
     * Gets a purchase order.
     *
     * GET /purchase_orders/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): PurchaseOrder
    {
        return $this->fetchOne(PurchaseOrder::class, $this->path($id), 'purchase_orders.show', (new Query())->include(...$include));
    }

    /**
     * Create a purchase order.
     *
     * POST /purchase_orders
     *
     * @param  CreatePurchaseOrderData|array<string, mixed>  $data
     */
    public function create(CreatePurchaseOrderData|array $data): PurchaseOrder
    {
        return $this->write(PurchaseOrder::class, Method::Post, $this->path(), 'purchase_orders.create', $data);
    }

    /**
     * Update a purchase order.
     *
     * PATCH /purchase_orders/{id}
     *
     * @param  UpdatePurchaseOrderData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdatePurchaseOrderData|array $data): PurchaseOrder
    {
        return $this->write(PurchaseOrder::class, Method::Patch, $this->path($id), 'purchase_orders.update', $data, (string) $id);
    }

    /**
     * Deletes a purchase order.
     *
     * DELETE /purchase_orders/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'purchase_orders.destroy');
    }

    /**
     * Copies a purchase order.
     *
     * POST /purchase_orders/copy
     *
     * @param  CopyPurchaseOrderData|array<string, mixed>  $data
     */
    public function copy(CopyPurchaseOrderData|array $data): ?PurchaseOrder
    {
        return $this->writeOptional(PurchaseOrder::class, Method::Post, $this->path('copy'), 'purchase_orders.copy', $data);
    }

    /**
     * Exports a purchase order.
     *
     * PATCH /purchase_orders/{id}/export
     *
     * @param  ExportPurchaseOrderData|array<string, mixed>  $data
     */
    public function export(int|string $id, ExportPurchaseOrderData|array $data): PurchaseOrder
    {
        return $this->write(PurchaseOrder::class, Method::Patch, $this->path($id, 'export'), 'purchase_orders.export', $data, (string) $id);
    }

    /**
     * Updates exported purchase order.
     *
     * PATCH /purchase_orders/{id}/export_update
     *
     * @param  ExportUpdatePurchaseOrderData|array<string, mixed>  $data
     */
    public function exportUpdate(int|string $id, ExportUpdatePurchaseOrderData|array $data): PurchaseOrder
    {
        return $this->write(PurchaseOrder::class, Method::Patch, $this->path($id, 'export_update'), 'purchase_orders.export_update', $data, (string) $id);
    }

    /**
     * Sends a purchase order.
     *
     * PATCH /purchase_orders/{id}/send
     *
     * @param  SendPurchaseOrderData|array<string, mixed>  $data
     */
    public function send(int|string $id, SendPurchaseOrderData|array $data): PurchaseOrder
    {
        return $this->write(PurchaseOrder::class, Method::Patch, $this->path($id, 'send'), 'purchase_orders.send', $data, (string) $id);
    }

    /**
     * Update purchase orders.
     *
     * PATCH /purchase_orders (bulk)
     *
     * @param  array<int|string, UpdatePurchaseOrderData|array<string, mixed>>  $updates  Keyed by ID.
     * @return ModelCollection<PurchaseOrder>
     */
    public function bulkUpdate(array $updates): ModelCollection
    {
        $items = [];

        foreach ($updates as $id => $update) {
            $items[] = ['id' => (string) $id, 'attributes' => self::attributes($update)];
        }

        /** @var ModelCollection<PurchaseOrder> */
        return $this->bulkWrite(Method::Patch, 'purchase_orders.update_bulk', $items);
    }

    /**
     * Delete purchase orders.
     *
     * DELETE /purchase_orders (bulk)
     *
     * @param  list<int|string>  $ids
     */
    public function bulkDelete(array $ids): void
    {
        $this->bulkWithoutResponse(Method::Delete, $this->path(), 'purchase_orders.destroy_bulk', $ids);
    }
}
