<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateReportCategoryData;
use Axyr\Productive\Data\Input\UpdateReportCategoryData;
use Axyr\Productive\Data\Models\ReportCategory;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * An aggregated report category resource grouping saved report filters.
 *
 * @see https://developer.productive.io/reference/resources/report-categories
 */
final class ReportCategoryResource extends Resource
{
    protected const string TYPE = 'report_categories';

    protected const string PATH = 'report_categories';

    /**
     * Get report categories.
     *
     * GET /report_categories
     *
     * @return PendingQuery<ReportCategory>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(ReportCategory::class, 'report_categories.index');
    }

    /**
     * Gets a report category.
     *
     * GET /report_categories/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): ReportCategory
    {
        return $this->fetchOne(ReportCategory::class, $this->path($id), 'report_categories.show', (new Query())->include(...$include));
    }

    /**
     * Create a report category.
     *
     * POST /report_categories
     *
     * @param  CreateReportCategoryData|array<string, mixed>  $data
     */
    public function create(CreateReportCategoryData|array $data): ReportCategory
    {
        return $this->write(ReportCategory::class, Method::Post, $this->path(), 'report_categories.create', $data);
    }

    /**
     * Update a report category.
     *
     * PATCH /report_categories/{id}
     *
     * @param  UpdateReportCategoryData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateReportCategoryData|array $data): ReportCategory
    {
        return $this->write(ReportCategory::class, Method::Patch, $this->path($id), 'report_categories.update', $data, (string) $id);
    }

    /**
     * Deletes a report category.
     *
     * DELETE /report_categories/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'report_categories.destroy');
    }
}
