<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateSectionData;
use Axyr\Productive\Data\Input\UpdateSectionData;
use Axyr\Productive\Data\Models\Section;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * Represents a named grouping of services within a deal or budget, used to organize line items into logical sections.
 *
 * @see https://developer.productive.io/reference/resources/sections
 */
final class SectionResource extends Resource
{
    protected const string TYPE = 'sections';

    protected const string PATH = 'sections';

    /**
     * Get sections.
     *
     * GET /sections
     *
     * @return PendingQuery<Section>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Section::class, 'sections.index');
    }

    /**
     * Gets a section.
     *
     * GET /sections/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Section
    {
        return $this->fetchOne(Section::class, $this->path($id), 'sections.show', (new Query())->include(...$include));
    }

    /**
     * Create a section.
     *
     * POST /sections
     *
     * @param  CreateSectionData|array<string, mixed>  $data
     */
    public function create(CreateSectionData|array $data): Section
    {
        return $this->write(Section::class, Method::Post, $this->path(), 'sections.create', $data);
    }

    /**
     * Update a section.
     *
     * PATCH /sections/{id}
     *
     * @param  UpdateSectionData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateSectionData|array $data): Section
    {
        return $this->write(Section::class, Method::Patch, $this->path($id), 'sections.update', $data, (string) $id);
    }

    /**
     * Deletes a section.
     *
     * DELETE /sections/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'sections.destroy');
    }
}
