<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateServiceTypeAssignmentData;
use Axyr\Productive\Data\Input\UpdateServiceTypeAssignmentData;
use Axyr\Productive\Data\Models\ServiceTypeAssignment;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * @see https://developer.productive.io/reference/resources/service-type-assignments
 */
final class ServiceTypeAssignmentResource extends Resource
{
    protected const string TYPE = 'service_type_assignments';

    protected const string PATH = 'service_type_assignments';

    /**
     * Get service type assignments.
     *
     * GET /service_type_assignments
     *
     * @return PendingQuery<ServiceTypeAssignment>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(ServiceTypeAssignment::class, 'service_type_assignments.index');
    }

    /**
     * Gets a service type assignment.
     *
     * GET /service_type_assignments/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): ServiceTypeAssignment
    {
        return $this->fetchOne(ServiceTypeAssignment::class, $this->path($id), 'service_type_assignments.show', (new Query())->include(...$include));
    }

    /**
     * Create a service type assignment.
     *
     * POST /service_type_assignments
     *
     * @param  CreateServiceTypeAssignmentData|array<string, mixed>  $data
     */
    public function create(CreateServiceTypeAssignmentData|array $data): ServiceTypeAssignment
    {
        return $this->write(ServiceTypeAssignment::class, Method::Post, $this->path(), 'service_type_assignments.create', $data);
    }

    /**
     * Update a service type assignment.
     *
     * PATCH /service_type_assignments/{id}
     *
     * @param  UpdateServiceTypeAssignmentData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateServiceTypeAssignmentData|array $data): ServiceTypeAssignment
    {
        return $this->write(ServiceTypeAssignment::class, Method::Patch, $this->path($id), 'service_type_assignments.update', $data, (string) $id);
    }

    /**
     * Deletes a service type assignment.
     *
     * DELETE /service_type_assignments/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'service_type_assignments.destroy');
    }
}
