<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateSurveyFieldOptionData;
use Axyr\Productive\Data\Input\UpdateSurveyFieldOptionData;
use Axyr\Productive\Data\Models\SurveyFieldOption;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * Selectable option for a dropdown or multi-select survey field. Has a label and position for ordering.
 *
 * @see https://developer.productive.io/reference/resources/survey-field-options
 */
final class SurveyFieldOptionResource extends Resource
{
    protected const string TYPE = 'survey_field_options';

    protected const string PATH = 'survey_field_options';

    /**
     * Get survey field options.
     *
     * GET /survey_field_options
     *
     * @return PendingQuery<SurveyFieldOption>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(SurveyFieldOption::class, 'survey_field_options.index');
    }

    /**
     * Gets a survey field option.
     *
     * GET /survey_field_options/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): SurveyFieldOption
    {
        return $this->fetchOne(SurveyFieldOption::class, $this->path($id), 'survey_field_options.show', (new Query())->include(...$include));
    }

    /**
     * Creates a survey field option.
     *
     * POST /survey_field_options
     *
     * @param  CreateSurveyFieldOptionData|array<string, mixed>  $data
     */
    public function create(CreateSurveyFieldOptionData|array $data): SurveyFieldOption
    {
        return $this->write(SurveyFieldOption::class, Method::Post, $this->path(), 'survey_field_options.create', $data);
    }

    /**
     * Updates a survey field option.
     *
     * PATCH /survey_field_options/{id}
     *
     * @param  UpdateSurveyFieldOptionData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateSurveyFieldOptionData|array $data): SurveyFieldOption
    {
        return $this->write(SurveyFieldOption::class, Method::Patch, $this->path($id), 'survey_field_options.update', $data, (string) $id);
    }

    /**
     * Archives a survey field option.
     *
     * PATCH /survey_field_options/{id}/archive
     */
    public function archive(int|string $id): SurveyFieldOption
    {
        return $this->write(SurveyFieldOption::class, Method::Patch, $this->path($id, 'archive'), 'survey_field_options.archive', null);
    }
}
