<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateSurveyResponseData;
use Axyr\Productive\Data\Models\SurveyResponse;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * Submitted form response for a survey. Contains field values keyed by survey_field_id. Triggers any automations configured on the parent survey.
 *
 * @see https://developer.productive.io/reference/resources/survey-responses
 */
final class SurveyResponseResource extends Resource
{
    protected const string TYPE = 'survey_responses';

    protected const string PATH = 'survey_responses';

    /**
     * Get survey responses.
     *
     * GET /survey_responses
     *
     * @return PendingQuery<SurveyResponse>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(SurveyResponse::class, 'survey_responses.index');
    }

    /**
     * Gets a survey response.
     *
     * GET /survey_responses/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): SurveyResponse
    {
        return $this->fetchOne(SurveyResponse::class, $this->path($id), 'survey_responses.show', (new Query())->include(...$include));
    }

    /**
     * Create a survey response.
     *
     * POST /survey_responses
     *
     * @param  CreateSurveyResponseData|array<string, mixed>  $data
     */
    public function create(CreateSurveyResponseData|array $data): SurveyResponse
    {
        return $this->write(SurveyResponse::class, Method::Post, $this->path(), 'survey_responses.create', $data);
    }

    /**
     * Deletes a survey response.
     *
     * DELETE /survey_responses/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'survey_responses.destroy');
    }
}
