<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateSurveyFieldData;
use Axyr\Productive\Data\Input\UpdateSurveyFieldData;
use Axyr\Productive\Data\Models\SurveyField;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * Form field on a survey with a data type (text, number, date, dropdown, checkbox, file), label, required flag, position, and optional description. Dropdown fields have selectable options via survey_field_options.
 *
 * @see https://developer.productive.io/reference/resources/survey-fields
 */
final class SurveyFieldResource extends Resource
{
    protected const string TYPE = 'survey_fields';

    protected const string PATH = 'survey_fields';

    /**
     * Get survey fields.
     *
     * GET /survey_fields
     *
     * @return PendingQuery<SurveyField>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(SurveyField::class, 'survey_fields.index');
    }

    /**
     * Gets a survey field.
     *
     * GET /survey_fields/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): SurveyField
    {
        return $this->fetchOne(SurveyField::class, $this->path($id), 'survey_fields.show', (new Query())->include(...$include));
    }

    /**
     * Creates a survey field.
     *
     * POST /survey_fields
     *
     * @param  CreateSurveyFieldData|array<string, mixed>  $data
     */
    public function create(CreateSurveyFieldData|array $data): SurveyField
    {
        return $this->write(SurveyField::class, Method::Post, $this->path(), 'survey_fields.create', $data);
    }

    /**
     * Updates a survey field.
     *
     * PATCH /survey_fields/{id}
     *
     * @param  UpdateSurveyFieldData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateSurveyFieldData|array $data): SurveyField
    {
        return $this->write(SurveyField::class, Method::Patch, $this->path($id), 'survey_fields.update', $data, (string) $id);
    }

    /**
     * Archives a survey field.
     *
     * PATCH /survey_fields/{id}/archive
     */
    public function archive(int|string $id): SurveyField
    {
        return $this->write(SurveyField::class, Method::Patch, $this->path($id, 'archive'), 'survey_fields.archive', null);
    }
}
