<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Models\Tag;
use Axyr\Productive\Query\Query;

/**
 * A label that can be applied to companies, deals, invoices, people, projects, or tasks for categorization and filtering.
 *
 * @see https://developer.productive.io/reference/resources/tags
 */
final class TagResource extends Resource
{
    protected const string TYPE = 'tags';

    protected const string PATH = 'tags';

    /**
     * Get tags.
     *
     * GET /tags
     *
     * @return PendingQuery<Tag>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Tag::class, 'tags.index');
    }

    /**
     * Gets a tag.
     *
     * GET /tags/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Tag
    {
        return $this->fetchOne(Tag::class, $this->path($id), 'tags.show', (new Query())->include(...$include));
    }
}
