<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CopyTaskListData;
use Axyr\Productive\Data\Input\CreateTaskListData;
use Axyr\Productive\Data\Input\MoveTaskListData;
use Axyr\Productive\Data\Input\RepositionTaskListData;
use Axyr\Productive\Data\Input\UpdateTaskListData;
use Axyr\Productive\Data\Models\TaskList;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * Task grouping within a project folder. Supports name, position ordering, placement, archiving, and an email_key for creating tasks via email. Task lists belong to a project and optionally to a board (folder).
 *
 * @see https://developer.productive.io/reference/resources/task-lists
 */
final class TaskListResource extends Resource
{
    protected const string TYPE = 'task_lists';

    protected const string PATH = 'task_lists';

    /**
     * Get task lists.
     *
     * GET /task_lists
     *
     * @return PendingQuery<TaskList>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(TaskList::class, 'task_lists.index');
    }

    /**
     * Gets a task list.
     *
     * GET /task_lists/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): TaskList
    {
        return $this->fetchOne(TaskList::class, $this->path($id), 'task_lists.show', (new Query())->include(...$include));
    }

    /**
     * Create a task list.
     *
     * POST /task_lists
     *
     * @param  CreateTaskListData|array<string, mixed>  $data
     */
    public function create(CreateTaskListData|array $data): TaskList
    {
        return $this->write(TaskList::class, Method::Post, $this->path(), 'task_lists.create', $data);
    }

    /**
     * Update a task list.
     *
     * PATCH /task_lists/{id}
     *
     * @param  UpdateTaskListData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateTaskListData|array $data): TaskList
    {
        return $this->write(TaskList::class, Method::Patch, $this->path($id), 'task_lists.update', $data, (string) $id);
    }

    /**
     * Archives a task list.
     *
     * PATCH /task_lists/{id}/archive
     */
    public function archive(int|string $id): TaskList
    {
        return $this->write(TaskList::class, Method::Patch, $this->path($id, 'archive'), 'task_lists.archive', null);
    }

    /**
     * Copies a task list.
     *
     * POST /task_lists/copy
     *
     * @param  CopyTaskListData|array<string, mixed>  $data
     */
    public function copy(CopyTaskListData|array $data): TaskList
    {
        return $this->write(TaskList::class, Method::Post, $this->path('copy'), 'task_lists.copy', $data);
    }

    /**
     * Moves a task list.
     *
     * PATCH /task_lists/{id}/move
     *
     * @param  MoveTaskListData|array<string, mixed>  $data
     */
    public function move(int|string $id, MoveTaskListData|array $data): TaskList
    {
        return $this->write(TaskList::class, Method::Patch, $this->path($id, 'move'), 'task_lists.move', $data, (string) $id);
    }

    /**
     * Repositions a task list.
     *
     * PATCH /task_lists/{id}/reposition
     *
     * @param  RepositionTaskListData|array<string, mixed>  $data
     */
    public function reposition(int|string $id, RepositionTaskListData|array $data): TaskList
    {
        return $this->write(TaskList::class, Method::Patch, $this->path($id, 'reposition'), 'task_lists.reposition', $data, (string) $id);
    }

    /**
     * Restores a task list.
     *
     * PATCH /task_lists/{id}/restore
     */
    public function restore(int|string $id): TaskList
    {
        return $this->write(TaskList::class, Method::Patch, $this->path($id, 'restore'), 'task_lists.restore', null);
    }
}
