<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateTimeTrackingPolicyData;
use Axyr\Productive\Data\Input\UpdateTimeTrackingPolicyData;
use Axyr\Productive\Data\Models\TimeTrackingPolicy;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * A time tracking policy defines rules for how time entries can be logged, including limits and mandatory fields.
 *
 * @see https://developer.productive.io/reference/resources/time-tracking-policies
 */
final class TimeTrackingPolicyResource extends Resource
{
    protected const string TYPE = 'time_tracking_policies';

    protected const string PATH = 'time_tracking_policies';

    /**
     * Get time tracking policies.
     *
     * GET /time_tracking_policies
     *
     * @return PendingQuery<TimeTrackingPolicy>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(TimeTrackingPolicy::class, 'time_tracking_policies.index');
    }

    /**
     * Gets a time tracking policy.
     *
     * GET /time_tracking_policies/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): TimeTrackingPolicy
    {
        return $this->fetchOne(TimeTrackingPolicy::class, $this->path($id), 'time_tracking_policies.show', (new Query())->include(...$include));
    }

    /**
     * Create a time tracking policy.
     *
     * POST /time_tracking_policies
     *
     * @param  CreateTimeTrackingPolicyData|array<string, mixed>  $data
     */
    public function create(CreateTimeTrackingPolicyData|array $data): TimeTrackingPolicy
    {
        return $this->write(TimeTrackingPolicy::class, Method::Post, $this->path(), 'time_tracking_policies.create', $data);
    }

    /**
     * Update a time tracking policy.
     *
     * PATCH /time_tracking_policies/{id}
     *
     * @param  UpdateTimeTrackingPolicyData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateTimeTrackingPolicyData|array $data): TimeTrackingPolicy
    {
        return $this->write(TimeTrackingPolicy::class, Method::Patch, $this->path($id), 'time_tracking_policies.update', $data, (string) $id);
    }

    /**
     * Deletes a time tracking policy.
     *
     * DELETE /time_tracking_policies/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'time_tracking_policies.destroy');
    }

    /**
     * Archives a time tracking policy.
     *
     * PATCH /time_tracking_policies/{id}/archive
     */
    public function archive(int|string $id): TimeTrackingPolicy
    {
        return $this->write(TimeTrackingPolicy::class, Method::Patch, $this->path($id, 'archive'), 'time_tracking_policies.archive', null);
    }

    /**
     * Restores an archived time tracking policy.
     *
     * PATCH /time_tracking_policies/{id}/restore
     */
    public function restore(int|string $id): TimeTrackingPolicy
    {
        return $this->write(TimeTrackingPolicy::class, Method::Patch, $this->path($id, 'restore'), 'time_tracking_policies.restore', null);
    }
}
