<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources;

use Axyr\Productive\Data\Input\CreateTodoData;
use Axyr\Productive\Data\Input\UpdateTodoData;
use Axyr\Productive\Data\Models\Todo;
use Axyr\Productive\Http\Method;
use Axyr\Productive\Query\Query;

/**
 * Checklist item on a task or deal. Supports description, assignee, due date (with optional time), position ordering, and completion tracking via closed_at timestamp.
 *
 * @see https://developer.productive.io/reference/resources/todos
 */
final class TodoResource extends Resource
{
    protected const string TYPE = 'todos';

    protected const string PATH = 'todos';

    /**
     * Get todos.
     *
     * GET /todos
     *
     * @return PendingQuery<Todo>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(Todo::class, 'todos.index');
    }

    /**
     * Gets a todo.
     *
     * GET /todos/{id}
     *
     * @param  list<string>  $include
     */
    public function find(int|string $id, array $include = []): Todo
    {
        return $this->fetchOne(Todo::class, $this->path($id), 'todos.show', (new Query())->include(...$include));
    }

    /**
     * Create a todo.
     *
     * POST /todos
     *
     * @param  CreateTodoData|array<string, mixed>  $data
     */
    public function create(CreateTodoData|array $data): Todo
    {
        return $this->write(Todo::class, Method::Post, $this->path(), 'todos.create', $data);
    }

    /**
     * Update a todo.
     *
     * PATCH /todos/{id}
     *
     * @param  UpdateTodoData|array<string, mixed>  $data
     */
    public function update(int|string $id, UpdateTodoData|array $data): Todo
    {
        return $this->write(Todo::class, Method::Patch, $this->path($id), 'todos.update', $data, (string) $id);
    }

    /**
     * Deletes a todo.
     *
     * DELETE /todos/{id}
     */
    public function delete(int|string $id): void
    {
        $this->writeWithoutResponse(Method::Delete, $this->path($id), 'todos.destroy');
    }
}
