<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the attachments list.
 */
enum AttachmentSort: string
{
    case Id = 'id';
    case IdDesc = '-id';
}
