<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Grouping dimensions for the automation report.
 */
enum AutomationReportGroup: string
{
    case Automation = 'automation';
    case CreatedAt = 'created_at';
    case Creator = 'creator';
    case Enabled = 'enabled';
    case Organization = 'organization';
    case Project = 'project';
    case Target = 'target';
    case Type = 'type';
    case UpdatedAt = 'updated_at';
}
