<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the automation reports list.
 */
enum AutomationReportSort: string
{
    case AutomationCreatedAt = 'automation_created_at';
    case AutomationCreatedAtDesc = '-automation_created_at';
    case AutomationUpdatedAt = 'automation_updated_at';
    case AutomationUpdatedAtDesc = '-automation_updated_at';
    case Count = 'count';
    case CountDesc = '-count';
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case Creator = 'creator';
    case CreatorDesc = '-creator';
    case Description = 'description';
    case DescriptionDesc = '-description';
    case Enabled = 'enabled';
    case EnabledDesc = '-enabled';
    case Name = 'name';
    case NameDesc = '-name';
    case Project = 'project';
    case ProjectDesc = '-project';
    case TargetId = 'target_id';
    case TargetIdDesc = '-target_id';
    case TypeId = 'type_id';
    case TypeIdDesc = '-type_id';
    case UpdatedAt = 'updated_at';
    case UpdatedAtDesc = '-updated_at';
}
