<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Grouping dimensions for the deal report.
 */
enum DealReportGroup: string
{
    case Company = 'company';
    case Contact = 'contact';
    case CreatedAt = 'created_at';
    case Creator = 'creator';
    case CustomFields = 'custom_fields';
    case Date = 'date';
    case Deal = 'deal';
    case DealStatus = 'deal_status';
    case DealValueSource = 'deal_value_source';
    case DesignatedApprover = 'designated_approver';
    case LastActivityAt = 'last_activity_at';
    case LostReason = 'lost_reason';
    case Month = 'month';
    case Organization = 'organization';
    case Pipeline = 'pipeline';
    case PreviousDealStatus = 'previous_deal_status';
    case PrimaryContact = 'primary_contact';
    case Project = 'project';
    case Quarter = 'quarter';
    case Responsible = 'responsible';
    case RevenueDistributionBase = 'revenue_distribution_base';
    case RevenueDistributionEndOn = 'revenue_distribution_end_on';
    case RevenueDistributionStartOn = 'revenue_distribution_start_on';
    case SalesClosedAt = 'sales_closed_at';
    case SalesClosedOn = 'sales_closed_on';
    case SalesStatusId = 'sales_status_id';
    case StageStatusId = 'stage_status_id';
    case StageUpdatedAt = 'stage_updated_at';
    case Subsidiary = 'subsidiary';
    case TrackingTypeId = 'tracking_type_id';
    case Week = 'week';
    case Year = 'year';
}
