<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the deleted items list.
 */
enum DeletedItemSort: string
{
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case Location = 'location';
    case LocationDesc = '-location';
    case Name = 'name';
    case NameDesc = '-name';
}
