<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the expense reports list.
 */
enum ExpenseReportSort: string
{
    case ApprovalStatus = 'approval_status';
    case ApprovalStatusDesc = '-approval_status';
    case ApprovedAt = 'approved_at';
    case ApprovedAtDesc = '-approved_at';
    case Approver = 'approver';
    case ApproverDesc = '-approver';
    case AverageProfitMargin = 'average_profit_margin';
    case AverageProfitMarginDesc = '-average_profit_margin';
    case Company = 'company';
    case CompanyDesc = '-company';
    case Count = 'count';
    case CountDesc = '-count';
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case Creator = 'creator';
    case CreatorDesc = '-creator';
    case CustomFields = 'custom_fields';
    case CustomFieldsDesc = '-custom_fields';
    case Date = 'date';
    case DateDesc = '-date';
    case Deal = 'deal';
    case DealDesc = '-deal';
    case DesignatedApprover = 'designated_approver';
    case DesignatedApproverDesc = '-designated_approver';
    case Expense = 'expense';
    case ExpenseDesc = '-expense';
    case ExpenseCreatedAt = 'expense_created_at';
    case ExpenseCreatedAtDesc = '-expense_created_at';
    case ExpenseDate = 'expense_date';
    case ExpenseDateDesc = '-expense_date';
    case ExpenseName = 'expense_name';
    case ExpenseNameDesc = '-expense_name';
    case ExpensePaidOn = 'expense_paid_on';
    case ExpensePaidOnDesc = '-expense_paid_on';
    case ExpensePayOn = 'expense_pay_on';
    case ExpensePayOnDesc = '-expense_pay_on';
    case ExpenseReimbursedOn = 'expense_reimbursed_on';
    case ExpenseReimbursedOnDesc = '-expense_reimbursed_on';
    case Invoiced = 'invoiced';
    case InvoicedDesc = '-invoiced';
    case InvoicingStatus = 'invoicing_status';
    case InvoicingStatusDesc = '-invoicing_status';
    case Month = 'month';
    case MonthDesc = '-month';
    case Name = 'name';
    case NameDesc = '-name';
    case PaidOn = 'paid_on';
    case PaidOnDesc = '-paid_on';
    case PayOn = 'pay_on';
    case PayOnDesc = '-pay_on';
    case Person = 'person';
    case PersonDesc = '-person';
    case Project = 'project';
    case ProjectDesc = '-project';
    case ProjectId = 'project_id';
    case ProjectIdDesc = '-project_id';
    case PurchaseOrder = 'purchase_order';
    case PurchaseOrderDesc = '-purchase_order';
    case Quantity = 'quantity';
    case QuantityDesc = '-quantity';
    case Quarter = 'quarter';
    case QuarterDesc = '-quarter';
    case QuoteType = 'quote_type';
    case QuoteTypeDesc = '-quote_type';
    case ReimbursedOn = 'reimbursed_on';
    case ReimbursedOnDesc = '-reimbursed_on';
    case Reimbursement = 'reimbursement';
    case ReimbursementDesc = '-reimbursement';
    case Responsible = 'responsible';
    case ResponsibleDesc = '-responsible';
    case SectionName = 'section_name';
    case SectionNameDesc = '-section_name';
    case Service = 'service';
    case ServiceDesc = '-service';
    case ServiceType = 'service_type';
    case ServiceTypeDesc = '-service_type';
    case StageType = 'stage_type';
    case StageTypeDesc = '-stage_type';
    case Status = 'status';
    case StatusDesc = '-status';
    case TaxRateId = 'tax_rate_id';
    case TaxRateIdDesc = '-tax_rate_id';
    case TotalAmount = 'total_amount';
    case TotalAmountDesc = '-total_amount';
    case TotalAmountWithTax = 'total_amount_with_tax';
    case TotalAmountWithTaxDesc = '-total_amount_with_tax';
    case TotalBillableAmount = 'total_billable_amount';
    case TotalBillableAmountDesc = '-total_billable_amount';
    case TotalProfit = 'total_profit';
    case TotalProfitDesc = '-total_profit';
    case TotalRecognizedRevenue = 'total_recognized_revenue';
    case TotalRecognizedRevenueDesc = '-total_recognized_revenue';
    case TotalTaxAmount = 'total_tax_amount';
    case TotalTaxAmountDesc = '-total_tax_amount';
    case UpdatedAt = 'updated_at';
    case UpdatedAtDesc = '-updated_at';
    case Updater = 'updater';
    case UpdaterDesc = '-updater';
    case Vendor = 'vendor';
    case VendorDesc = '-vendor';
    case Week = 'week';
    case WeekDesc = '-week';
    case Year = 'year';
    case YearDesc = '-year';
}
