<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the invoice reports list.
 */
enum InvoiceReportSort: string
{
    case AutomaticallyCreated = 'automatically_created';
    case AutomaticallyCreatedDesc = '-automatically_created';
    case AverageDueIn = 'average_due_in';
    case AverageDueInDesc = '-average_due_in';
    case AveragePaidIn = 'average_paid_in';
    case AveragePaidInDesc = '-average_paid_in';
    case Budget = 'budget';
    case BudgetDesc = '-budget';
    case Company = 'company';
    case CompanyDesc = '-company';
    case CompanyBillingName = 'company_billing_name';
    case CompanyBillingNameDesc = '-company_billing_name';
    case Count = 'count';
    case CountDesc = '-count';
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case Creator = 'creator';
    case CreatorDesc = '-creator';
    case Currency = 'currency';
    case CurrencyDesc = '-currency';
    case CustomFields = 'custom_fields';
    case CustomFieldsDesc = '-custom_fields';
    case DeliveryOn = 'delivery_on';
    case DeliveryOnDesc = '-delivery_on';
    case EinvoiceStatus = 'einvoice_status';
    case EinvoiceStatusDesc = '-einvoice_status';
    case FiscalizationStatus = 'fiscalization_status';
    case FiscalizationStatusDesc = '-fiscalization_status';
    case Invoice = 'invoice';
    case InvoiceDesc = '-invoice';
    case InvoiceAging = 'invoice_aging';
    case InvoiceAgingDesc = '-invoice_aging';
    case InvoiceCreatedAt = 'invoice_created_at';
    case InvoiceCreatedAtDesc = '-invoice_created_at';
    case InvoiceCustomFields = 'invoice_custom_fields';
    case InvoiceCustomFieldsDesc = '-invoice_custom_fields';
    case InvoiceDeliveryOn = 'invoice_delivery_on';
    case InvoiceDeliveryOnDesc = '-invoice_delivery_on';
    case InvoiceDiscount = 'invoice_discount';
    case InvoiceDiscountDesc = '-invoice_discount';
    case InvoiceInvoicedOn = 'invoice_invoiced_on';
    case InvoiceInvoicedOnDesc = '-invoice_invoiced_on';
    case InvoiceLastActivityAt = 'invoice_last_activity_at';
    case InvoiceLastActivityAtDesc = '-invoice_last_activity_at';
    case InvoiceNumber = 'invoice_number';
    case InvoiceNumberDesc = '-invoice_number';
    case InvoicePaidOn = 'invoice_paid_on';
    case InvoicePaidOnDesc = '-invoice_paid_on';
    case InvoicePayOn = 'invoice_pay_on';
    case InvoicePayOnDesc = '-invoice_pay_on';
    case InvoicePurchaseOrderNumber = 'invoice_purchase_order_number';
    case InvoicePurchaseOrderNumberDesc = '-invoice_purchase_order_number';
    case InvoiceSentOn = 'invoice_sent_on';
    case InvoiceSentOnDesc = '-invoice_sent_on';
    case InvoiceState = 'invoice_state';
    case InvoiceStateDesc = '-invoice_state';
    case InvoiceStatus = 'invoice_status';
    case InvoiceStatusDesc = '-invoice_status';
    case InvoiceSubject = 'invoice_subject';
    case InvoiceSubjectDesc = '-invoice_subject';
    case InvoiceType = 'invoice_type';
    case InvoiceTypeDesc = '-invoice_type';
    case InvoicedOn = 'invoiced_on';
    case InvoicedOnDesc = '-invoiced_on';
    case Issuer = 'issuer';
    case IssuerDesc = '-issuer';
    case LastActivityAt = 'last_activity_at';
    case LastActivityAtDesc = '-last_activity_at';
    case Month = 'month';
    case MonthDesc = '-month';
    case OverdueStatus = 'overdue_status';
    case OverdueStatusDesc = '-overdue_status';
    case PaidOn = 'paid_on';
    case PaidOnDesc = '-paid_on';
    case PayOn = 'pay_on';
    case PayOnDesc = '-pay_on';
    case PaymentStatus = 'payment_status';
    case PaymentStatusDesc = '-payment_status';
    case Project = 'project';
    case ProjectDesc = '-project';
    case Quarter = 'quarter';
    case QuarterDesc = '-quarter';
    case SentOn = 'sent_on';
    case SentOnDesc = '-sent_on';
    case SentStatus = 'sent_status';
    case SentStatusDesc = '-sent_status';
    case Subsidiary = 'subsidiary';
    case SubsidiaryDesc = '-subsidiary';
    case TaxRates = 'tax_rates';
    case TaxRatesDesc = '-tax_rates';
    case TotalAmount = 'total_amount';
    case TotalAmountDesc = '-total_amount';
    case TotalAmountCredited = 'total_amount_credited';
    case TotalAmountCreditedDesc = '-total_amount_credited';
    case TotalAmountCreditedWithTax = 'total_amount_credited_with_tax';
    case TotalAmountCreditedWithTaxDesc = '-total_amount_credited_with_tax';
    case TotalAmountPaid = 'total_amount_paid';
    case TotalAmountPaidDesc = '-total_amount_paid';
    case TotalAmountTax = 'total_amount_tax';
    case TotalAmountTaxDesc = '-total_amount_tax';
    case TotalAmountUnpaid = 'total_amount_unpaid';
    case TotalAmountUnpaidDesc = '-total_amount_unpaid';
    case TotalAmountWithTax = 'total_amount_with_tax';
    case TotalAmountWithTaxDesc = '-total_amount_with_tax';
    case TotalAmountWrittenOff = 'total_amount_written_off';
    case TotalAmountWrittenOffDesc = '-total_amount_written_off';
    case Week = 'week';
    case WeekDesc = '-week';
    case Year = 'year';
    case YearDesc = '-year';
}
