<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Grouping dimensions for the invoice report.
 */
enum InvoiceReportGroup: string
{
    case Company = 'company';
    case CreatedAt = 'created_at';
    case Creator = 'creator';
    case Currency = 'currency';
    case CustomFields = 'custom_fields';
    case DeliveryOn = 'delivery_on';
    case EinvoiceStatus = 'einvoice_status';
    case FiscalizationStatus = 'fiscalization_status';
    case Invoice = 'invoice';
    case InvoiceAging = 'invoice_aging';
    case InvoiceState = 'invoice_state';
    case InvoiceStatus = 'invoice_status';
    case InvoiceType = 'invoice_type';
    case InvoicedOn = 'invoiced_on';
    case Issuer = 'issuer';
    case LastActivityAt = 'last_activity_at';
    case Month = 'month';
    case Organization = 'organization';
    case OverdueStatus = 'overdue_status';
    case PaidOn = 'paid_on';
    case PayOn = 'pay_on';
    case PaymentStatus = 'payment_status';
    case Quarter = 'quarter';
    case SentOn = 'sent_on';
    case SentStatus = 'sent_status';
    case Subsidiary = 'subsidiary';
    case Week = 'week';
    case Year = 'year';
}
