<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the page reports list.
 */
enum PageReportSort: string
{
    case Count = 'count';
    case CountDesc = '-count';
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case Creator = 'creator';
    case CreatorDesc = '-creator';
    case CustomFields = 'custom_fields';
    case CustomFieldsDesc = '-custom_fields';
    case EditedAt = 'edited_at';
    case EditedAtDesc = '-edited_at';
    case Page = 'page';
    case PageDesc = '-page';
    case PageId = 'page_id';
    case PageIdDesc = '-page_id';
    case PageLastActivityAt = 'page_last_activity_at';
    case PageLastActivityAtDesc = '-page_last_activity_at';
    case Project = 'project';
    case ProjectDesc = '-project';
    case Title = 'title';
    case TitleDesc = '-title';
    case Updater = 'updater';
    case UpdaterDesc = '-updater';
}
