<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the payroll item reports list.
 */
enum PayrollItemReportSort: string
{
    case CompanyId = 'company_id';
    case CompanyIdDesc = '-company_id';
    case Count = 'count';
    case CountDesc = '-count';
    case CustomFields = 'custom_fields';
    case CustomFieldsDesc = '-custom_fields';
    case Date = 'date';
    case DateDesc = '-date';
    case EndDate = 'end_date';
    case EndDateDesc = '-end_date';
    case PayrollItemId = 'payroll_item_id';
    case PayrollItemIdDesc = '-payroll_item_id';
    case PayrollItemType = 'payroll_item_type';
    case PayrollItemTypeDesc = '-payroll_item_type';
    case Person = 'person';
    case PersonDesc = '-person';
    case PersonStatus = 'person_status';
    case PersonStatusDesc = '-person_status';
    case PersonType = 'person_type';
    case PersonTypeDesc = '-person_type';
    case RoleId = 'role_id';
    case RoleIdDesc = '-role_id';
    case SalaryId = 'salary_id';
    case SalaryIdDesc = '-salary_id';
    case SalaryTypeId = 'salary_type_id';
    case SalaryTypeIdDesc = '-salary_type_id';
    case StartDate = 'start_date';
    case StartDateDesc = '-start_date';
    case SubsidiaryId = 'subsidiary_id';
    case SubsidiaryIdDesc = '-subsidiary_id';
    case TotalAvailability = 'total_availability';
    case TotalAvailabilityDesc = '-total_availability';
    case TotalCapacity = 'total_capacity';
    case TotalCapacityDesc = '-total_capacity';
    case TotalCost = 'total_cost';
    case TotalCostDesc = '-total_cost';
    case TotalScheduledTime = 'total_scheduled_time';
    case TotalScheduledTimeDesc = '-total_scheduled_time';
    case TotalTime = 'total_time';
    case TotalTimeDesc = '-total_time';
    case TotalTimeOffCost = 'total_time_off_cost';
    case TotalTimeOffCostDesc = '-total_time_off_cost';
    case TotalTimeOffTime = 'total_time_off_time';
    case TotalTimeOffTimeDesc = '-total_time_off_time';
}
