<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Grouping dimensions for the person report.
 */
enum PersonReportGroup: string
{
    case ApprovalPolicy = 'approval_policy';
    case Autotracking = 'autotracking';
    case Company = 'company';
    case ContactAddress = 'contact_address';
    case ContactCity = 'contact_city';
    case ContactCountry = 'contact_country';
    case ContactEmail = 'contact_email';
    case ContactPhone = 'contact_phone';
    case ContactState = 'contact_state';
    case ContactWebsite = 'contact_website';
    case ContactZipcode = 'contact_zipcode';
    case CreatedAt = 'created_at';
    case CustomFields = 'custom_fields';
    case CustomRole = 'custom_role';
    case DeactivatedAt = 'deactivated_at';
    case JobRole = 'job_role';
    case JoinedAt = 'joined_at';
    case LastActivityAt = 'last_activity_at';
    case Manager = 'manager';
    case Month = 'month';
    case OffboardingStatus = 'offboarding_status';
    case Organization = 'organization';
    case Person = 'person';
    case Quarter = 'quarter';
    case RoleId = 'role_id';
    case SharedSeat = 'shared_seat';
    case Status = 'status';
    case Subsidiary = 'subsidiary';
    case Type = 'type';
    case Week = 'week';
    case Year = 'year';
}
