<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the people list.
 */
enum PersonSort: string
{
    case Autotracking = 'autotracking';
    case AutotrackingDesc = '-autotracking';
    case CompanyName = 'company_name';
    case CompanyNameDesc = '-company_name';
    case CustomFields = 'custom_fields';
    case CustomFieldsDesc = '-custom_fields';
    case CustomRole = 'custom_role';
    case CustomRoleDesc = '-custom_role';
    case Email = 'email';
    case EmailDesc = '-email';
    case JobRole = 'job_role';
    case JobRoleDesc = '-job_role';
    case JoinedAt = 'joined_at';
    case JoinedAtDesc = '-joined_at';
    case LastSeenAt = 'last_seen_at';
    case LastSeenAtDesc = '-last_seen_at';
    case Manager = 'manager';
    case ManagerDesc = '-manager';
    case Name = 'name';
    case NameDesc = '-name';
    case ResourceRequestMatch = 'resource_request_match';
    case ResourceRequestMatchDesc = '-resource_request_match';
    case RoleId = 'role_id';
    case RoleIdDesc = '-role_id';
    case Schedulable = 'schedulable';
    case SchedulableDesc = '-schedulable';
    case Subsidiary = 'subsidiary';
    case SubsidiaryDesc = '-subsidiary';
    case Title = 'title';
    case TitleDesc = '-title';
    case TwoFactorAuth = 'two_factor_auth';
    case TwoFactorAuthDesc = '-two_factor_auth';
}
