<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the placeholder usages list.
 */
enum PlaceholderUsageSort: string
{
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case Field = 'field';
    case FieldDesc = '-field';
    case Id = 'id';
    case IdDesc = '-id';
    case IntervalDirection = 'interval_direction';
    case IntervalDirectionDesc = '-interval_direction';
    case IntervalEnabled = 'interval_enabled';
    case IntervalEnabledDesc = '-interval_enabled';
    case IntervalUnit = 'interval_unit';
    case IntervalUnitDesc = '-interval_unit';
    case IntervalValue = 'interval_value';
    case IntervalValueDesc = '-interval_value';
    case PlaceholderId = 'placeholder_id';
    case PlaceholderIdDesc = '-placeholder_id';
    case SkipWeekends = 'skip_weekends';
    case SkipWeekendsDesc = '-skip_weekends';
    case TargetId = 'target_id';
    case TargetIdDesc = '-target_id';
    case TargetType = 'target_type';
    case TargetTypeDesc = '-target_type';
    case UpdatedAt = 'updated_at';
    case UpdatedAtDesc = '-updated_at';
}
