<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the prices list.
 */
enum PriceSort: string
{
    case BillingTypeId = 'billing_type_id';
    case BillingTypeIdDesc = '-billing_type_id';
    case BookingTrackingEnabled = 'booking_tracking_enabled';
    case BookingTrackingEnabledDesc = '-booking_tracking_enabled';
    case CustomFields = 'custom_fields';
    case CustomFieldsDesc = '-custom_fields';
    case Description = 'description';
    case DescriptionDesc = '-description';
    case Discount = 'discount';
    case DiscountDesc = '-discount';
    case EstimatedCost = 'estimated_cost';
    case EstimatedCostDesc = '-estimated_cost';
    case ExpenseTrackingEnabled = 'expense_tracking_enabled';
    case ExpenseTrackingEnabledDesc = '-expense_tracking_enabled';
    case Markup = 'markup';
    case MarkupDesc = '-markup';
    case Name = 'name';
    case NameDesc = '-name';
    case Quantity = 'quantity';
    case QuantityDesc = '-quantity';
    case Rate = 'rate';
    case RateDesc = '-rate';
    case ServiceType = 'service_type';
    case ServiceTypeDesc = '-service_type';
    case TimeTrackingEnabled = 'time_tracking_enabled';
    case TimeTrackingEnabledDesc = '-time_tracking_enabled';
    case UnitId = 'unit_id';
    case UnitIdDesc = '-unit_id';
}
