<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the projects list.
 */
enum ProjectSort: string
{
    case CompanyName = 'company_name';
    case CompanyNameDesc = '-company_name';
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case CustomFields = 'custom_fields';
    case CustomFieldsDesc = '-custom_fields';
    case LastActivityAt = 'last_activity_at';
    case LastActivityAtDesc = '-last_activity_at';
    case Name = 'name';
    case NameDesc = '-name';
    case Number = 'number';
    case NumberDesc = '-number';
    case ProjectNumber = 'project_number';
    case ProjectNumberDesc = '-project_number';
}
