<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the resource requests list.
 */
enum ResourceRequestSort: string
{
    case BookingMethodId = 'booking_method_id';
    case BookingMethodIdDesc = '-booking_method_id';
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case Creator = 'creator';
    case CreatorDesc = '-creator';
    case EndedOn = 'ended_on';
    case EndedOnDesc = '-ended_on';
    case Id = 'id';
    case IdDesc = '-id';
    case Percentage = 'percentage';
    case PercentageDesc = '-percentage';
    case ResolvedAt = 'resolved_at';
    case ResolvedAtDesc = '-resolved_at';
    case Resolver = 'resolver';
    case ResolverDesc = '-resolver';
    case Service = 'service';
    case ServiceDesc = '-service';
    case StartedOn = 'started_on';
    case StartedOnDesc = '-started_on';
    case Status = 'status';
    case StatusDesc = '-status';
    case Time = 'time';
    case TimeDesc = '-time';
    case TotalTime = 'total_time';
    case TotalTimeDesc = '-total_time';
}
