<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Grouping dimensions for the service report.
 */
enum ServiceReportGroup: string
{
    case Billable = 'billable';
    case BillingType = 'billing_type';
    case BookingTrackingEnabled = 'booking_tracking_enabled';
    case Budget = 'budget';
    case BudgetCapEnabled = 'budget_cap_enabled';
    case BudgetCustomFields = 'budget_custom_fields';
    case BudgetStatus = 'budget_status';
    case Company = 'company';
    case CustomFields = 'custom_fields';
    case Date = 'date';
    case DealCustomFields = 'deal_custom_fields';
    case DealStatus = 'deal_status';
    case ExpenseTrackingEnabled = 'expense_tracking_enabled';
    case LimitationType = 'limitation_type';
    case Organization = 'organization';
    case OriginDeal = 'origin_deal';
    case Pipeline = 'pipeline';
    case Project = 'project';
    case ProjectType = 'project_type';
    case Recurring = 'recurring';
    case Responsible = 'responsible';
    case SalesStatus = 'sales_status';
    case Section = 'section';
    case SectionName = 'section_name';
    case Service = 'service';
    case ServiceType = 'service_type';
    case StageStatus = 'stage_status';
    case StageType = 'stage_type';
    case Subsidiary = 'subsidiary';
    case TimeTrackingEnabled = 'time_tracking_enabled';
    case Unit = 'unit';
}
