<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the survey fields list.
 */
enum SurveyFieldSort: string
{
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
    case Id = 'id';
    case IdDesc = '-id';
    case Name = 'name';
    case NameDesc = '-name';
    case ProjectId = 'project_id';
    case ProjectIdDesc = '-project_id';
    case SurveyId = 'survey_id';
    case SurveyIdDesc = '-survey_id';
    case UpdatedAt = 'updated_at';
    case UpdatedAtDesc = '-updated_at';
}
