<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the surveys list.
 */
enum SurveySort: string
{
    case Id = 'id';
    case IdDesc = '-id';
    case Title = 'title';
    case TitleDesc = '-title';
}
