<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the tax rates list.
 */
enum TaxRateSort: string
{
    case Name = 'name';
    case NameDesc = '-name';
    case SubsidiaryName = 'subsidiary_name';
    case SubsidiaryNameDesc = '-subsidiary_name';
}
