<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the timesheet reports list.
 */
enum TimesheetReportSort: string
{
    case Count = 'count';
    case CountDesc = '-count';
    case FridayCapacity = 'friday_capacity';
    case FridayCapacityDesc = '-friday_capacity';
    case FridayTime = 'friday_time';
    case FridayTimeDesc = '-friday_time';
    case MondayCapacity = 'monday_capacity';
    case MondayCapacityDesc = '-monday_capacity';
    case MondayTime = 'monday_time';
    case MondayTimeDesc = '-monday_time';
    case Person = 'person';
    case PersonDesc = '-person';
    case SaturdayCapacity = 'saturday_capacity';
    case SaturdayCapacityDesc = '-saturday_capacity';
    case SaturdayTime = 'saturday_time';
    case SaturdayTimeDesc = '-saturday_time';
    case SundayCapacity = 'sunday_capacity';
    case SundayCapacityDesc = '-sunday_capacity';
    case SundayTime = 'sunday_time';
    case SundayTimeDesc = '-sunday_time';
    case ThursdayCapacity = 'thursday_capacity';
    case ThursdayCapacityDesc = '-thursday_capacity';
    case ThursdayTime = 'thursday_time';
    case ThursdayTimeDesc = '-thursday_time';
    case TuesdayCapacity = 'tuesday_capacity';
    case TuesdayCapacityDesc = '-tuesday_capacity';
    case TuesdayTime = 'tuesday_time';
    case TuesdayTimeDesc = '-tuesday_time';
    case WednesdayCapacity = 'wednesday_capacity';
    case WednesdayCapacityDesc = '-wednesday_capacity';
    case WednesdayTime = 'wednesday_time';
    case WednesdayTimeDesc = '-wednesday_time';
    case Week = 'week';
    case WeekDesc = '-week';
    case WeekSubmissionStatus = 'week_submission_status';
    case WeekSubmissionStatusDesc = '-week_submission_status';
}
