<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the time entry versions list.
 */
enum TimeEntryVersionSort: string
{
    case CreatedAt = 'created_at';
    case CreatedAtDesc = '-created_at';
}
