<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Grouping dimensions for the time entry report.
 */
enum TimeEntryReportGroup: string
{
    case ApprovalPolicy = 'approval_policy';
    case Approver = 'approver';
    case Autotracked = 'autotracked';
    case BillingType = 'billing_type';
    case Budget = 'budget';
    case Company = 'company';
    case CreatedAt = 'created_at';
    case Creator = 'creator';
    case CustomFields = 'custom_fields';
    case Date = 'date';
    case Day = 'day';
    case DealSubsidiary = 'deal_subsidiary';
    case DesignatedApprover = 'designated_approver';
    case EndedAt = 'ended_at';
    case IntercompanyHours = 'intercompany_hours';
    case Invoice = 'invoice';
    case Invoiced = 'invoiced';
    case InvoicingStatus = 'invoicing_status';
    case JiraIssueId = 'jira_issue_id';
    case JiraIssueStatus = 'jira_issue_status';
    case JiraIssueSummary = 'jira_issue_summary';
    case LastActivityAt = 'last_activity_at';
    case LastActor = 'last_actor';
    case Month = 'month';
    case Organization = 'organization';
    case Overhead = 'overhead';
    case PeopleCustomFields = 'people_custom_fields';
    case Person = 'person';
    case PersonManager = 'person_manager';
    case PersonSubsidiary = 'person_subsidiary';
    case Project = 'project';
    case ProjectTypeId = 'project_type_id';
    case Quarter = 'quarter';
    case Responsible = 'responsible';
    case SectionName = 'section_name';
    case Service = 'service';
    case ServiceType = 'service_type';
    case StageType = 'stage_type';
    case StartedAt = 'started_at';
    case Status = 'status';
    case Task = 'task';
    case TaskList = 'task_list';
    case TimeEntry = 'time_entry';
    case TrackMethodId = 'track_method_id';
    case UnitId = 'unit_id';
    case Week = 'week';
    case Year = 'year';
}
