<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Enums;

/**
 * Sort options for the workflow statuses list.
 */
enum WorkflowStatusSort: string
{
    case Name = 'name';
    case NameDesc = '-name';
    case Position = 'position';
    case PositionDesc = '-position';
}
