<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * An activity feed entry recording a change event on an entity. Activities track who changed what, when, and how — forming the audit log for tasks, deals, projects, invoices, and other resources.
 *
 * @see https://developer.productive.io/reference/resources/activities
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Activity extends Model
{
    public const string TYPE = 'activities';

    /** ID of the related booking, if applicable. */
    public ?int $bookingId;

    /**
     * The set of field changes made in this activity, formatted as before/after pairs. Sensitive fields are filtered based on viewer permissions.
     *
     * @var list<mixed>|null
     */
    public ?array $changeset;

    /** ID of the related company, if applicable. */
    public ?int $companyId;

    /** When this activity occurred. */
    public ?DateTimeImmutable $createdAt;

    /** ID of the related deal/budget, if applicable. */
    public ?int $dealId;

    /** Whether the related deal is a production budget (in a production pipeline) rather than a sales deal. */
    public ?bool $dealIsBudget;

    /** ID of the related doc discussion, if applicable. */
    public ?int $discussionId;

    /** ID of the related salary record, if applicable. */
    public ?int $engagementId;

    /** The type of change event (e.g. create, update, destroy). */
    public ?string $event;

    /** ID of the related invoice, if applicable. */
    public ?int $invoiceId;

    /** Timestamp if the changed entity has been soft-deleted, null otherwise. */
    public ?DateTimeImmutable $itemDeletedAt;

    /** ID of the entity that was changed. */
    public ?int $itemId;

    /** Human-readable name of the changed entity. */
    public ?string $itemName;

    /** Resource type of the changed entity (e.g. "task", "deal", "invoice"). */
    public ?string $itemType;

    /** Whether this change was triggered by an automation rule rather than a person. */
    public ?bool $madeByAutomation;

    /** ID of the related doc page, if applicable. */
    public ?int $pageId;

    /** Timestamp if the parent entity has been soft-deleted, null otherwise. */
    public ?DateTimeImmutable $parentDeletedAt;

    /** ID of the parent entity (e.g. the project a task belongs to). */
    public ?int $parentId;

    /** Human-readable name of the parent entity. */
    public ?string $parentName;

    /** Resource type of the parent entity. */
    public ?string $parentType;

    /** ID of the related person, if applicable. */
    public ?int $personId;

    /** ID of the related purchase order, if applicable. */
    public ?int $purchaseOrderId;

    /** Timestamp if the root entity has been soft-deleted, null otherwise. */
    public ?DateTimeImmutable $rootDeletedAt;

    /** ID of the root-level entity in the hierarchy. */
    public ?int $rootId;

    /** Human-readable name of the root-level entity. */
    public ?string $rootName;

    /** Resource type of the root-level entity. */
    public ?string $rootType;

    /** ID of the related task, if this activity is about a task or its children. */
    public ?int $taskId;

    protected function hydrate(Attributes $attributes): void
    {
        $this->bookingId = $attributes->int('booking_id');
        $this->changeset = $attributes->list('changeset');
        $this->companyId = $attributes->int('company_id');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->dealId = $attributes->int('deal_id');
        $this->dealIsBudget = $attributes->bool('deal_is_budget');
        $this->discussionId = $attributes->int('discussion_id');
        $this->engagementId = $attributes->int('engagement_id');
        $this->event = $attributes->string('event');
        $this->invoiceId = $attributes->int('invoice_id');
        $this->itemDeletedAt = $attributes->dateTime('item_deleted_at');
        $this->itemId = $attributes->int('item_id');
        $this->itemName = $attributes->string('item_name');
        $this->itemType = $attributes->string('item_type');
        $this->madeByAutomation = $attributes->bool('made_by_automation');
        $this->pageId = $attributes->int('page_id');
        $this->parentDeletedAt = $attributes->dateTime('parent_deleted_at');
        $this->parentId = $attributes->int('parent_id');
        $this->parentName = $attributes->string('parent_name');
        $this->parentType = $attributes->string('parent_type');
        $this->personId = $attributes->int('person_id');
        $this->purchaseOrderId = $attributes->int('purchase_order_id');
        $this->rootDeletedAt = $attributes->dateTime('root_deleted_at');
        $this->rootId = $attributes->int('root_id');
        $this->rootName = $attributes->string('root_name');
        $this->rootType = $attributes->string('root_type');
        $this->taskId = $attributes->int('task_id');
    }

    public function attachment(): ?Attachment
    {
        return $this->belongsTo('attachment', Attachment::class);
    }

    public function comment(): ?Comment
    {
        return $this->belongsTo('comment', Comment::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function email(): ?Email
    {
        return $this->belongsTo('email', Email::class);
    }

    public function organization(): ?Model
    {
        return $this->belongsTo('organization', Model::class);
    }

    public function role(): ?Model
    {
        return $this->belongsTo('role', Model::class);
    }
}
