<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * An approval policy assignment links an approval policy to a specific target (person or budget).
 *
 * @see https://developer.productive.io/reference/resources/approval-policy-assignments
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class ApprovalPolicyAssignment extends Model
{
    public const string TYPE = 'approval_policy_assignments';

    public ?DateTimeImmutable $createdAt;

    /** The type of target this policy is assigned to: 'Person' for absence approvals or 'Quote' for budget approvals. */
    public ?string $targetType;

    protected function hydrate(Attributes $attributes): void
    {
        $this->createdAt = $attributes->dateTime('created_at');
        $this->targetType = $attributes->string('target_type');
    }

    public function approvalPolicy(): ?ApprovalPolicy
    {
        return $this->belongsTo('approval_policy', ApprovalPolicy::class);
    }

    public function deal(): ?Deal
    {
        return $this->belongsTo('deal', Deal::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function person(): ?Person
    {
        return $this->belongsTo('person', Person::class);
    }
}
