<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * Approval policy defining who approves time entries, absences, or expenses. Configures the set of approvers and whether unanimous approval is required. Auto-creates approval_status records for each approver when a submission is made.
 *
 * @see https://developer.productive.io/reference/resources/approval-policies
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class ApprovalPolicy extends Model
{
    public const string TYPE = 'approval_policies';

    /** Timestamp when the approval policy was archived, or null if active. */
    public ?DateTimeImmutable $archivedAt;

    public ?DateTimeImmutable $createdAt;

    /** Indicates whether this is a custom approval policy created for a specific assignment. */
    public ?bool $custom;

    /** Indicates whether this is the default approval policy for its type. */
    public ?bool $default;

    /** The display name of the approval policy. */
    public ?string $name;

    public ?string $policyType;

    /** Numeric identifier for the approval policy type: 1 = absence, 2 = budget, 3 = deal. */
    public ?int $typeId;

    protected function hydrate(Attributes $attributes): void
    {
        $this->archivedAt = $attributes->dateTime('archived_at');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->custom = $attributes->bool('custom');
        $this->default = $attributes->bool('default');
        $this->name = $attributes->string('name');
        $this->policyType = $attributes->string('policy_type');
        $this->typeId = $attributes->int('type_id');
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }
}
