<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * An uploaded file attached to a task, comment, expense, or other entity.
 *
 * @see https://developer.productive.io/reference/resources/attachments
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Attachment extends Model
{
    public const string TYPE = 'attachments';

    /** The type of the parent entity this file is attached to (e.g. comment, expense, task). */
    public ?string $attachableType;

    /** The attachment category type (e.g. file, image, document). */
    public ?string $attachmentType;

    /** The AWS S3 presigned upload policy used for direct file uploads to object storage. */
    public mixed $awsPolicy;

    /** The MIME content type of this file (e.g. image/png, application/pdf). */
    public ?string $contentType;

    /** Timestamp when this attachment was uploaded. */
    public ?DateTimeImmutable $createdAt;

    /** Timestamp when this attachment was soft-deleted. Null if not deleted. */
    public ?DateTimeImmutable $deletedAt;

    /** The external system ID for this attachment, used when synced from an integration. */
    public ?int $externalId;

    public ?int $fileSize;

    /** The email thread message ID this attachment belongs to. */
    public ?int $messageId;

    /** The filename of the uploaded file. */
    public ?string $name;

    /** Whether resized image variants are available for this attachment. */
    public ?bool $resized;

    /** The file size in bytes. */
    public mixed $size;

    /** A temporary pre-signed URL for accessing the file, valid for a limited time. */
    public mixed $tempUrl;

    /** URL of a thumbnail image for previewing this attachment (for image files). */
    public mixed $thumb;

    /** The download URL for this attachment. */
    public mixed $url;

    protected function hydrate(Attributes $attributes): void
    {
        $this->attachableType = $attributes->string('attachable_type');
        $this->attachmentType = $attributes->string('attachment_type');
        $this->awsPolicy = $attributes->mixed('aws_policy');
        $this->contentType = $attributes->string('content_type');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->deletedAt = $attributes->dateTime('deleted_at');
        $this->externalId = $attributes->int('external_id');
        $this->fileSize = $attributes->int('file_size');
        $this->messageId = $attributes->int('message_id');
        $this->name = $attributes->string('name');
        $this->resized = $attributes->bool('resized');
        $this->size = $attributes->mixed('size');
        $this->tempUrl = $attributes->mixed('temp_url');
        $this->thumb = $attributes->mixed('thumb');
        $this->url = $attributes->mixed('url');
    }

    public function bill(): ?Bill
    {
        return $this->belongsTo('bill', Bill::class);
    }

    public function comment(): ?Comment
    {
        return $this->belongsTo('comment', Comment::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function deal(): ?Deal
    {
        return $this->belongsTo('deal', Deal::class);
    }

    public function documentStyle(): ?DocumentStyle
    {
        return $this->belongsTo('document_style', DocumentStyle::class);
    }

    public function documentType(): ?DocumentType
    {
        return $this->belongsTo('document_type', DocumentType::class);
    }

    public function email(): ?Email
    {
        return $this->belongsTo('email', Email::class);
    }

    public function expense(): ?Expense
    {
        return $this->belongsTo('expense', Expense::class);
    }

    public function invoice(): ?Invoice
    {
        return $this->belongsTo('invoice', Invoice::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function page(): ?Page
    {
        return $this->belongsTo('page', Page::class);
    }

    public function purchaseOrder(): ?PurchaseOrder
    {
        return $this->belongsTo('purchase_order', PurchaseOrder::class);
    }

    public function task(): ?Task
    {
        return $this->belongsTo('task', Task::class);
    }
}
