<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * @see https://developer.productive.io/reference/resources/reports
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class AutomationReport extends Model
{
    public const string TYPE = 'automation_reports';

    public ?int $count;

    public ?DateTimeImmutable $createdAt;

    public ?string $description;

    public ?bool $enabled;

    public mixed $formulaFields;

    public ?string $group;

    public ?string $name;

    public ?bool $resolveOnAllProjects;

    public ?int $targetId;

    public ?int $typeId;

    public ?DateTimeImmutable $updatedAt;

    protected function hydrate(Attributes $attributes): void
    {
        $this->count = $attributes->int('count');
        $this->createdAt = $attributes->date('created_at');
        $this->description = $attributes->string('description');
        $this->enabled = $attributes->bool('enabled');
        $this->formulaFields = $attributes->mixed('formula_fields');
        $this->group = $attributes->string('group');
        $this->name = $attributes->string('name');
        $this->resolveOnAllProjects = $attributes->bool('resolve_on_all_projects');
        $this->targetId = $attributes->int('target_id');
        $this->typeId = $attributes->int('type_id');
        $this->updatedAt = $attributes->date('updated_at');
    }

    public function automation(): ?Model
    {
        return $this->belongsTo('automation', Model::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function project(): ?Project
    {
        return $this->belongsTo('project', Project::class);
    }

    /**
     * @return list<Project>
     */
    public function projects(): array
    {
        return $this->hasMany('projects', Project::class);
    }

    public function report(): ?Model
    {
        return $this->belongsTo('report', Model::class);
    }
}
