<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * Receipt record against a purchase order. Tracks the vendor invoice number, date, due date, description, and total amounts received and cost. Links to a deal and has an optional attachment for the vendor invoice document.
 *
 * @see https://developer.productive.io/reference/resources/bills
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Bill extends Model
{
    public const string TYPE = 'bills';

    public ?string $amount;

    /** Timestamp when the bill was created. */
    public ?DateTimeImmutable $createdAt;

    /** The currency of the bill amounts. */
    public ?string $currency;

    /** The currency used for amounts expressed in the organization's default currency. */
    public ?string $currencyDefault;

    /** The currency used for amounts expressed in the normalized (common reporting) currency. */
    public ?string $currencyNormalized;

    /** The date the bill was issued. */
    public ?DateTimeImmutable $date;

    /** Timestamp when the bill was deleted, or null if active. */
    public ?DateTimeImmutable $deletedAt;

    /** The payment due date for this bill. */
    public ?DateTimeImmutable $dueDate;

    /** The vendor's invoice number or reference code for this bill. */
    public ?string $invoiceNumber;

    public ?string $name;

    public ?string $status;

    /** The total cost of goods or services received in this bill, in the bill's currency. */
    public mixed $totalCost;

    /** The total cost of this bill expressed in the organization's default currency. */
    public mixed $totalCostDefault;

    /** The total cost of this bill expressed in the normalized (common reporting) currency. */
    public mixed $totalCostNormalized;

    /** The total amount received or recognized from the vendor in the bill's currency. */
    public mixed $totalReceived;

    /** The total amount received expressed in the organization's default currency. */
    public mixed $totalReceivedDefault;

    /** The total amount received expressed in the normalized (common reporting) currency. */
    public mixed $totalReceivedNormalized;

    protected function hydrate(Attributes $attributes): void
    {
        $this->amount = $attributes->string('amount');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->date = $attributes->date('date');
        $this->deletedAt = $attributes->dateTime('deleted_at');
        $this->dueDate = $attributes->date('due_date');
        $this->invoiceNumber = $attributes->string('invoice_number');
        $this->name = $attributes->string('name');
        $this->status = $attributes->string('status');
        $this->totalCost = $attributes->mixed('total_cost');
        $this->totalCostDefault = $attributes->mixed('total_cost_default');
        $this->totalCostNormalized = $attributes->mixed('total_cost_normalized');
        $this->totalReceived = $attributes->mixed('total_received');
        $this->totalReceivedDefault = $attributes->mixed('total_received_default');
        $this->totalReceivedNormalized = $attributes->mixed('total_received_normalized');
    }

    public function attachment(): ?Attachment
    {
        return $this->belongsTo('attachment', Attachment::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function deal(): ?Deal
    {
        return $this->belongsTo('deal', Deal::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function purchaseOrder(): ?PurchaseOrder
    {
        return $this->belongsTo('purchase_order', PurchaseOrder::class);
    }
}
