<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A message in the activity feed of a task, deal, company, or other entity. Comments support rich text, @mentions, and file attachments.
 *
 * @see https://developer.productive.io/reference/resources/comments
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Comment extends Model
{
    public const string TYPE = 'comments';

    /** The HTML body of the comment including rich text formatting and @mention markup. */
    public ?string $body;

    public ?int $commentableId;

    /** The type of the parent entity this comment is posted on (e.g. task, deal, company). */
    public ?string $commentableType;

    /** Timestamp when this comment was created. */
    public ?DateTimeImmutable $createdAt;

    /** Timestamp when this comment was soft-deleted. Null if not deleted. */
    public ?DateTimeImmutable $deletedAt;

    /** Whether this comment is a draft (not yet published and not visible to others). */
    public ?bool $draft;

    /** Timestamp when this comment was last edited. */
    public ?DateTimeImmutable $editedAt;

    /** Whether this comment is hidden from the activity feed (moderated or removed). */
    public ?bool $hidden;

    public ?string $note;

    /** Timestamp when this comment was pinned, or null if not pinned. */
    public ?DateTimeImmutable $pinnedAt;

    /**
     * Emoji reactions on this comment, keyed by emoji with people and timestamps.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $reactions;

    /** Timestamp when this comment was last updated. */
    public ?DateTimeImmutable $updatedAt;

    /** The version number of this comment, incremented on each edit. */
    public ?int $versionNumber;

    protected function hydrate(Attributes $attributes): void
    {
        $this->body = $attributes->string('body');
        $this->commentableId = $attributes->int('commentable_id');
        $this->commentableType = $attributes->string('commentable_type');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->deletedAt = $attributes->dateTime('deleted_at');
        $this->draft = $attributes->bool('draft');
        $this->editedAt = $attributes->dateTime('edited_at');
        $this->hidden = $attributes->bool('hidden');
        $this->note = $attributes->string('note');
        $this->pinnedAt = $attributes->dateTime('pinned_at');
        $this->reactions = $attributes->object('reactions');
        $this->updatedAt = $attributes->dateTime('updated_at');
        $this->versionNumber = $attributes->int('version_number');
    }

    /**
     * @return list<Attachment>
     */
    public function attachments(): array
    {
        return $this->hasMany('attachments', Attachment::class);
    }

    public function company(): ?Company
    {
        return $this->belongsTo('company', Company::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function deal(): ?Deal
    {
        return $this->belongsTo('deal', Deal::class);
    }

    public function discussion(): ?Discussion
    {
        return $this->belongsTo('discussion', Discussion::class);
    }

    public function invoice(): ?Invoice
    {
        return $this->belongsTo('invoice', Invoice::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function person(): ?Person
    {
        return $this->belongsTo('person', Person::class);
    }

    public function pinnedBy(): ?Person
    {
        return $this->belongsTo('pinned_by', Person::class);
    }

    public function project(): ?Project
    {
        return $this->belongsTo('project', Project::class);
    }

    public function purchaseOrder(): ?PurchaseOrder
    {
        return $this->belongsTo('purchase_order', PurchaseOrder::class);
    }

    public function task(): ?Task
    {
        return $this->belongsTo('task', Task::class);
    }
}
