<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A recurring retainer contract that auto-generates budgets at set intervals with optional rollover of unused amounts.
 *
 * @see https://developer.productive.io/reference/resources/contracts
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Contract extends Model
{
    public const string TYPE = 'contracts';

    /** Whether to copy expenses from the template. */
    public ?bool $copyExpenses;

    /** Whether to copy the purchase order number. */
    public ?bool $copyPurchaseOrderNumber;

    public ?DateTimeImmutable $createdAt;

    public ?string $endDate;

    /** Date when this contract ends, or null if it has no end date. */
    public ?DateTimeImmutable $endsOn;

    /** ID of the recurrence interval of this contract (alias for contract_interval_id). */
    public ?int $intervalId;

    public ?string $name;

    /** The date of the next occurrence. */
    public ?DateTimeImmutable $nextOccurrenceOn;

    public ?string $startDate;

    /** Date when this contract starts. */
    public ?DateTimeImmutable $startsOn;

    public ?string $status;

    /** Whether to roll over unused hours. */
    public ?bool $useRolloverHours;

    protected function hydrate(Attributes $attributes): void
    {
        $this->copyExpenses = $attributes->bool('copy_expenses');
        $this->copyPurchaseOrderNumber = $attributes->bool('copy_purchase_order_number');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->endDate = $attributes->string('end_date');
        $this->endsOn = $attributes->date('ends_on');
        $this->intervalId = $attributes->int('interval_id');
        $this->name = $attributes->string('name');
        $this->nextOccurrenceOn = $attributes->date('next_occurrence_on');
        $this->startDate = $attributes->string('start_date');
        $this->startsOn = $attributes->date('starts_on');
        $this->status = $attributes->string('status');
        $this->useRolloverHours = $attributes->bool('use_rollover_hours');
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function template(): ?Template
    {
        return $this->belongsTo('template', Template::class);
    }
}
