<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * The resource custom field section.
 *
 * @see https://developer.productive.io/reference/resources/custom-field-sections
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class CustomFieldSection extends Model
{
    public const string TYPE = 'custom_field_sections';

    public ?string $itemType;

    /** The display name of this custom field section. */
    public ?string $name;

    /** The display order position of this section among custom field sections. */
    public ?int $position;

    protected function hydrate(Attributes $attributes): void
    {
        $this->itemType = $attributes->string('item_type');
        $this->name = $attributes->string('name');
        $this->position = $attributes->int('position');
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }
}
