<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A configurable dashboard with widgets displaying KPIs, charts, and project summaries.
 *
 * @see https://developer.productive.io/reference/resources/dashboards
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Dashboard extends Model
{
    public const string TYPE = 'dashboards';

    /** Timestamp when the dashboard was created. */
    public ?DateTimeImmutable $createdAt;

    /** When true, this dashboard is private and only visible to the creator. */
    public ?bool $isPrivate;

    /** The display name of the dashboard. */
    public ?string $name;

    public ?bool $shared;

    /** Timestamp when this dashboard was last updated. */
    public ?DateTimeImmutable $updatedAt;

    protected function hydrate(Attributes $attributes): void
    {
        $this->createdAt = $attributes->dateTime('created_at');
        $this->isPrivate = $attributes->bool('is_private');
        $this->name = $attributes->string('name');
        $this->shared = $attributes->bool('shared');
        $this->updatedAt = $attributes->dateTime('updated_at');
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function organization(): ?Model
    {
        return $this->belongsTo('organization', Model::class);
    }

    public function project(): ?Project
    {
        return $this->belongsTo('project', Project::class);
    }
}
