<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * An aggregated deal funnel report showing pipeline conversion rates, stage progression, and win/loss analysis. Each row represents deals grouped by pipeline stage (deal status), with counts of active and lost deals and total financial values. Used to visualize funnel drop-off and conversion across the sales pipeline.
 *
 * @see https://developer.productive.io/reference/resources/reports
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class DealFunnelReport extends Model
{
    public const string TYPE = 'deal_funnel_reports';

    /** Number of deals grouped into this report row. */
    public ?int $count;

    /** Currency code for this report row, reflecting the budget currency. */
    public ?string $currency;

    /** Currency code for totals expressed in the organization's default currency. */
    public ?string $currencyDefault;

    /** Currency code for totals expressed in the organization's normalized (common) currency. */
    public ?string $currencyNormalized;

    public ?int $dealCount;

    /** Formula fields — key-value hash of custom formula results for this report row. */
    public mixed $formulaFields;

    /** Dimension value used to group this report row (e.g. pipeline stage name or deal status label). */
    public ?string $group;

    /** Number of deals in this funnel stage that were marked as lost. */
    public ?int $lostCount;

    public ?int $pipelineId;

    public ?string $stage;

    /** Sum of total budget value for all deals in this funnel stage, in the budget currency. */
    public mixed $totalBudgetTotal;

    /** Sum of total budget value for all deals in this funnel stage, in the organization's default currency. */
    public mixed $totalBudgetTotalDefault;

    /** Sum of total budget value for all deals in this funnel stage, in the normalized common currency. */
    public mixed $totalBudgetTotalNormalized;

    /** Sum of projected revenue for all deals in this funnel stage, in the budget currency. */
    public mixed $totalProjectedRevenue;

    /** Sum of projected revenue for all deals in this funnel stage, in the organization's default currency. */
    public mixed $totalProjectedRevenueDefault;

    /** Sum of projected revenue for all deals in this funnel stage, in the normalized common currency. */
    public mixed $totalProjectedRevenueNormalized;

    public ?string $totalValue;

    protected function hydrate(Attributes $attributes): void
    {
        $this->count = $attributes->int('count');
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->dealCount = $attributes->int('deal_count');
        $this->formulaFields = $attributes->mixed('formula_fields');
        $this->group = $attributes->string('group');
        $this->lostCount = $attributes->int('lost_count');
        $this->pipelineId = $attributes->int('pipeline_id');
        $this->stage = $attributes->string('stage');
        $this->totalBudgetTotal = $attributes->mixed('total_budget_total');
        $this->totalBudgetTotalDefault = $attributes->mixed('total_budget_total_default');
        $this->totalBudgetTotalNormalized = $attributes->mixed('total_budget_total_normalized');
        $this->totalProjectedRevenue = $attributes->mixed('total_projected_revenue');
        $this->totalProjectedRevenueDefault = $attributes->mixed('total_projected_revenue_default');
        $this->totalProjectedRevenueNormalized = $attributes->mixed('total_projected_revenue_normalized');
        $this->totalValue = $attributes->string('total_value');
    }

    public function dealStatus(): ?DealStatus
    {
        return $this->belongsTo('deal_status', DealStatus::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function pipeline(): ?Pipeline
    {
        return $this->belongsTo('pipeline', Pipeline::class);
    }

    public function report(): ?Model
    {
        return $this->belongsTo('report', Model::class);
    }
}
