<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * An aggregated deal report row. Deal reports group deals by configurable dimensions and calculate financial totals, pipeline metrics, and conversion rates.
 *
 * @see https://developer.productive.io/reference/resources/reports
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class DealReport extends Model
{
    public const string TYPE = 'deal_reports';

    /** Average actual billing rate across deals in this report row, in the deal's budget currency. */
    public mixed $averageActualRate;

    /** Average actual billing rate across deals in this report row, in the organization's default currency. */
    public mixed $averageActualRateDefault;

    /** Average actual billing rate across deals in this report row, in the normalized common currency. */
    public mixed $averageActualRateNormalized;

    /** Average number of calendar days deals have spent in their current pipeline stage. */
    public ?int $averageDaysInCurrentStage;

    /** Average number of calendar days from deal creation to closure (or now if still open). */
    public ?int $averageDaysSinceCreated;

    /** Average number of days since the last activity across deals in this report. */
    public ?int $averageDaysSinceLastActivity;

    /** Average billing rate on the deal, in the deal's budget currency. */
    public mixed $averageRate;

    /** Average billing rate on the deal, in the organization's default currency. */
    public mixed $averageRateDefault;

    /** Average billing rate on the deal, in the normalized common currency. */
    public mixed $averageRateNormalized;

    /** The average number of interval units per retainer period across grouped deals. */
    public ?int $averageRetainerIntervalCount;

    public ?int $billableTime;

    public ?string $cost;

    /** Number of deals grouped into this report row. */
    public ?int $count;

    /** Time period grouping for the deal creation date. */
    public mixed $createdAtPeriod;

    /** Currency code of the deal's budget currency. */
    public ?string $currency;

    /** Currency code in the organization's default currency. */
    public ?string $currencyDefault;

    /** Currency code in the normalized common currency. */
    public ?string $currencyNormalized;

    /** Custom field values associated with the deal. */
    public ?string $customFields;

    /** Time period grouping label for the report date dimension. */
    public mixed $datePeriod;

    public ?int $dealId;

    /** Computed values for custom formula fields defined on the report. */
    public mixed $formulaFields;

    /** The grouping dimension for this report row (e.g. the company, pipeline, or person being grouped by). */
    public ?string $group;

    /** Time period grouping for last activity date (e.g. week, month, quarter). */
    public mixed $lastActivityAtPeriod;

    /** Month grouping label for this report row (e.g. March 2026). */
    public ?string $month;

    /** Probability percentage of the deal before the last status change. */
    public ?string $previousProbability;

    /** Likelihood of winning this deal as a percentage (100 for won, 0 for lost by default). */
    public ?string $probability;

    public ?string $profit;

    public ?float $profitMargin;

    /** Quarter grouping label for this report row (e.g. Q1 2026). */
    public ?string $quarter;

    /** When true, deals in this group are retainer deals. */
    public ?int $retainer;

    /** The billing interval for retainer deals in this group. */
    public ?string $retainerInterval;

    public ?string $revenue;

    /** Time period grouping for the sales closed-at timestamp (e.g. week, month, quarter). */
    public mixed $salesClosedAtPeriod;

    /** Time period grouping for the sales closed-on date (e.g. week, month, quarter). */
    public mixed $salesClosedOnPeriod;

    /** ID of the current pipeline stage status. */
    public ?int $stageStatusId;

    /** Time period grouping for the stage updated-at date (e.g. week, month, quarter). */
    public mixed $stageUpdatedAtPeriod;

    /** Sum of billable hours tracked across all deals in this report group. */
    public ?float $totalBillableTime;

    /** The total budget value derived from services for deals in this group, in the deal currency. */
    public mixed $totalBudgetFromServices;

    /** The total budget value derived from services for deals in this group, in the organization's default currency. */
    public mixed $totalBudgetFromServicesDefault;

    /** The total budget value derived from services for deals in this group, normalized to the deal currency. */
    public mixed $totalBudgetFromServicesNormalized;

    /** Sum of total approved budget amounts across all deals in this report group. */
    public mixed $totalBudgetTotal;

    /** Sum of total approved budget amounts in the organization's default currency across all deals in this report group. */
    public mixed $totalBudgetTotalDefault;

    /** Sum of total approved budget amounts in the normalized currency across all deals in this report group. */
    public mixed $totalBudgetTotalNormalized;

    /** Sum of budget used amounts across all deals in this report group. */
    public mixed $totalBudgetUsed;

    /** Sum of budget used amounts in the organization's default currency across all deals in this report group. */
    public mixed $totalBudgetUsedDefault;

    /** Sum of budget used amounts in the normalized currency across all deals in this report group. */
    public mixed $totalBudgetUsedNormalized;

    /** Sum of budgeted (estimated) hours across all deals in this report group. */
    public ?float $totalBudgetedTime;

    /** Sum of total costs across all deals in this report group. */
    public mixed $totalCost;

    /** Sum of total costs in the organization's default currency across all deals in this report group. */
    public mixed $totalCostDefault;

    /** Sum of total costs in the normalized currency across all deals in this report group. */
    public mixed $totalCostNormalized;

    /** Sum of estimated costs across all deals in this report group. */
    public mixed $totalEstimatedCost;

    /** Sum of estimated costs in the organization's default currency across all deals in this report group. */
    public mixed $totalEstimatedCostDefault;

    /** Sum of estimated costs in the normalized currency across all deals in this report group. */
    public mixed $totalEstimatedCostNormalized;

    /** Sum of estimated remaining hours across all deals in this report group. */
    public ?float $totalEstimatedRemainingTime;

    /** Sum of estimated hours across all deals in this report group. */
    public ?float $totalEstimatedTime;

    /** Sum of expense costs across all deals in this report group. */
    public mixed $totalExpense;

    /** Sum of expense costs in the organization's default currency across all deals in this report group. */
    public mixed $totalExpenseDefault;

    /** Sum of expense costs in the normalized currency across all deals in this report group. */
    public mixed $totalExpenseNormalized;

    /** Sum of profit amounts across all deals in this report group. */
    public mixed $totalProfit;

    /** Sum of profit amounts in the organization's default currency across all deals in this report group. */
    public mixed $totalProfitDefault;

    /** Sum of profit amounts in the normalized currency across all deals in this report group. */
    public mixed $totalProfitNormalized;

    /** Sum of projected revenue amounts across all deals in this report group. */
    public mixed $totalProjectedRevenue;

    /** Sum of projected revenue amounts in the organization's default currency across all deals in this report group. */
    public mixed $totalProjectedRevenueDefault;

    /** Sum of projected revenue amounts in the normalized currency across all deals in this report group. */
    public mixed $totalProjectedRevenueNormalized;

    /** Sum of revenue amounts across all deals in this report group. */
    public mixed $totalRevenue;

    /** Sum of revenue amounts in the organization's default currency across all deals in this report group. */
    public mixed $totalRevenueDefault;

    /** Sum of revenue amounts in the normalized currency across all deals in this report group. */
    public mixed $totalRevenueNormalized;

    /** Sum of services revenue across all deals in this report group. */
    public mixed $totalServicesRevenue;

    /** Sum of services revenue in the organization's default currency across all deals in this report group. */
    public mixed $totalServicesRevenueDefault;

    /** Sum of services revenue in the normalized currency across all deals in this report group. */
    public mixed $totalServicesRevenueNormalized;

    public ?string $totalValue;

    /** Sum of labor (work) costs across all deals in this report group. */
    public mixed $totalWorkCost;

    /** Sum of labor (work) costs in the organization's default currency across all deals in this report group. */
    public mixed $totalWorkCostDefault;

    /** Sum of labor (work) costs in the normalized currency across all deals in this report group. */
    public mixed $totalWorkCostNormalized;

    /** Sum of worked (tracked) hours across all deals in this report group. */
    public ?float $totalWorkedTime;

    /** ID of the tracking type for deals in this report group. */
    public ?int $trackingTypeId;

    /** Week grouping for this deal report row (e.g. week, month, quarter). */
    public ?string $week;

    /** Year grouping for this deal report row. */
    public ?string $year;

    protected function hydrate(Attributes $attributes): void
    {
        $this->averageActualRate = $attributes->mixed('average_actual_rate');
        $this->averageActualRateDefault = $attributes->mixed('average_actual_rate_default');
        $this->averageActualRateNormalized = $attributes->mixed('average_actual_rate_normalized');
        $this->averageDaysInCurrentStage = $attributes->int('average_days_in_current_stage');
        $this->averageDaysSinceCreated = $attributes->int('average_days_since_created');
        $this->averageDaysSinceLastActivity = $attributes->int('average_days_since_last_activity');
        $this->averageRate = $attributes->mixed('average_rate');
        $this->averageRateDefault = $attributes->mixed('average_rate_default');
        $this->averageRateNormalized = $attributes->mixed('average_rate_normalized');
        $this->averageRetainerIntervalCount = $attributes->int('average_retainer_interval_count');
        $this->billableTime = $attributes->int('billable_time');
        $this->cost = $attributes->string('cost');
        $this->count = $attributes->int('count');
        $this->createdAtPeriod = $attributes->mixed('created_at_period');
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->customFields = $attributes->string('custom_fields');
        $this->datePeriod = $attributes->mixed('date_period');
        $this->dealId = $attributes->int('deal_id');
        $this->formulaFields = $attributes->mixed('formula_fields');
        $this->group = $attributes->string('group');
        $this->lastActivityAtPeriod = $attributes->mixed('last_activity_at_period');
        $this->month = $attributes->string('month');
        $this->previousProbability = $attributes->string('previous_probability');
        $this->probability = $attributes->string('probability');
        $this->profit = $attributes->string('profit');
        $this->profitMargin = $attributes->float('profit_margin');
        $this->quarter = $attributes->string('quarter');
        $this->retainer = $attributes->int('retainer');
        $this->retainerInterval = $attributes->string('retainer_interval');
        $this->revenue = $attributes->string('revenue');
        $this->salesClosedAtPeriod = $attributes->mixed('sales_closed_at_period');
        $this->salesClosedOnPeriod = $attributes->mixed('sales_closed_on_period');
        $this->stageStatusId = $attributes->int('stage_status_id');
        $this->stageUpdatedAtPeriod = $attributes->mixed('stage_updated_at_period');
        $this->totalBillableTime = $attributes->float('total_billable_time');
        $this->totalBudgetFromServices = $attributes->mixed('total_budget_from_services');
        $this->totalBudgetFromServicesDefault = $attributes->mixed('total_budget_from_services_default');
        $this->totalBudgetFromServicesNormalized = $attributes->mixed('total_budget_from_services_normalized');
        $this->totalBudgetTotal = $attributes->mixed('total_budget_total');
        $this->totalBudgetTotalDefault = $attributes->mixed('total_budget_total_default');
        $this->totalBudgetTotalNormalized = $attributes->mixed('total_budget_total_normalized');
        $this->totalBudgetUsed = $attributes->mixed('total_budget_used');
        $this->totalBudgetUsedDefault = $attributes->mixed('total_budget_used_default');
        $this->totalBudgetUsedNormalized = $attributes->mixed('total_budget_used_normalized');
        $this->totalBudgetedTime = $attributes->float('total_budgeted_time');
        $this->totalCost = $attributes->mixed('total_cost');
        $this->totalCostDefault = $attributes->mixed('total_cost_default');
        $this->totalCostNormalized = $attributes->mixed('total_cost_normalized');
        $this->totalEstimatedCost = $attributes->mixed('total_estimated_cost');
        $this->totalEstimatedCostDefault = $attributes->mixed('total_estimated_cost_default');
        $this->totalEstimatedCostNormalized = $attributes->mixed('total_estimated_cost_normalized');
        $this->totalEstimatedRemainingTime = $attributes->float('total_estimated_remaining_time');
        $this->totalEstimatedTime = $attributes->float('total_estimated_time');
        $this->totalExpense = $attributes->mixed('total_expense');
        $this->totalExpenseDefault = $attributes->mixed('total_expense_default');
        $this->totalExpenseNormalized = $attributes->mixed('total_expense_normalized');
        $this->totalProfit = $attributes->mixed('total_profit');
        $this->totalProfitDefault = $attributes->mixed('total_profit_default');
        $this->totalProfitNormalized = $attributes->mixed('total_profit_normalized');
        $this->totalProjectedRevenue = $attributes->mixed('total_projected_revenue');
        $this->totalProjectedRevenueDefault = $attributes->mixed('total_projected_revenue_default');
        $this->totalProjectedRevenueNormalized = $attributes->mixed('total_projected_revenue_normalized');
        $this->totalRevenue = $attributes->mixed('total_revenue');
        $this->totalRevenueDefault = $attributes->mixed('total_revenue_default');
        $this->totalRevenueNormalized = $attributes->mixed('total_revenue_normalized');
        $this->totalServicesRevenue = $attributes->mixed('total_services_revenue');
        $this->totalServicesRevenueDefault = $attributes->mixed('total_services_revenue_default');
        $this->totalServicesRevenueNormalized = $attributes->mixed('total_services_revenue_normalized');
        $this->totalValue = $attributes->string('total_value');
        $this->totalWorkCost = $attributes->mixed('total_work_cost');
        $this->totalWorkCostDefault = $attributes->mixed('total_work_cost_default');
        $this->totalWorkCostNormalized = $attributes->mixed('total_work_cost_normalized');
        $this->totalWorkedTime = $attributes->float('total_worked_time');
        $this->trackingTypeId = $attributes->int('tracking_type_id');
        $this->week = $attributes->string('week');
        $this->year = $attributes->string('year');
    }

    public function company(): ?Company
    {
        return $this->belongsTo('company', Company::class);
    }

    public function companyReport(): ?CompanyReport
    {
        return $this->belongsTo('company_report', CompanyReport::class);
    }

    public function contact(): ?Model
    {
        return $this->belongsTo('contact', Model::class);
    }

    public function contactReport(): ?Model
    {
        return $this->belongsTo('contact_report', Model::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function creatorReport(): ?Model
    {
        return $this->belongsTo('creator_report', Model::class);
    }

    public function deal(): ?Deal
    {
        return $this->belongsTo('deal', Deal::class);
    }

    public function dealStatus(): ?DealStatus
    {
        return $this->belongsTo('deal_status', DealStatus::class);
    }

    public function designatedApprover(): ?Person
    {
        return $this->belongsTo('designated_approver', Person::class);
    }

    public function lostReason(): ?LostReason
    {
        return $this->belongsTo('lost_reason', LostReason::class);
    }

    public function organization(): ?Model
    {
        return $this->belongsTo('organization', Model::class);
    }

    public function ownerReport(): ?Model
    {
        return $this->belongsTo('owner_report', Model::class);
    }

    public function pipeline(): ?Pipeline
    {
        return $this->belongsTo('pipeline', Pipeline::class);
    }

    public function previousDealStatus(): ?DealStatus
    {
        return $this->belongsTo('previous_deal_status', DealStatus::class);
    }

    public function primaryContact(): ?Model
    {
        return $this->belongsTo('primary_contact', Model::class);
    }

    public function primaryContactReport(): ?Model
    {
        return $this->belongsTo('primary_contact_report', Model::class);
    }

    public function project(): ?Project
    {
        return $this->belongsTo('project', Project::class);
    }

    public function projectReport(): ?ProjectReport
    {
        return $this->belongsTo('project_report', ProjectReport::class);
    }

    public function report(): ?Model
    {
        return $this->belongsTo('report', Model::class);
    }

    public function responsible(): ?Person
    {
        return $this->belongsTo('responsible', Person::class);
    }

    public function subsidiary(): ?Model
    {
        return $this->belongsTo('subsidiary', Model::class);
    }
}
