<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A time-off entitlement for a person showing allocated, used, and pending hours for an absence category.
 *
 * @see https://developer.productive.io/reference/resources/entitlements
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Entitlement extends Model
{
    public const string TYPE = 'entitlements';

    /** Total hours allocated to this person for the absence category in the entitlement period. */
    public ?float $allocated;

    /** The date when this entitlement period ends. After this date, unused hours may expire. */
    public ?DateTimeImmutable $endDate;

    /** Optional note providing additional context for this entitlement allocation. */
    public ?string $note;

    /** Hours pending approval — absence bookings submitted but not yet approved. */
    public ?float $pending;

    /** The date when this entitlement period starts. */
    public ?DateTimeImmutable $startDate;

    /** Hours already used — approved absence bookings that have been taken within the entitlement period. */
    public ?float $used;

    protected function hydrate(Attributes $attributes): void
    {
        $this->allocated = $attributes->float('allocated');
        $this->endDate = $attributes->date('end_date');
        $this->note = $attributes->string('note');
        $this->pending = $attributes->float('pending');
        $this->startDate = $attributes->date('start_date');
        $this->used = $attributes->float('used');
    }

    public function approvalWorkflow(): ?ApprovalWorkflow
    {
        return $this->belongsTo('approval_workflow', ApprovalWorkflow::class);
    }

    public function event(): ?Event
    {
        return $this->belongsTo('event', Event::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function person(): ?Person
    {
        return $this->belongsTo('person', Person::class);
    }
}
