<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * @see https://developer.productive.io/reference/resources/expense-line-items
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class ExpenseLineItem extends Model
{
    public const string TYPE = 'expense_line_items';

    public ?string $currency;

    public ?string $currencyDefault;

    public ?string $currencyNormalized;

    public ?string $name;

    public ?float $quantity;

    public ?int $unitPrice;

    public ?int $unitPriceDefault;

    public ?int $unitPriceNormalized;

    protected function hydrate(Attributes $attributes): void
    {
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->name = $attributes->string('name');
        $this->quantity = $attributes->float('quantity');
        $this->unitPrice = $attributes->int('unit_price');
        $this->unitPriceDefault = $attributes->int('unit_price_default');
        $this->unitPriceNormalized = $attributes->int('unit_price_normalized');
    }

    public function expense(): ?Expense
    {
        return $this->belongsTo('expense', Expense::class);
    }

    public function taxRate(): ?TaxRate
    {
        return $this->belongsTo('tax_rate', TaxRate::class);
    }
}
