<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A saved view configuration containing filters, sorters, column layout, and optional report aggregation settings.
 *
 * @see https://developer.productive.io/reference/resources/filters
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Filter extends Model
{
    public const string TYPE = 'filters';

    /** ID of the chart visualization type used when displaying this filter as a report chart. */
    public ?int $chartTypeId;

    /** A JSON object containing per-column display settings such as width and visibility. */
    public ?string $columnSettings;

    /** An ordered list of column identifiers defining which columns are visible in this filter's list view. */
    public ?string $columns;

    /** Timestamp when this filter was created. */
    public ?DateTimeImmutable $createdAt;

    /** Whether this filter is the default view loaded when navigating to the associated resource list. */
    public mixed $default;

    /** The currency used for exchange rate conversions when this filter displays monetary values. */
    public ?string $exchangeCurrency;

    /**
     * A JSON object defining the date or date range used for currency exchange rate lookups in this filter.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $exchangeDate;

    /** @var array<array-key, mixed>|null */
    public ?array $filterData;

    /** The collection of resources (e.g. tasks, bookings) that this filter applies to. */
    public ?string $filterableCollection;

    /** ID of the specific resource (e.g. a project) this filter is scoped to, or null for organization-wide filters. */
    public ?int $filterableId;

    /** The type of resource this filter is scoped to (e.g. projects), or null for organization-wide filters. */
    public ?string $filterableType;

    /** Custom formula definitions used to compute derived values in report-type filters. */
    public ?string $formulas;

    /** The field identifier used to group results in this filter's view. */
    public ?string $groupBy;

    /** Whether this filter is hidden from the navigation sidebar. */
    public ?bool $hidden;

    public ?string $itemType;

    /** Timestamp when the last pulse notification was sent for this filter. */
    public ?DateTimeImmutable $lastPulseSentAt;

    /** Timestamp when this filter was last viewed by the current user. */
    public ?DateTimeImmutable $lastViewedAt;

    /** ID of the layout mode used to display this filter (e.g. list, board, timeline). */
    public ?int $layoutId;

    /** The display name of this filter. */
    public ?string $name;

    /** The internal numeric ID of this filter, as opposed to the slug-based id field. */
    public ?int $originalId;

    /** A hash of filter criteria (field/value pairs) that define what records this filter matches. */
    public ?string $params;

    /** The identifier of the predefined system filter this was created from, if applicable. */
    public ?string $predefinedId;

    /** Whether this filter is visible to all members of the organization. */
    public ?bool $public;

    /** The number of unread pulse notifications for the current user on this report filter. */
    public mixed $pulseCount;

    /** Indicates whether this saved filter is of report type. */
    public ?bool $report;

    /** ID of the report layout used by this filter. */
    public ?int $reportLayoutId;

    /** A JSON object containing miscellaneous UI settings for this filter, such as collapsed state or display preferences. */
    public ?string $settings;

    /** Whether this filter has been shared with specific people or teams via memberships. */
    public ?bool $shared;

    /** The field identifier used to sort results in this filter's view. */
    public ?string $sortBy;

    /** The field identifier used to pivot or transpose data in report-type filters. */
    public ?string $transposeBy;

    /** ID of the filter type, indicating whether this is a saved view, a report, or a widget. */
    public ?int $typeId;

    /** Timestamp when this filter was last updated. */
    public ?DateTimeImmutable $updatedAt;

    protected function hydrate(Attributes $attributes): void
    {
        $this->chartTypeId = $attributes->int('chart_type_id');
        $this->columnSettings = $attributes->string('column_settings');
        $this->columns = $attributes->string('columns');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->default = $attributes->mixed('default');
        $this->exchangeCurrency = $attributes->string('exchange_currency');
        $this->exchangeDate = $attributes->object('exchange_date');
        $this->filterData = $attributes->object('filter_data');
        $this->filterableCollection = $attributes->string('filterable_collection');
        $this->filterableId = $attributes->int('filterable_id');
        $this->filterableType = $attributes->string('filterable_type');
        $this->formulas = $attributes->string('formulas');
        $this->groupBy = $attributes->string('group_by');
        $this->hidden = $attributes->bool('hidden');
        $this->itemType = $attributes->string('item_type');
        $this->lastPulseSentAt = $attributes->dateTime('last_pulse_sent_at');
        $this->lastViewedAt = $attributes->dateTime('last_viewed_at');
        $this->layoutId = $attributes->int('layout_id');
        $this->name = $attributes->string('name');
        $this->originalId = $attributes->int('original_id');
        $this->params = $attributes->string('params');
        $this->predefinedId = $attributes->string('predefined_id');
        $this->public = $attributes->bool('public');
        $this->pulseCount = $attributes->mixed('pulse_count');
        $this->report = $attributes->bool('report');
        $this->reportLayoutId = $attributes->int('report_layout_id');
        $this->settings = $attributes->string('settings');
        $this->shared = $attributes->bool('shared');
        $this->sortBy = $attributes->string('sort_by');
        $this->transposeBy = $attributes->string('transpose_by');
        $this->typeId = $attributes->int('type_id');
        $this->updatedAt = $attributes->dateTime('updated_at');
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    /**
     * @return list<Membership>
     */
    public function memberships(): array
    {
        return $this->hasMany('memberships', Membership::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function reportCategory(): ?ReportCategory
    {
        return $this->belongsTo('report_category', ReportCategory::class);
    }

    public function templateObject(): ?Model
    {
        return $this->belongsTo('template_object', Model::class);
    }
}
