<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A non-working day within a holiday calendar that affects person availability calculations.
 *
 * @see https://developer.productive.io/reference/resources/holidays
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Holiday extends Model
{
    public const string TYPE = 'holidays';

    /** The date of this holiday. */
    public ?DateTimeImmutable $date;

    /** The name of this holiday (e.g. Christmas Day). */
    public ?string $name;

    protected function hydrate(Attributes $attributes): void
    {
        $this->date = $attributes->date('date');
        $this->name = $attributes->string('name');
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function holidayCalendar(): ?HolidayCalendar
    {
        return $this->belongsTo('holiday_calendar', HolidayCalendar::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }
}
