<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * An invoice template is linked to a specific budget and stores the default settings (document type, bank account, issuer, etc.) used when automatically generating invoice drafts for that budget.
 *
 * @see https://developer.productive.io/reference/resources/invoice-templates
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class InvoiceTemplate extends Model
{
    public const string TYPE = 'invoice_templates';

    /**
     * Custom bank account details (as a JSON object) to display on generated invoices, overriding the default bank account details.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $bankAccountDetails;

    public ?DateTimeImmutable $createdAt;

    /**
     * Custom field values for this invoice template.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $customFields;

    public ?bool $default;

    /**
     * A JSON object containing rules used to determine which services or time entries to include when auto-generating invoice line items.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $invoiceCreationOptions;

    public ?string $name;

    /** The default note text to include on invoices generated from this template. */
    public ?string $note;

    public ?int $paymentTermsDays;

    public ?string $paymentTermsType;

    /** The default subject line used on invoices generated from this template, typically the budget name. */
    public mixed $subject;

    protected function hydrate(Attributes $attributes): void
    {
        $this->bankAccountDetails = $attributes->object('bank_account_details');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->customFields = $attributes->object('custom_fields');
        $this->default = $attributes->bool('default');
        $this->invoiceCreationOptions = $attributes->object('invoice_creation_options');
        $this->name = $attributes->string('name');
        $this->note = $attributes->string('note');
        $this->paymentTermsDays = $attributes->int('payment_terms_days');
        $this->paymentTermsType = $attributes->string('payment_terms_type');
        $this->subject = $attributes->mixed('subject');
    }

    public function bankAccount(): ?BankAccount
    {
        return $this->belongsTo('bank_account', BankAccount::class);
    }

    public function budget(): ?Deal
    {
        return $this->belongsTo('budget', Deal::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function documentType(): ?DocumentType
    {
        return $this->belongsTo('document_type', DocumentType::class);
    }

    public function issuer(): ?Model
    {
        return $this->belongsTo('issuer', Model::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function subsidiary(): ?Subsidiary
    {
        return $this->belongsTo('subsidiary', Subsidiary::class);
    }
}
