<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * An invoice line item with quantity, unit price, description, and tax. Line items can link to budget services or expenses for automatic billing.
 *
 * @see https://developer.productive.io/reference/resources/line-items
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class LineItem extends Model
{
    public const string TYPE = 'line_items';

    /** The total line amount (unit price × quantity, minus discount) in the invoice's currency. */
    public mixed $amount;

    /** The total line amount converted to the organization's default currency. */
    public mixed $amountDefault;

    /** The total line amount converted to the invoice currency. */
    public mixed $amountNormalized;

    /** The tax portion of this line item's amount in the invoice's currency. */
    public mixed $amountTax;

    /** The tax portion of this line item's amount converted to the organization's default currency. */
    public mixed $amountTaxDefault;

    /** The tax portion of this line item's amount converted to the invoice currency. */
    public mixed $amountTaxNormalized;

    /** The total line amount including tax in the invoice's currency. */
    public mixed $amountWithTax;

    /** The amount with tax converted to the organization's default currency. */
    public mixed $amountWithTaxDefault;

    /** The amount with tax converted to the invoice currency. */
    public mixed $amountWithTaxNormalized;

    /** The currency of this line item, inherited from the associated invoice. */
    public ?string $currency;

    /** The organization's default currency for this line item. */
    public ?string $currencyDefault;

    /** The invoice's currency for this line item. */
    public ?string $currencyNormalized;

    /** The discount applied to this line item, expressed as a percentage (0–100). */
    public ?float $discount;

    public ?bool $manualEntry;

    public ?string $name;

    /** The display order of this line item within the invoice. */
    public ?int $position;

    /** The quantity of units for this line item; for percentage billing types, expressed as a percentage value. */
    public ?float $quantity;

    /** The display name of the tax applied to this line item (e.g. VAT). */
    public ?string $taxName;

    public ?string $taxRate;

    /** The computed tax amount for this line item (amount × tax_value). */
    public ?float $taxValue;

    public ?string $totalPrice;

    public ?string $unit;

    /** ID of the unit of measure for this line item (e.g. hour, day, piece). */
    public ?int $unitId;

    /** The price per unit for this line item in the invoice's currency. */
    public ?int $unitPrice;

    /** The price per unit converted to the organization's default currency. */
    public mixed $unitPriceDefault;

    /** The price per unit for this line item in the invoice's currency. */
    public mixed $unitPriceNormalized;

    protected function hydrate(Attributes $attributes): void
    {
        $this->amount = $attributes->mixed('amount');
        $this->amountDefault = $attributes->mixed('amount_default');
        $this->amountNormalized = $attributes->mixed('amount_normalized');
        $this->amountTax = $attributes->mixed('amount_tax');
        $this->amountTaxDefault = $attributes->mixed('amount_tax_default');
        $this->amountTaxNormalized = $attributes->mixed('amount_tax_normalized');
        $this->amountWithTax = $attributes->mixed('amount_with_tax');
        $this->amountWithTaxDefault = $attributes->mixed('amount_with_tax_default');
        $this->amountWithTaxNormalized = $attributes->mixed('amount_with_tax_normalized');
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->discount = $attributes->float('discount');
        $this->manualEntry = $attributes->bool('manual_entry');
        $this->name = $attributes->string('name');
        $this->position = $attributes->int('position');
        $this->quantity = $attributes->float('quantity');
        $this->taxName = $attributes->string('tax_name');
        $this->taxRate = $attributes->string('tax_rate');
        $this->taxValue = $attributes->float('tax_value');
        $this->totalPrice = $attributes->string('total_price');
        $this->unit = $attributes->string('unit');
        $this->unitId = $attributes->int('unit_id');
        $this->unitPrice = $attributes->int('unit_price');
        $this->unitPriceDefault = $attributes->mixed('unit_price_default');
        $this->unitPriceNormalized = $attributes->mixed('unit_price_normalized');
    }

    public function expense(): ?Expense
    {
        return $this->belongsTo('expense', Expense::class);
    }

    public function invoice(): ?Invoice
    {
        return $this->belongsTo('invoice', Invoice::class);
    }

    public function kpdCode(): ?Model
    {
        return $this->belongsTo('kpd_code', Model::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function service(): ?Service
    {
        return $this->belongsTo('service', Service::class);
    }

    public function serviceType(): ?ServiceType
    {
        return $this->belongsTo('service_type', ServiceType::class);
    }

    public function taxRate(): ?TaxRate
    {
        return $this->belongsTo('tax_rate', TaxRate::class);
    }
}
