<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A label explaining why a deal was lost, used for sales pipeline analytics.
 *
 * @see https://developer.productive.io/reference/resources/lost-reasons
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class LostReason extends Model
{
    public const string TYPE = 'lost_reasons';

    /** Timestamp when this lost reason was archived, or null if active. */
    public ?DateTimeImmutable $archivedAt;

    /** Label text displayed on the deal when marked as lost. */
    public ?string $name;

    public ?int $position;

    protected function hydrate(Attributes $attributes): void
    {
        $this->archivedAt = $attributes->dateTime('archived_at');
        $this->name = $attributes->string('name');
        $this->position = $attributes->int('position');
    }

    public function organization(): ?Model
    {
        return $this->belongsTo('organization', Model::class);
    }
}
