<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A rich text document page. Root pages are standalone Docs with sharing settings; child pages form a hierarchy within a Doc.
 *
 * @see https://developer.productive.io/reference/resources/pages
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Page extends Model
{
    public const string TYPE = 'pages';

    public ?DateTimeImmutable $archivedAt;

    /** Rich text body of the page in ProseMirror JSON format. */
    public mixed $body;

    /** Metadata for the cover image, such as dimensions and focal point. */
    public ?string $coverImageMeta;

    /** URL of the cover image displayed at the top of the page. */
    public ?string $coverImageUrl;

    /** Timestamp when the page was created. */
    public ?DateTimeImmutable $createdAt;

    /**
     * Custom field values set on this page. Only available on root pages that belong to a project.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $customFields;

    /** Timestamp when the page content was last edited. */
    public ?DateTimeImmutable $editedAt;

    /** Emoji or icon identifier displayed next to the page title. */
    public ?string $iconId;

    /** Timestamp of the most recent activity on this page. */
    public ?DateTimeImmutable $lastActivityAt;

    public ?string $note;

    /** ID of the parent page in the hierarchy, or null if this is a root page. */
    public ?int $parentPageId;

    /** The display order position of this page among its siblings. */
    public ?int $position;

    /**
     * Page-level display preferences such as layout width, font size and default edit access.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $preferences;

    /** Whether this page is publicly accessible via a shared link. */
    public mixed $public;

    /** Controls whether the page can be viewed publicly without authentication. */
    public ?bool $publicAccess;

    /** UUID used in the public sharing URL for this page. */
    public ?string $publicUuid;

    /** ID of the root Doc page. Null if this page is itself a root Doc. */
    public ?int $rootPageId;

    /** Title of the page. */
    public ?string $title;

    /** Timestamp when the page record was last updated. */
    public ?DateTimeImmutable $updatedAt;

    /** Incremental version counter for the page body, used to detect and prevent conflicting edits. */
    public ?int $versionNumber;

    protected function hydrate(Attributes $attributes): void
    {
        $this->archivedAt = $attributes->dateTime('archived_at');
        $this->body = $attributes->mixed('body');
        $this->coverImageMeta = $attributes->string('cover_image_meta');
        $this->coverImageUrl = $attributes->string('cover_image_url');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->customFields = $attributes->object('custom_fields');
        $this->editedAt = $attributes->dateTime('edited_at');
        $this->iconId = $attributes->string('icon_id');
        $this->lastActivityAt = $attributes->dateTime('last_activity_at');
        $this->note = $attributes->string('note');
        $this->parentPageId = $attributes->int('parent_page_id');
        $this->position = $attributes->int('position');
        $this->preferences = $attributes->object('preferences');
        $this->public = $attributes->mixed('public');
        $this->publicAccess = $attributes->bool('public_access');
        $this->publicUuid = $attributes->string('public_uuid');
        $this->rootPageId = $attributes->int('root_page_id');
        $this->title = $attributes->string('title');
        $this->updatedAt = $attributes->dateTime('updated_at');
        $this->versionNumber = $attributes->int('version_number');
    }

    /**
     * @return list<Attachment>
     */
    public function attachments(): array
    {
        return $this->hasMany('attachments', Attachment::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function parentPage(): ?Page
    {
        return $this->belongsTo('parent_page', Page::class);
    }

    public function project(): ?Project
    {
        return $this->belongsTo('project', Project::class);
    }

    public function rootPage(): ?Page
    {
        return $this->belongsTo('root_page', Page::class);
    }

    public function templateObject(): ?Model
    {
        return $this->belongsTo('template_object', Model::class);
    }

    public function updater(): ?Person
    {
        return $this->belongsTo('updater', Person::class);
    }
}
