<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A password reset or change request, identified by a reset token.
 *
 * @see https://developer.productive.io/reference/resources/passwords
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Password extends Model
{
    public const string TYPE = 'passwords';

    /** The email address associated with the user whose password is being reset or changed. */
    public ?string $email;

    /** When true, the user has not yet set their first password after account creation. */
    public ?bool $firstPassword;

    public ?DateTimeImmutable $updatedAt;

    protected function hydrate(Attributes $attributes): void
    {
        $this->email = $attributes->string('email');
        $this->firstPassword = $attributes->bool('first_password');
        $this->updatedAt = $attributes->dateTime('updated_at');
    }
}
