<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A payment record representing an amount received against an invoice, internally referred to as an InvoicePayment.
 *
 * @see https://developer.productive.io/reference/resources/payments
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Payment extends Model
{
    public const string TYPE = 'payments';

    /** The payment amount in the invoice's currency. */
    public ?int $amount;

    /** The payment amount converted to the organization's default currency. */
    public mixed $amountDefault;

    /** The payment amount converted to the normalized (reporting) currency. */
    public mixed $amountNormalized;

    public ?DateTimeImmutable $createdAt;

    /** The currency of this payment, inherited from the associated invoice. */
    public ?string $currency;

    /** The organization's default currency for this payment. */
    public ?string $currencyDefault;

    /** The normalized (reporting) currency for this payment. */
    public ?string $currencyNormalized;

    /** An external identifier for this payment, used when syncing with third-party accounting systems. */
    public ?string $externalId;

    /** An optional note or memo about this payment. */
    public ?string $note;

    /** Date when the payment was received (paid). */
    public ?DateTimeImmutable $paidOn;

    /** Date when this payment was written off as uncollectable, or null if the payment is not written off. */
    public ?DateTimeImmutable $writtenOffOn;

    protected function hydrate(Attributes $attributes): void
    {
        $this->amount = $attributes->int('amount');
        $this->amountDefault = $attributes->mixed('amount_default');
        $this->amountNormalized = $attributes->mixed('amount_normalized');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->externalId = $attributes->string('external_id');
        $this->note = $attributes->string('note');
        $this->paidOn = $attributes->date('paid_on');
        $this->writtenOffOn = $attributes->date('written_off_on');
    }

    public function invoice(): ?Invoice
    {
        return $this->belongsTo('invoice', Invoice::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }
}
