<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * An aggregated project report row grouping projects by configurable dimensions with utilization, financial, and delivery metrics.
 *
 * @see https://developer.productive.io/reference/resources/reports
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class ProjectReport extends Model
{
    public const string TYPE = 'project_reports';

    /** Average profit margin for this project report group. */
    public ?float $averageProfitMargin;

    /** Average profit margin in the organization's default currency for this project report group. */
    public ?float $averageProfitMarginDefault;

    /** Average profit margin in the normalized currency for this project report group. */
    public mixed $averageProfitMarginNormalized;

    public ?int $billableTime;

    public ?string $budgetTotal;

    public ?string $budgetUsed;

    public ?int $companyId;

    public ?string $cost;

    /** Number of projects in this report group. */
    public ?int $count;

    /** Time period grouping for created at (e.g. week, month, quarter). */
    public mixed $createdAtPeriod;

    /** Currency for this project report group. */
    public ?string $currency;

    /** Currency in the organization's default currency for this project report group. */
    public ?string $currencyDefault;

    /** Currency in the normalized currency for this project report group. */
    public ?string $currencyNormalized;

    /** Custom fields for this project report group. */
    public ?string $customFields;

    /** Formula fields for this project report group. */
    public mixed $formulaFields;

    /** The grouping dimension for this project report row. */
    public ?string $group;

    /** Time period grouping for last activity date (e.g. week, month, quarter). */
    public mixed $lastActivityAtPeriod;

    /** Month grouping for this project report row. */
    public ?string $month;

    public ?int $nonbillableTime;

    public ?string $profit;

    public ?float $profitMargin;

    public ?int $projectId;

    /** Project status for this project report group. */
    public ?int $projectStatus;

    /** Project type for this project report group. */
    public ?int $projectType;

    /** Quarter grouping for this project report row. */
    public ?string $quarter;

    public ?string $revenue;

    /** Sum of cost across all records in this project report group. */
    public mixed $totalCost;

    /** Sum of cost in the organization's default currency across all records in this project report group. */
    public mixed $totalCostDefault;

    /** Sum of cost in the normalized currency across all records in this project report group. */
    public mixed $totalCostNormalized;

    /** Sum of estimated time across all records in this project report group. */
    public ?float $totalEstimatedTime;

    /** Sum of needs invoicing across all records in this project report group. */
    public mixed $totalNeedsInvoicing;

    /** Sum of needs invoicing in the organization's default currency across all records in this project report group. */
    public mixed $totalNeedsInvoicingDefault;

    /** Sum of needs invoicing in the normalized currency across all records in this project report group. */
    public mixed $totalNeedsInvoicingNormalized;

    /** Sum of pending invoicing across all records in this project report group. */
    public mixed $totalPendingInvoicing;

    /** Sum of pending invoicing in the organization's default currency across all records in this project report group. */
    public mixed $totalPendingInvoicingDefault;

    /** Sum of pending invoicing in the normalized currency across all records in this project report group. */
    public mixed $totalPendingInvoicingNormalized;

    /** Sum of profit across all records in this project report group. */
    public mixed $totalProfit;

    /** Sum of profit in the organization's default currency across all records in this project report group. */
    public mixed $totalProfitDefault;

    /** Sum of profit in the normalized currency across all records in this project report group. */
    public mixed $totalProfitNormalized;

    /** Sum of projected revenue across all records in this project report group. */
    public mixed $totalProjectedRevenue;

    /** Sum of projected revenue in the organization's default currency across all records in this project report group. */
    public mixed $totalProjectedRevenueDefault;

    /** Sum of projected revenue in the normalized currency across all records in this project report group. */
    public mixed $totalProjectedRevenueNormalized;

    /** Sum of revenue across all records in this project report group. */
    public mixed $totalRevenue;

    /** Sum of revenue in the organization's default currency across all records in this project report group. */
    public mixed $totalRevenueDefault;

    /** Sum of revenue in the normalized currency across all records in this project report group. */
    public mixed $totalRevenueNormalized;

    public ?int $totalTime;

    /** Sum of worked time across all records in this project report group. */
    public ?float $totalWorkedTime;

    /** Week grouping for this project report row. */
    public ?string $week;

    /** Year grouping for this project report row. */
    public ?string $year;

    protected function hydrate(Attributes $attributes): void
    {
        $this->averageProfitMargin = $attributes->float('average_profit_margin');
        $this->averageProfitMarginDefault = $attributes->float('average_profit_margin_default');
        $this->averageProfitMarginNormalized = $attributes->mixed('average_profit_margin_normalized');
        $this->billableTime = $attributes->int('billable_time');
        $this->budgetTotal = $attributes->string('budget_total');
        $this->budgetUsed = $attributes->string('budget_used');
        $this->companyId = $attributes->int('company_id');
        $this->cost = $attributes->string('cost');
        $this->count = $attributes->int('count');
        $this->createdAtPeriod = $attributes->mixed('created_at_period');
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->customFields = $attributes->string('custom_fields');
        $this->formulaFields = $attributes->mixed('formula_fields');
        $this->group = $attributes->string('group');
        $this->lastActivityAtPeriod = $attributes->mixed('last_activity_at_period');
        $this->month = $attributes->string('month');
        $this->nonbillableTime = $attributes->int('nonbillable_time');
        $this->profit = $attributes->string('profit');
        $this->profitMargin = $attributes->float('profit_margin');
        $this->projectId = $attributes->int('project_id');
        $this->projectStatus = $attributes->int('project_status');
        $this->projectType = $attributes->int('project_type');
        $this->quarter = $attributes->string('quarter');
        $this->revenue = $attributes->string('revenue');
        $this->totalCost = $attributes->mixed('total_cost');
        $this->totalCostDefault = $attributes->mixed('total_cost_default');
        $this->totalCostNormalized = $attributes->mixed('total_cost_normalized');
        $this->totalEstimatedTime = $attributes->float('total_estimated_time');
        $this->totalNeedsInvoicing = $attributes->mixed('total_needs_invoicing');
        $this->totalNeedsInvoicingDefault = $attributes->mixed('total_needs_invoicing_default');
        $this->totalNeedsInvoicingNormalized = $attributes->mixed('total_needs_invoicing_normalized');
        $this->totalPendingInvoicing = $attributes->mixed('total_pending_invoicing');
        $this->totalPendingInvoicingDefault = $attributes->mixed('total_pending_invoicing_default');
        $this->totalPendingInvoicingNormalized = $attributes->mixed('total_pending_invoicing_normalized');
        $this->totalProfit = $attributes->mixed('total_profit');
        $this->totalProfitDefault = $attributes->mixed('total_profit_default');
        $this->totalProfitNormalized = $attributes->mixed('total_profit_normalized');
        $this->totalProjectedRevenue = $attributes->mixed('total_projected_revenue');
        $this->totalProjectedRevenueDefault = $attributes->mixed('total_projected_revenue_default');
        $this->totalProjectedRevenueNormalized = $attributes->mixed('total_projected_revenue_normalized');
        $this->totalRevenue = $attributes->mixed('total_revenue');
        $this->totalRevenueDefault = $attributes->mixed('total_revenue_default');
        $this->totalRevenueNormalized = $attributes->mixed('total_revenue_normalized');
        $this->totalTime = $attributes->int('total_time');
        $this->totalWorkedTime = $attributes->float('total_worked_time');
        $this->week = $attributes->string('week');
        $this->year = $attributes->string('year');
    }

    public function company(): ?Company
    {
        return $this->belongsTo('company', Company::class);
    }

    public function companyReport(): ?CompanyReport
    {
        return $this->belongsTo('company_report', CompanyReport::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function project(): ?Project
    {
        return $this->belongsTo('project', Project::class);
    }

    public function projectManager(): ?Person
    {
        return $this->belongsTo('project_manager', Person::class);
    }

    public function projectManagerReport(): ?Model
    {
        return $this->belongsTo('project_manager_report', Model::class);
    }

    public function report(): ?Model
    {
        return $this->belongsTo('report', Model::class);
    }
}
