<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * A single aggregated row in a proposal report, containing metrics and grouping fields for one or more proposals.
 *
 * @see https://developer.productive.io/reference/resources/reports
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class ProposalReport extends Model
{
    public const string TYPE = 'proposal_reports';

    /** Average tax rate percentage applied across proposals in this report row, computed from the tax rate component values. */
    public ?float $averageTaxRateValue;

    public ?int $companyId;

    /** Number of proposals aggregated into this report row. */
    public ?int $count;

    /** The period label for the proposal creation date when the report is grouped by a creation date interval. */
    public mixed $createdAtPeriod;

    /** Currency code of the proposal amounts in this report row. */
    public ?string $currency;

    /** Budget total amount in the organization's default currency. */
    public ?string $currencyDefault;

    /** Budget total amount normalized to the organization's reporting currency. */
    public ?string $currencyNormalized;

    /** The period label for the date signed when the report is grouped by a signing date interval. */
    public mixed $dateSignedPeriod;

    public ?int $dealId;

    /** Values of any custom formula fields defined for this report. */
    public mixed $formulaFields;

    /** The grouping dimension used to aggregate proposals into this report row (e.g. company, deal, status). */
    public ?string $group;

    /** Public link sharing status of the proposals in this report row. */
    public ?string $linkStatus;

    /** The period label for the sent date when the report is grouped by a sent date interval. */
    public mixed $sentAtPeriod;

    /** Whether the proposals in this report row have been signed by the client. */
    public ?int $signed;

    /** Email address of the person who signed the proposal, populated only when the proposal is signed. */
    public ?string $signedByEmail;

    /** Current lifecycle status of the proposals in this report row (e.g. draft, sent, accepted, declined). */
    public ?string $status;

    /** The period label for the status change date when the report is grouped by a status change date interval. */
    public mixed $statusChangedAtPeriod;

    public ?string $total;

    /** Sum of all proposal budget totals in this report row, in the proposal's original currency. */
    public mixed $totalBudgetTotal;

    /** Sum of all proposal budget totals in this report row, in the organization's default currency. */
    public mixed $totalBudgetTotalDefault;

    /** Sum of all proposal budget totals in this report row, normalized to the organization's reporting currency. */
    public mixed $totalBudgetTotalNormalized;

    /** Sum of calculated tax amounts across all proposals in this report row, in the proposal's original currency. */
    public mixed $totalTaxAmount;

    /** Sum of calculated tax amounts across all proposals in this report row, in the organization's default currency. */
    public mixed $totalTaxAmountDefault;

    /** Sum of calculated tax amounts across all proposals in this report row, normalized to the organization's reporting currency. */
    public mixed $totalTaxAmountNormalized;

    /** The period label for the updated date when the report is grouped by an update date interval. */
    public mixed $updatedAtPeriod;

    protected function hydrate(Attributes $attributes): void
    {
        $this->averageTaxRateValue = $attributes->float('average_tax_rate_value');
        $this->companyId = $attributes->int('company_id');
        $this->count = $attributes->int('count');
        $this->createdAtPeriod = $attributes->mixed('created_at_period');
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->dateSignedPeriod = $attributes->mixed('date_signed_period');
        $this->dealId = $attributes->int('deal_id');
        $this->formulaFields = $attributes->mixed('formula_fields');
        $this->group = $attributes->string('group');
        $this->linkStatus = $attributes->string('link_status');
        $this->sentAtPeriod = $attributes->mixed('sent_at_period');
        $this->signed = $attributes->int('signed');
        $this->signedByEmail = $attributes->string('signed_by_email');
        $this->status = $attributes->string('status');
        $this->statusChangedAtPeriod = $attributes->mixed('status_changed_at_period');
        $this->total = $attributes->string('total');
        $this->totalBudgetTotal = $attributes->mixed('total_budget_total');
        $this->totalBudgetTotalDefault = $attributes->mixed('total_budget_total_default');
        $this->totalBudgetTotalNormalized = $attributes->mixed('total_budget_total_normalized');
        $this->totalTaxAmount = $attributes->mixed('total_tax_amount');
        $this->totalTaxAmountDefault = $attributes->mixed('total_tax_amount_default');
        $this->totalTaxAmountNormalized = $attributes->mixed('total_tax_amount_normalized');
        $this->updatedAtPeriod = $attributes->mixed('updated_at_period');
    }

    public function company(): ?Company
    {
        return $this->belongsTo('company', Company::class);
    }

    public function companyReport(): ?CompanyReport
    {
        return $this->belongsTo('company_report', CompanyReport::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function creatorReport(): ?Model
    {
        return $this->belongsTo('creator_report', Model::class);
    }

    public function deal(): ?Deal
    {
        return $this->belongsTo('deal', Deal::class);
    }

    public function dealReport(): ?DealReport
    {
        return $this->belongsTo('deal_report', DealReport::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function proposal(): ?Proposal
    {
        return $this->belongsTo('proposal', Proposal::class);
    }

    public function report(): ?Model
    {
        return $this->belongsTo('report', Model::class);
    }

    public function responsible(): ?Person
    {
        return $this->belongsTo('responsible', Person::class);
    }

    public function responsibleReport(): ?Model
    {
        return $this->belongsTo('responsible_report', Model::class);
    }

    public function subsidiary(): ?Subsidiary
    {
        return $this->belongsTo('subsidiary', Subsidiary::class);
    }
}
