<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A document sent to a client summarizing proposed work, budget, and terms for a deal.
 *
 * @see https://developer.productive.io/reference/resources/proposals
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Proposal extends Model
{
    public const string TYPE = 'proposals';

    public ?DateTimeImmutable $acceptedAt;

    /** The total budget amount of this proposal in the proposal's currency. */
    public mixed $budgetTotal;

    /** The total budget amount of this proposal in the organization's default currency. */
    public mixed $budgetTotalDefault;

    /** The total budget amount of this proposal in the normalized (reporting) currency. */
    public mixed $budgetTotalNormalized;

    /** Timestamp when this proposal was created. */
    public ?DateTimeImmutable $createdAt;

    /** The currency code used for amounts in this proposal. */
    public ?string $currency;

    /** The organization's default currency code. */
    public ?string $currencyDefault;

    /** The normalized (reporting) currency code used across the organization. */
    public ?string $currencyNormalized;

    /**
     * Custom field values for this proposal.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $customFields;

    /** Date when this proposal was issued. */
    public ?DateTimeImmutable $date;

    public ?DateTimeImmutable $declinedAt;

    /** The optional disclaimer text appended to the proposal. */
    public ?string $disclaimer;

    /** When true, the disclaimer text is shown on the proposal. */
    public ?bool $disclaimerEnabled;

    /** The end date of the proposal's validity or service period. */
    public ?DateTimeImmutable $endDate;

    /** The date used to determine the exchange rate applied to this proposal. */
    public ?DateTimeImmutable $exchangeDate;

    /** The exchange rate used to convert proposal amounts to the billing currency. */
    public ?float $exchangeRate;

    /** The footer text template for the proposal, may contain interpolation variables. */
    public mixed $footer;

    /** The footer text with all interpolation variables resolved. */
    public mixed $footerInterpolated;

    public ?bool $identityConfirmationEnabled;

    public ?DateTimeImmutable $identityConfirmedAt;

    /** The public sharing link status of the proposal (e.g. active, disabled). */
    public ?string $linkStatus;

    /** The display name of the proposal. */
    public ?string $name;

    /** The body text of the proposal note, may contain interpolation variables. */
    public ?string $note;

    /** The proposal note with all interpolation variables resolved. */
    public mixed $noteInterpolated;

    public ?string $number;

    /** The URL of the generated PDF for this proposal. */
    public ?string $pdfUrl;

    /** The unique public UUID used to generate the proposal's public sharing link. */
    public ?string $publicUuid;

    /** The client's purchase order number associated with this proposal. */
    public ?string $purchaseOrderNumber;

    /** The email address of the person who responded to (signed) the proposal. */
    public ?string $responderEmail;

    /** The name of the person who responded to (signed) the proposal. */
    public ?string $responderName;

    /** Timestamp when the proposal was sent to the client. */
    public ?DateTimeImmutable $sentAt;

    /** When true, the proposal has been signed by the client. */
    public mixed $signed;

    /** URL of the audit trail PDF for this proposal, capturing signature and viewing history. */
    public ?string $signedPdfUrl;

    /** The current status of the proposal (e.g. draft, sent, approved, rejected). */
    public ?string $status;

    /** Timestamp when the proposal status last changed. */
    public ?DateTimeImmutable $statusChangedAt;

    public ?string $total;

    protected function hydrate(Attributes $attributes): void
    {
        $this->acceptedAt = $attributes->dateTime('accepted_at');
        $this->budgetTotal = $attributes->mixed('budget_total');
        $this->budgetTotalDefault = $attributes->mixed('budget_total_default');
        $this->budgetTotalNormalized = $attributes->mixed('budget_total_normalized');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->customFields = $attributes->object('custom_fields');
        $this->date = $attributes->date('date');
        $this->declinedAt = $attributes->dateTime('declined_at');
        $this->disclaimer = $attributes->string('disclaimer');
        $this->disclaimerEnabled = $attributes->bool('disclaimer_enabled');
        $this->endDate = $attributes->date('end_date');
        $this->exchangeDate = $attributes->date('exchange_date');
        $this->exchangeRate = $attributes->float('exchange_rate');
        $this->footer = $attributes->mixed('footer');
        $this->footerInterpolated = $attributes->mixed('footer_interpolated');
        $this->identityConfirmationEnabled = $attributes->bool('identity_confirmation_enabled');
        $this->identityConfirmedAt = $attributes->dateTime('identity_confirmed_at');
        $this->linkStatus = $attributes->string('link_status');
        $this->name = $attributes->string('name');
        $this->note = $attributes->string('note');
        $this->noteInterpolated = $attributes->mixed('note_interpolated');
        $this->number = $attributes->string('number');
        $this->pdfUrl = $attributes->string('pdf_url');
        $this->publicUuid = $attributes->string('public_uuid');
        $this->purchaseOrderNumber = $attributes->string('purchase_order_number');
        $this->responderEmail = $attributes->string('responder_email');
        $this->responderName = $attributes->string('responder_name');
        $this->sentAt = $attributes->dateTime('sent_at');
        $this->signed = $attributes->mixed('signed');
        $this->signedPdfUrl = $attributes->string('signed_pdf_url');
        $this->status = $attributes->string('status');
        $this->statusChangedAt = $attributes->dateTime('status_changed_at');
        $this->total = $attributes->string('total');
    }

    public function client(): ?Model
    {
        return $this->belongsTo('client', Model::class);
    }

    public function contact(): ?Model
    {
        return $this->belongsTo('contact', Model::class);
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function deal(): ?Deal
    {
        return $this->belongsTo('deal', Deal::class);
    }

    public function dealCreator(): ?Model
    {
        return $this->belongsTo('deal_creator', Model::class);
    }

    public function documentType(): ?DocumentType
    {
        return $this->belongsTo('document_type', DocumentType::class);
    }

    public function organization(): ?Model
    {
        return $this->belongsTo('organization', Model::class);
    }

    public function project(): ?Project
    {
        return $this->belongsTo('project', Project::class);
    }

    public function proposalFrom(): ?Model
    {
        return $this->belongsTo('proposal_from', Model::class);
    }

    public function proposalTo(): ?Model
    {
        return $this->belongsTo('proposal_to', Model::class);
    }

    public function responsible(): ?Person
    {
        return $this->belongsTo('responsible', Person::class);
    }

    public function subsidiary(): ?Model
    {
        return $this->belongsTo('subsidiary', Model::class);
    }

    public function taxRate(): ?TaxRate
    {
        return $this->belongsTo('tax_rate', TaxRate::class);
    }
}
