<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * Represents a named grouping of services within a deal or budget, used to organize line items into logical sections.
 *
 * @see https://developer.productive.io/reference/resources/sections
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Section extends Model
{
    public const string TYPE = 'sections';

    /**
     * Rich text editor configuration and content for this section's description.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $editorConfig;

    /** The name of this section. */
    public ?string $name;

    /** The sort position of this section within the deal. */
    public ?int $position;

    /**
     * User-specific display preferences for this section, stored as key-value settings.
     *
     * @var array<array-key, mixed>|null
     */
    public ?array $preferences;

    protected function hydrate(Attributes $attributes): void
    {
        $this->editorConfig = $attributes->object('editor_config');
        $this->name = $attributes->string('name');
        $this->position = $attributes->int('position');
        $this->preferences = $attributes->object('preferences');
    }

    public function deal(): ?Deal
    {
        return $this->belongsTo('deal', Deal::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }
}
