<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * An aggregated service report row grouping services by configurable dimensions with financial totals, time metrics, and billing analysis.
 *
 * @see https://developer.productive.io/reference/resources/reports
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class ServiceReport extends Model
{
    public const string TYPE = 'service_reports';

    /** Average actual rate for this service report group. */
    public mixed $averageActualRate;

    /** Average actual rate in the organization's default currency for this service report group. */
    public mixed $averageActualRateDefault;

    /** Average actual rate in the normalized currency for this service report group. */
    public mixed $averageActualRateNormalized;

    /** Average budget usage for this service report group. */
    public ?float $averageBudgetUsage;

    /** Average budget usage in the organization's default currency for this service report group. */
    public ?float $averageBudgetUsageDefault;

    /** Average budget usage in the normalized currency for this service report group. */
    public mixed $averageBudgetUsageNormalized;

    /** Average discount for this service report group. */
    public ?string $averageDiscount;

    /** Average forecasted budget usage for this service report group. */
    public ?float $averageForecastedBudgetUsage;

    /** Average forecasted budget usage in the organization's default currency for this service report group. */
    public ?float $averageForecastedBudgetUsageDefault;

    /** Average forecasted budget usage in the normalized currency for this service report group. */
    public mixed $averageForecastedBudgetUsageNormalized;

    /** Average forecasted time usage for this service report group. */
    public ?float $averageForecastedTimeUsage;

    /** Average markup for this service report group. */
    public ?string $averageMarkup;

    /** Average profit margin for this service report group. */
    public ?float $averageProfitMargin;

    /** Average profit margin in the organization's default currency for this service report group. */
    public ?float $averageProfitMarginDefault;

    /** Average profit margin in the normalized currency for this service report group. */
    public mixed $averageProfitMarginNormalized;

    /** The average number of interval units per retainer period across services in this group. */
    public ?int $averageRetainerIntervalCount;

    /** Billable for this service report group. */
    public ?int $billable;

    public ?int $billableTime;

    /** Billing type for this service report group. */
    public ?int $billingType;

    /** Booking tracking enabled for this service report group. */
    public ?int $bookingTrackingEnabled;

    /** Budget cap enabled for this service report group. */
    public ?int $budgetCapEnabled;

    /** Budget custom fields for this service report group. */
    public ?string $budgetCustomFields;

    /** Budget status for this service report group. */
    public ?int $budgetStatus;

    public ?string $budgetTotal;

    public ?string $budgetUsed;

    public ?string $cost;

    /** Number of services in this report group. */
    public ?int $count;

    /** Currency for this service report group. */
    public ?string $currency;

    /** Currency in the organization's default currency for this service report group. */
    public ?string $currencyDefault;

    /** Currency in the normalized currency for this service report group. */
    public ?string $currencyNormalized;

    /** Custom fields for this service report group. */
    public ?string $customFields;

    /** Time period grouping for date (e.g. week, month, quarter). */
    public mixed $datePeriod;

    /** Deal custom fields for this service report group. */
    public ?string $dealCustomFields;

    public ?int $dealId;

    public ?int $estimatedTime;

    /** Expense tracking enabled for this service report group. */
    public ?int $expenseTrackingEnabled;

    /** Formula fields for this service report group. */
    public mixed $formulaFields;

    /** The grouping dimension for this service report row. */
    public ?string $group;

    /** Limitation type for this service report group. */
    public ?string $limitationType;

    public ?int $nonbillableTime;

    public ?string $profit;

    public ?float $profitMargin;

    /** Project type for this service report group. */
    public ?int $projectType;

    /** Recurring for this service report group. */
    public ?int $recurring;

    public ?string $revenue;

    /** Section name for this service report group. */
    public ?string $sectionName;

    public ?int $serviceId;

    /** Stage status id for this service report group. */
    public ?int $stageStatusId;

    /** Stage type for this service report group. */
    public ?int $stageType;

    /** Time tracking enabled for this service report group. */
    public ?int $timeTrackingEnabled;

    /** Sum of billable time across all records in this service report group. */
    public ?float $totalBillableTime;

    /** Sum of booked time across all records in this service report group. */
    public ?float $totalBookedTime;

    /** Sum of budget remaining across all records in this service report group. */
    public mixed $totalBudgetRemaining;

    /** Sum of budget remaining in the organization's default currency across all records in this service report group. */
    public mixed $totalBudgetRemainingDefault;

    /** Sum of budget remaining in the normalized currency across all records in this service report group. */
    public mixed $totalBudgetRemainingNormalized;

    /** Sum of budget total across all records in this service report group. */
    public mixed $totalBudgetTotal;

    /** Sum of budget total in the organization's default currency across all records in this service report group. */
    public mixed $totalBudgetTotalDefault;

    /** Sum of budget total in the normalized currency across all records in this service report group. */
    public mixed $totalBudgetTotalNormalized;

    /** Sum of budget used across all records in this service report group. */
    public mixed $totalBudgetUsed;

    /** Sum of budget used in the organization's default currency across all records in this service report group. */
    public mixed $totalBudgetUsedDefault;

    /** Sum of budget used in the normalized currency across all records in this service report group. */
    public mixed $totalBudgetUsedNormalized;

    /** Sum of budgeted time across all records in this service report group. */
    public ?float $totalBudgetedTime;

    /** Sum of cost across all records in this service report group. */
    public mixed $totalCost;

    /** Sum of cost in the organization's default currency across all records in this service report group. */
    public mixed $totalCostDefault;

    /** Sum of cost in the normalized currency across all records in this service report group. */
    public mixed $totalCostNormalized;

    /** Sum of discount amount across all records in this service report group. */
    public mixed $totalDiscountAmount;

    /** Sum of discount amount in the organization's default currency across all records in this service report group. */
    public mixed $totalDiscountAmountDefault;

    /** Sum of discount amount in the normalized currency across all records in this service report group. */
    public mixed $totalDiscountAmountNormalized;

    /** Sum of estimated cost across all records in this service report group. */
    public mixed $totalEstimatedCost;

    /** Sum of estimated cost in the organization's default currency across all records in this service report group. */
    public mixed $totalEstimatedCostDefault;

    /** Sum of estimated cost in the normalized currency across all records in this service report group. */
    public mixed $totalEstimatedCostNormalized;

    /** Sum of estimated remaining time across all records in this service report group. */
    public ?float $totalEstimatedRemainingTime;

    /** Sum of estimated time across all records in this service report group. */
    public ?float $totalEstimatedTime;

    /** Sum of expense cost across all records in this service report group. */
    public mixed $totalExpenseCost;

    /** Sum of expense cost in the organization's default currency across all records in this service report group. */
    public mixed $totalExpenseCostDefault;

    /** Sum of expense cost in the normalized currency across all records in this service report group. */
    public mixed $totalExpenseCostNormalized;

    /** Sum of forecasted billable time across all records in this service report group. */
    public ?float $totalForecastedBillableTime;

    /** Sum of forecasted budget used across all records in this service report group. */
    public mixed $totalForecastedBudgetUsed;

    /** Sum of forecasted budget used in the organization's default currency across all records in this service report group. */
    public mixed $totalForecastedBudgetUsedDefault;

    /** Sum of forecasted budget used in the normalized currency across all records in this service report group. */
    public mixed $totalForecastedBudgetUsedNormalized;

    /** Sum of future booked time across all records in this service report group. */
    public ?float $totalFutureBookedTime;

    /** Sum of future budget used across all records in this service report group. */
    public mixed $totalFutureBudgetUsed;

    /** Sum of future budget used in the organization's default currency across all records in this service report group. */
    public mixed $totalFutureBudgetUsedDefault;

    /** Sum of future budget used in the normalized currency across all records in this service report group. */
    public mixed $totalFutureBudgetUsedNormalized;

    /** Sum of left to schedule time across all records in this service report group. */
    public ?float $totalLeftToScheduleTime;

    /** Sum of markup amount across all records in this service report group. */
    public mixed $totalMarkupAmount;

    /** Sum of markup amount in the organization's default currency across all records in this service report group. */
    public mixed $totalMarkupAmountDefault;

    /** Sum of markup amount in the normalized currency across all records in this service report group. */
    public mixed $totalMarkupAmountNormalized;

    /** Sum of price across all records in this service report group. */
    public mixed $totalPrice;

    /** Sum of price in the organization's default currency across all records in this service report group. */
    public mixed $totalPriceDefault;

    /** Sum of price in the normalized currency across all records in this service report group. */
    public mixed $totalPriceNormalized;

    /** Sum of profit across all records in this service report group. */
    public mixed $totalProfit;

    /** Sum of profit in the organization's default currency across all records in this service report group. */
    public mixed $totalProfitDefault;

    /** Sum of profit in the normalized currency across all records in this service report group. */
    public mixed $totalProfitNormalized;

    /** Sum of projected revenue across all records in this service report group. */
    public mixed $totalProjectedRevenue;

    /** Sum of projected revenue in the organization's default currency across all records in this service report group. */
    public mixed $totalProjectedRevenueDefault;

    /** Sum of projected revenue in the normalized currency across all records in this service report group. */
    public mixed $totalProjectedRevenueNormalized;

    /** Sum of recognized revenue across all records in this service report group. */
    public mixed $totalRecognizedRevenue;

    /** Sum of recognized revenue in the organization's default currency across all records in this service report group. */
    public mixed $totalRecognizedRevenueDefault;

    /** Sum of recognized revenue in the normalized currency across all records in this service report group. */
    public mixed $totalRecognizedRevenueNormalized;

    /** Sum of remaining scheduled time across all records in this service report group. */
    public ?float $totalRemainingScheduledTime;

    /** Sum of revenue across all records in this service report group. */
    public mixed $totalRevenue;

    /** Sum of revenue in the organization's default currency across all records in this service report group. */
    public mixed $totalRevenueDefault;

    /** Sum of revenue in the normalized currency across all records in this service report group. */
    public mixed $totalRevenueNormalized;

    /** Sum of rolled over time across all records in this service report group. */
    public ?float $totalRolledOverTime;

    /** Sum of unapproved time across all records in this service report group. */
    public ?float $totalUnapprovedTime;

    /** Sum of worked cost across all records in this service report group. */
    public mixed $totalWorkedCost;

    /** Sum of worked cost in the organization's default currency across all records in this service report group. */
    public mixed $totalWorkedCostDefault;

    /** Sum of worked cost in the normalized currency across all records in this service report group. */
    public mixed $totalWorkedCostNormalized;

    /** Sum of worked time across all records in this service report group. */
    public ?float $totalWorkedTime;

    /** Unit for this service report group. */
    public ?int $unit;

    public ?int $workedTime;

    protected function hydrate(Attributes $attributes): void
    {
        $this->averageActualRate = $attributes->mixed('average_actual_rate');
        $this->averageActualRateDefault = $attributes->mixed('average_actual_rate_default');
        $this->averageActualRateNormalized = $attributes->mixed('average_actual_rate_normalized');
        $this->averageBudgetUsage = $attributes->float('average_budget_usage');
        $this->averageBudgetUsageDefault = $attributes->float('average_budget_usage_default');
        $this->averageBudgetUsageNormalized = $attributes->mixed('average_budget_usage_normalized');
        $this->averageDiscount = $attributes->string('average_discount');
        $this->averageForecastedBudgetUsage = $attributes->float('average_forecasted_budget_usage');
        $this->averageForecastedBudgetUsageDefault = $attributes->float('average_forecasted_budget_usage_default');
        $this->averageForecastedBudgetUsageNormalized = $attributes->mixed('average_forecasted_budget_usage_normalized');
        $this->averageForecastedTimeUsage = $attributes->float('average_forecasted_time_usage');
        $this->averageMarkup = $attributes->string('average_markup');
        $this->averageProfitMargin = $attributes->float('average_profit_margin');
        $this->averageProfitMarginDefault = $attributes->float('average_profit_margin_default');
        $this->averageProfitMarginNormalized = $attributes->mixed('average_profit_margin_normalized');
        $this->averageRetainerIntervalCount = $attributes->int('average_retainer_interval_count');
        $this->billable = $attributes->int('billable');
        $this->billableTime = $attributes->int('billable_time');
        $this->billingType = $attributes->int('billing_type');
        $this->bookingTrackingEnabled = $attributes->int('booking_tracking_enabled');
        $this->budgetCapEnabled = $attributes->int('budget_cap_enabled');
        $this->budgetCustomFields = $attributes->string('budget_custom_fields');
        $this->budgetStatus = $attributes->int('budget_status');
        $this->budgetTotal = $attributes->string('budget_total');
        $this->budgetUsed = $attributes->string('budget_used');
        $this->cost = $attributes->string('cost');
        $this->count = $attributes->int('count');
        $this->currency = $attributes->string('currency');
        $this->currencyDefault = $attributes->string('currency_default');
        $this->currencyNormalized = $attributes->string('currency_normalized');
        $this->customFields = $attributes->string('custom_fields');
        $this->datePeriod = $attributes->mixed('date_period');
        $this->dealCustomFields = $attributes->string('deal_custom_fields');
        $this->dealId = $attributes->int('deal_id');
        $this->estimatedTime = $attributes->int('estimated_time');
        $this->expenseTrackingEnabled = $attributes->int('expense_tracking_enabled');
        $this->formulaFields = $attributes->mixed('formula_fields');
        $this->group = $attributes->string('group');
        $this->limitationType = $attributes->string('limitation_type');
        $this->nonbillableTime = $attributes->int('nonbillable_time');
        $this->profit = $attributes->string('profit');
        $this->profitMargin = $attributes->float('profit_margin');
        $this->projectType = $attributes->int('project_type');
        $this->recurring = $attributes->int('recurring');
        $this->revenue = $attributes->string('revenue');
        $this->sectionName = $attributes->string('section_name');
        $this->serviceId = $attributes->int('service_id');
        $this->stageStatusId = $attributes->int('stage_status_id');
        $this->stageType = $attributes->int('stage_type');
        $this->timeTrackingEnabled = $attributes->int('time_tracking_enabled');
        $this->totalBillableTime = $attributes->float('total_billable_time');
        $this->totalBookedTime = $attributes->float('total_booked_time');
        $this->totalBudgetRemaining = $attributes->mixed('total_budget_remaining');
        $this->totalBudgetRemainingDefault = $attributes->mixed('total_budget_remaining_default');
        $this->totalBudgetRemainingNormalized = $attributes->mixed('total_budget_remaining_normalized');
        $this->totalBudgetTotal = $attributes->mixed('total_budget_total');
        $this->totalBudgetTotalDefault = $attributes->mixed('total_budget_total_default');
        $this->totalBudgetTotalNormalized = $attributes->mixed('total_budget_total_normalized');
        $this->totalBudgetUsed = $attributes->mixed('total_budget_used');
        $this->totalBudgetUsedDefault = $attributes->mixed('total_budget_used_default');
        $this->totalBudgetUsedNormalized = $attributes->mixed('total_budget_used_normalized');
        $this->totalBudgetedTime = $attributes->float('total_budgeted_time');
        $this->totalCost = $attributes->mixed('total_cost');
        $this->totalCostDefault = $attributes->mixed('total_cost_default');
        $this->totalCostNormalized = $attributes->mixed('total_cost_normalized');
        $this->totalDiscountAmount = $attributes->mixed('total_discount_amount');
        $this->totalDiscountAmountDefault = $attributes->mixed('total_discount_amount_default');
        $this->totalDiscountAmountNormalized = $attributes->mixed('total_discount_amount_normalized');
        $this->totalEstimatedCost = $attributes->mixed('total_estimated_cost');
        $this->totalEstimatedCostDefault = $attributes->mixed('total_estimated_cost_default');
        $this->totalEstimatedCostNormalized = $attributes->mixed('total_estimated_cost_normalized');
        $this->totalEstimatedRemainingTime = $attributes->float('total_estimated_remaining_time');
        $this->totalEstimatedTime = $attributes->float('total_estimated_time');
        $this->totalExpenseCost = $attributes->mixed('total_expense_cost');
        $this->totalExpenseCostDefault = $attributes->mixed('total_expense_cost_default');
        $this->totalExpenseCostNormalized = $attributes->mixed('total_expense_cost_normalized');
        $this->totalForecastedBillableTime = $attributes->float('total_forecasted_billable_time');
        $this->totalForecastedBudgetUsed = $attributes->mixed('total_forecasted_budget_used');
        $this->totalForecastedBudgetUsedDefault = $attributes->mixed('total_forecasted_budget_used_default');
        $this->totalForecastedBudgetUsedNormalized = $attributes->mixed('total_forecasted_budget_used_normalized');
        $this->totalFutureBookedTime = $attributes->float('total_future_booked_time');
        $this->totalFutureBudgetUsed = $attributes->mixed('total_future_budget_used');
        $this->totalFutureBudgetUsedDefault = $attributes->mixed('total_future_budget_used_default');
        $this->totalFutureBudgetUsedNormalized = $attributes->mixed('total_future_budget_used_normalized');
        $this->totalLeftToScheduleTime = $attributes->float('total_left_to_schedule_time');
        $this->totalMarkupAmount = $attributes->mixed('total_markup_amount');
        $this->totalMarkupAmountDefault = $attributes->mixed('total_markup_amount_default');
        $this->totalMarkupAmountNormalized = $attributes->mixed('total_markup_amount_normalized');
        $this->totalPrice = $attributes->mixed('total_price');
        $this->totalPriceDefault = $attributes->mixed('total_price_default');
        $this->totalPriceNormalized = $attributes->mixed('total_price_normalized');
        $this->totalProfit = $attributes->mixed('total_profit');
        $this->totalProfitDefault = $attributes->mixed('total_profit_default');
        $this->totalProfitNormalized = $attributes->mixed('total_profit_normalized');
        $this->totalProjectedRevenue = $attributes->mixed('total_projected_revenue');
        $this->totalProjectedRevenueDefault = $attributes->mixed('total_projected_revenue_default');
        $this->totalProjectedRevenueNormalized = $attributes->mixed('total_projected_revenue_normalized');
        $this->totalRecognizedRevenue = $attributes->mixed('total_recognized_revenue');
        $this->totalRecognizedRevenueDefault = $attributes->mixed('total_recognized_revenue_default');
        $this->totalRecognizedRevenueNormalized = $attributes->mixed('total_recognized_revenue_normalized');
        $this->totalRemainingScheduledTime = $attributes->float('total_remaining_scheduled_time');
        $this->totalRevenue = $attributes->mixed('total_revenue');
        $this->totalRevenueDefault = $attributes->mixed('total_revenue_default');
        $this->totalRevenueNormalized = $attributes->mixed('total_revenue_normalized');
        $this->totalRolledOverTime = $attributes->float('total_rolled_over_time');
        $this->totalUnapprovedTime = $attributes->float('total_unapproved_time');
        $this->totalWorkedCost = $attributes->mixed('total_worked_cost');
        $this->totalWorkedCostDefault = $attributes->mixed('total_worked_cost_default');
        $this->totalWorkedCostNormalized = $attributes->mixed('total_worked_cost_normalized');
        $this->totalWorkedTime = $attributes->float('total_worked_time');
        $this->unit = $attributes->int('unit');
        $this->workedTime = $attributes->int('worked_time');
    }

    public function budget(): ?Deal
    {
        return $this->belongsTo('budget', Deal::class);
    }

    public function company(): ?Company
    {
        return $this->belongsTo('company', Company::class);
    }

    public function companyReport(): ?CompanyReport
    {
        return $this->belongsTo('company_report', CompanyReport::class);
    }

    public function contract(): ?Contract
    {
        return $this->belongsTo('contract', Contract::class);
    }

    public function dealOrBudgetReport(): ?Model
    {
        return $this->belongsTo('deal_or_budget_report', Model::class);
    }

    public function dealStatus(): ?DealStatus
    {
        return $this->belongsTo('deal_status', DealStatus::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function originDeal(): ?Deal
    {
        return $this->belongsTo('origin_deal', Deal::class);
    }

    public function originDealReport(): ?DealReport
    {
        return $this->belongsTo('origin_deal_report', DealReport::class);
    }

    public function ownerReport(): ?Model
    {
        return $this->belongsTo('owner_report', Model::class);
    }

    public function pipeline(): ?Pipeline
    {
        return $this->belongsTo('pipeline', Pipeline::class);
    }

    public function project(): ?Project
    {
        return $this->belongsTo('project', Project::class);
    }

    public function projectReport(): ?ProjectReport
    {
        return $this->belongsTo('project_report', ProjectReport::class);
    }

    public function report(): ?Model
    {
        return $this->belongsTo('report', Model::class);
    }

    public function responsible(): ?Person
    {
        return $this->belongsTo('responsible', Person::class);
    }

    public function section(): ?Section
    {
        return $this->belongsTo('section', Section::class);
    }

    public function service(): ?Service
    {
        return $this->belongsTo('service', Service::class);
    }

    public function serviceType(): ?ServiceType
    {
        return $this->belongsTo('service_type', ServiceType::class);
    }

    public function subsidiary(): ?Subsidiary
    {
        return $this->belongsTo('subsidiary', Subsidiary::class);
    }
}
