<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * An API access token session for a user, tracking device, browser, and IP information.
 *
 * @see https://developer.productive.io/reference/resources/sessions
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Session extends Model
{
    public const string TYPE = 'sessions';

    /** The avatar URL of the agent (admin) who created this session on behalf of the user, if applicable. */
    public mixed $agentAvatar;

    /** The first name of the agent (admin) who created this session on behalf of the user, or null if the user created it themselves. */
    public mixed $agentFirstName;

    /** The last name of the agent (admin) who created this session on behalf of the user, or null if the user created it themselves. */
    public mixed $agentLastName;

    /** The browser used to create this session, as detected from the user agent string. */
    public ?string $browser;

    public ?DateTimeImmutable $createdAt;

    /** The type of device used to create this session, such as desktop or mobile. */
    public ?string $device;

    /** Timestamp of the last request made in this session. */
    public ?DateTimeImmutable $lastActivityAt;

    /** The IP address from which this session was last used. */
    public ?string $lastIp;

    /** The geographic location associated with the last IP address used in this session. */
    public ?string $location;

    /** When true, this session belongs to a machine (API token) rather than an interactive user session. */
    public ?bool $machine;

    /** A user-assigned label for this session, used to identify API tokens or machine sessions. */
    public ?string $name;

    /** An optional note describing the purpose of this session or API token. */
    public ?string $note;

    /** The operating system platform detected from the device used to create this session. */
    public ?string $platform;

    /** When true, this session has read-only access and cannot make changes. */
    public ?bool $readOnly;

    /** Whether this session was authenticated via Single Sign-On. */
    public ?bool $singleSignOn;

    /** The API access token for authenticating requests in this session. */
    public mixed $token;

    /** Timestamp when this session's token expires, or null if the session does not expire. */
    public ?DateTimeImmutable $tokenExpiresAt;

    /** When true, two-factor authentication has been verified for this session. */
    public ?bool $twoFactorAuth;

    /** ID of the user this session belongs to. */
    public ?int $userId;

    protected function hydrate(Attributes $attributes): void
    {
        $this->agentAvatar = $attributes->mixed('agent_avatar');
        $this->agentFirstName = $attributes->mixed('agent_first_name');
        $this->agentLastName = $attributes->mixed('agent_last_name');
        $this->browser = $attributes->string('browser');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->device = $attributes->string('device');
        $this->lastActivityAt = $attributes->dateTime('last_activity_at');
        $this->lastIp = $attributes->string('last_ip');
        $this->location = $attributes->string('location');
        $this->machine = $attributes->bool('machine');
        $this->name = $attributes->string('name');
        $this->note = $attributes->string('note');
        $this->platform = $attributes->string('platform');
        $this->readOnly = $attributes->bool('read_only');
        $this->singleSignOn = $attributes->bool('single_sign_on');
        $this->token = $attributes->mixed('token');
        $this->tokenExpiresAt = $attributes->dateTime('token_expires_at');
        $this->twoFactorAuth = $attributes->bool('two_factor_auth');
        $this->userId = $attributes->int('user_id');
    }

    public function user(): ?User
    {
        return $this->belongsTo('user', User::class);
    }
}
