<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * Submitted form response for a survey. Contains field values keyed by survey_field_id. Triggers any automations configured on the parent survey.
 *
 * @see https://developer.productive.io/reference/resources/survey-responses
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class SurveyResponse extends Model
{
    public const string TYPE = 'survey_responses';

    /** @var array<array-key, mixed>|null */
    public ?array $answers;

    /** Timestamp when this survey response was created. */
    public ?DateTimeImmutable $createdAt;

    public ?DateTimeImmutable $submittedAt;

    /** The survey field responses included in this submission. */
    public mixed $surveyFields;

    /** Timestamp when this survey response was last updated. */
    public ?DateTimeImmutable $updatedAt;

    protected function hydrate(Attributes $attributes): void
    {
        $this->answers = $attributes->object('answers');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->submittedAt = $attributes->dateTime('submitted_at');
        $this->surveyFields = $attributes->mixed('survey_fields');
        $this->updatedAt = $attributes->dateTime('updated_at');
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    /**
     * @return list<Attachment>
     */
    public function customFieldAttachments(): array
    {
        return $this->hasMany('custom_field_attachments', Attachment::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function survey(): ?Survey
    {
        return $this->belongsTo('survey', Survey::class);
    }
}
