<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * Selectable option for a dropdown or multi-select survey field. Has a label and position for ordering.
 *
 * @see https://developer.productive.io/reference/resources/survey-field-options
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class SurveyFieldOption extends Model
{
    public const string TYPE = 'survey_field_options';

    /** Timestamp when this option was archived, or null if not archived. */
    public ?DateTimeImmutable $archivedAt;

    /** ID of the color associated with this option. */
    public ?int $colorId;

    public ?string $label;

    /** The display label for this answer option. */
    public ?string $name;

    /** The display order position of this option within the survey field. */
    public ?int $position;

    public ?string $value;

    protected function hydrate(Attributes $attributes): void
    {
        $this->archivedAt = $attributes->dateTime('archived_at');
        $this->colorId = $attributes->int('color_id');
        $this->label = $attributes->string('label');
        $this->name = $attributes->string('name');
        $this->position = $attributes->int('position');
        $this->value = $attributes->string('value');
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function surveyField(): ?SurveyField
    {
        return $this->belongsTo('survey_field', SurveyField::class);
    }
}
