<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;

/**
 * Named group of people. Includes the team name and a list of member people (via has_many members). Teams are used for access control (memberships) and reporting groupings.
 *
 * @see https://developer.productive.io/reference/resources/teams
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Team extends Model
{
    public const string TYPE = 'teams';

    /** The identifier of the color associated with this team. */
    public ?int $colorId;

    /** The identifier of the icon associated with this team. */
    public ?string $iconId;

    /** The name of this team. */
    public ?string $name;

    protected function hydrate(Attributes $attributes): void
    {
        $this->colorId = $attributes->int('color_id');
        $this->iconId = $attributes->string('icon_id');
        $this->name = $attributes->string('name');
    }

    /**
     * @return list<Person>
     */
    public function members(): array
    {
        return $this->hasMany('members', Person::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }
}
