<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A time tracking policy defines rules for how time entries can be logged, including limits and mandatory fields.
 *
 * @see https://developer.productive.io/reference/resources/time-tracking-policies
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class TimeTrackingPolicy extends Model
{
    public const string TYPE = 'time_tracking_policies';

    /** Timestamp when this policy was archived, or null if it is still active. */
    public ?DateTimeImmutable $archivedAt;

    /** The number of active people currently assigned to this time tracking policy. */
    public mixed $assignedPeopleCount;

    /** Timestamp when the time tracking policy was created. */
    public ?DateTimeImmutable $createdAt;

    public ?int $dailyLimit;

    public ?int $defaultTrackMethodId;

    /** Message shown to people when time tracking is fully disabled for them. */
    public ?string $disabledTrackingMessage;

    /** Maximum hours that can be tracked on a full day of absence. */
    public ?int $fullDayAbsenceLimit;

    /** Maximum hours that can be tracked on a half day of absence. */
    public ?int $halfDayAbsenceLimit;

    /** Maximum hours that can be tracked on a public holiday. */
    public ?int $holidayLimit;

    /** Message shown to people when time tracking is limited (not fully disabled) for them. */
    public ?string $limitedTrackingMessage;

    /** The display name of the time tracking policy. */
    public ?string $name;

    /** Maximum hours that can be tracked on a non-working day. */
    public ?int $nonWorkingDayLimit;

    /** When true, a note is required on every time entry submitted. */
    public ?bool $noteMandatory;

    public ?bool $requiresService;

    public ?bool $requiresTask;

    /** When true, overlapping time entry ranges are not allowed. */
    public ?bool $restrictTimeEntryOverlap;

    /** @var list<mixed>|null */
    public ?array $trackMethodIds;

    /** Timestamp when this time tracking policy was last updated. */
    public ?DateTimeImmutable $updatedAt;

    /** Maximum hours that can be tracked on a standard working day. */
    public ?int $workingDayLimit;

    protected function hydrate(Attributes $attributes): void
    {
        $this->archivedAt = $attributes->dateTime('archived_at');
        $this->assignedPeopleCount = $attributes->mixed('assigned_people_count');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->dailyLimit = $attributes->int('daily_limit');
        $this->defaultTrackMethodId = $attributes->int('default_track_method_id');
        $this->disabledTrackingMessage = $attributes->string('disabled_tracking_message');
        $this->fullDayAbsenceLimit = $attributes->int('full_day_absence_limit');
        $this->halfDayAbsenceLimit = $attributes->int('half_day_absence_limit');
        $this->holidayLimit = $attributes->int('holiday_limit');
        $this->limitedTrackingMessage = $attributes->string('limited_tracking_message');
        $this->name = $attributes->string('name');
        $this->nonWorkingDayLimit = $attributes->int('non_working_day_limit');
        $this->noteMandatory = $attributes->bool('note_mandatory');
        $this->requiresService = $attributes->bool('requires_service');
        $this->requiresTask = $attributes->bool('requires_task');
        $this->restrictTimeEntryOverlap = $attributes->bool('restrict_time_entry_overlap');
        $this->trackMethodIds = $attributes->list('track_method_ids');
        $this->updatedAt = $attributes->dateTime('updated_at');
        $this->workingDayLimit = $attributes->int('working_day_limit');
    }

    public function creator(): ?Person
    {
        return $this->belongsTo('creator', Person::class);
    }

    public function lastActor(): ?Person
    {
        return $this->belongsTo('last_actor', Person::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }
}
