<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * Checklist item on a task or deal. Supports description, assignee, due date (with optional time), position ordering, and completion tracking via closed_at timestamp.
 *
 * @see https://developer.productive.io/reference/resources/todos
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class Todo extends Model
{
    public const string TYPE = 'todos';

    /** Indicates whether this checklist item has been completed. */
    public ?bool $closed;

    /** Timestamp when this checklist item was completed, or null if still open. */
    public ?DateTimeImmutable $closedAt;

    /** Timestamp when this checklist item was created. */
    public ?DateTimeImmutable $createdAt;

    /** Text of the todo — the content of the checklist item. */
    public ?string $description;

    /** The due date for completing this checklist item. */
    public ?DateTimeImmutable $dueDate;

    /** The specific time of day the checklist item is due. */
    public ?string $dueTime;

    /** The display order of this todo within its parent list. */
    public ?int $position;

    /** The type of the parent resource this todo is attached to (task or deal). */
    public ?string $todoableType;

    protected function hydrate(Attributes $attributes): void
    {
        $this->closed = $attributes->bool('closed');
        $this->closedAt = $attributes->dateTime('closed_at');
        $this->createdAt = $attributes->dateTime('created_at');
        $this->description = $attributes->string('description');
        $this->dueDate = $attributes->date('due_date');
        $this->dueTime = $attributes->string('due_time');
        $this->position = $attributes->int('position');
        $this->todoableType = $attributes->string('todoable_type');
    }

    public function assignee(): ?Person
    {
        return $this->belongsTo('assignee', Person::class);
    }

    public function deal(): ?Deal
    {
        return $this->belongsTo('deal', Deal::class);
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function task(): ?Task
    {
        return $this->belongsTo('task', Task::class);
    }
}
