<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Models;

use Axyr\Productive\Data\Attributes;
use Axyr\Productive\Data\Model;
use DateTimeImmutable;

/**
 * A webhook log records a single delivery attempt of a webhook event to its target URL, capturing the payload sent, HTTP response code, and retry details.
 *
 * @see https://developer.productive.io/reference/resources/webhook-logs
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 * @SuppressWarnings("PHPMD.ExcessiveClassComplexity")
 * @SuppressWarnings("PHPMD.TooManyFields")
 */
final readonly class WebhookLog extends Model
{
    public const string TYPE = 'webhook_logs';

    /** Timestamp when this webhook delivery attempt was made. */
    public ?DateTimeImmutable $createdAt;

    public ?string $eventType;

    /** The JSON payload that was sent to the target URL. */
    public ?string $payload;

    public ?string $responseBody;

    public ?int $responseCode;

    /** The retry attempt number for this delivery, where 0 is the initial attempt. */
    public ?int $retryAttempt;

    /** The background job ID for a scheduled retry of this delivery, or null if no retry is pending. */
    public ?string $retryJobId;

    public ?DateTimeImmutable $sentAt;

    /** The HTTP response status code returned by the target URL. */
    public ?int $statusCode;

    public ?bool $success;

    /** The URL to which the webhook payload was delivered. */
    public ?string $targetUrl;

    public ?string $url;

    protected function hydrate(Attributes $attributes): void
    {
        $this->createdAt = $attributes->dateTime('created_at');
        $this->eventType = $attributes->string('event_type');
        $this->payload = $attributes->string('payload');
        $this->responseBody = $attributes->string('response_body');
        $this->responseCode = $attributes->int('response_code');
        $this->retryAttempt = $attributes->int('retry_attempt');
        $this->retryJobId = $attributes->string('retry_job_id');
        $this->sentAt = $attributes->dateTime('sent_at');
        $this->statusCode = $attributes->int('status_code');
        $this->success = $attributes->bool('success');
        $this->targetUrl = $attributes->string('target_url');
        $this->url = $attributes->string('url');
    }

    public function organization(): ?Organization
    {
        return $this->belongsTo('organization', Organization::class);
    }

    public function webhook(): ?Webhook
    {
        return $this->belongsTo('webhook', Webhook::class);
    }
}
