<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\ApprovalWorkflow;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<ApprovalWorkflow>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class ApprovalWorkflowFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return ApprovalWorkflow::class;
    }

    protected function definition(): array
    {
        return [
            'approval_requirement_id' => 1,
            'target_type_id' => 1,
            'dynamic_approver_ids' => [],
            'dynamic_subscriber_ids' => [],
        ];
    }
}
