<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\BudgetReport;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<BudgetReport>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class BudgetReportFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return BudgetReport::class;
    }

    protected function definition(): array
    {
        return [
            'budget_total' => '100000.00',
            'budget_used' => '62000.00',
            'revenue' => '75000.00',
            'cost' => '45000.00',
            'profit' => '30000.00',
            'profit_margin' => 0.4,
            'billable_time' => 48000,
            'nonbillable_time' => 6000,
            'expense_amount' => '3500.00',
            'project_id' => 6899,
            'deal_id' => 89,
            'currency' => 'USD',
        ];
    }
}
