<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Company;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Company>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class CompanyFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Company::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Acme Corp',
            'billing_name' => 'Acme Corporation Ltd',
            'vat' => 'DE123456789',
            'default_currency' => 'USD',
            'created_at' => '2026-01-01T00:00:00.000+00:00',
            'last_activity_at' => '2026-03-10T14:00:00.000+00:00',
            'archived_at' => null,
            'avatar_url' => null,
            'original_avatar_url' => null,
            'invoice_email_recipients' => [],
            'custom_fields' => null,
            'company_code' => 'ACME1',
            'domain' => 'acme.com',
            'domains' => ['acme.com'],
            'projectless_budgets' => false,
            'default_subsidiary_id' => null,
            'default_tax_rate_id' => null,
            'default_document_type_id' => null,
            'due_days' => 30,
            'tag_list' => ['enterprise'],
            'contact' => [],
            'sample_data' => false,
            'settings' => [],
            'external_id' => null,
            'external_sync' => false,
            'parent_company_id' => null,
        ];
    }
}
