<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\CompanyReport;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<CompanyReport>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class CompanyReportFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return CompanyReport::class;
    }

    protected function definition(): array
    {
        return [
            'revenue' => '250000.00',
            'invoiced' => '175000.00',
            'payments' => '140000.00',
            'outstanding' => '35000.00',
            'billable_time' => 120000,
            'company_id' => 65111,
            'currency' => 'USD',
        ];
    }
}
