<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Contract;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Contract>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class ContractFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Contract::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Master Services Agreement',
            'status' => 'active',
            'start_date' => '2026-01-01',
            'end_date' => '2026-12-31',
            'created_at' => '2026-01-01T00:00:00.000+00:00',
        ];
    }
}
