<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\ContactEntry;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<ContactEntry>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class ContactEntryFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return ContactEntry::class;
    }

    protected function definition(): array
    {
        return [
            'contactable_type' => 'company',
            'name' => 'Headquarters',
            'email' => 'hello@acmecorp.com',
            'phone' => '+1-555-0123',
            'website' => 'https://acmecorp.com',
            'address' => '123 Innovation Drive',
            'city' => 'San Francisco',
            'state' => 'CA',
            'zipcode' => '94105',
            'country' => 'US',
            'billing_address' => '123 Innovation Drive, San Francisco, CA 94105',
            'billing_email' => 'billing@acmecorp.com',
        ];
    }
}
