<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\CustomFieldOption;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<CustomFieldOption>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class CustomFieldOptionFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return CustomFieldOption::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'High',
            'color_id' => '1',
            'position' => 1,
            'archived_at' => null,
        ];
    }
}
