<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Discussion;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Discussion>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class DiscussionFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Discussion::class;
    }

    protected function definition(): array
    {
        return [
            'title' => 'API Design Review',
            'note' => 'Let\'s discuss the new API endpoint design for the authentication module',
            'created_at' => '2026-02-01T10:00:00.000+00:00',
            'updated_at' => '2026-03-01T09:00:00.000+00:00',
            'last_activity_at' => '2026-03-01T09:00:00.000+00:00',
        ];
    }
}
