<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\DocumentStyle;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<DocumentStyle>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class DocumentStyleFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return DocumentStyle::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Modern Blue',
            'created_at' => '2026-01-01T00:00:00.000+00:00',
        ];
    }
}
