<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\EinvoiceIdentity;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<EinvoiceIdentity>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class EinvoiceIdentityFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return EinvoiceIdentity::class;
    }

    protected function definition(): array
    {
        return [
            'peppol_id' => '0088:1234567890123',
            'buyer_reference' => 'BUYER-REF-001',
            'dir3_fiscal_code' => null,
            'dir3_pagador_code' => null,
            'dir3_receptor_code' => null,
            'dire_code' => null,
            'is_government_entity' => false,
            'created_at' => '2025-04-10T08:15:00.000Z',
            'updated_at' => '2025-04-10T08:15:00.000Z',
        ];
    }
}
