<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Event;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Event>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class EventFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Event::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Vacation',
            'event_type_id' => 1,
            'icon_id' => '3',
            'color_id' => '7',
            'archived_at' => null,
            'limitation_type_id' => 1,
            'sync_personal_integrations' => false,
            'half_day_bookings' => true,
            'description' => 'Annual paid leave',
            'absence_type' => 'vacation',
        ];
    }
}
