<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\ExpenseLineItem;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<ExpenseLineItem>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class ExpenseLineItemFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return ExpenseLineItem::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'AWS hosting',
            'quantity' => 2,
            'unit_price' => 15000,
            'unit_price_default' => 16500,
            'unit_price_normalized' => 16500,
            'currency' => 'EUR',
            'currency_default' => 'USD',
            'currency_normalized' => 'USD',
        ];
    }
}
