<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Invoice;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Invoice>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class InvoiceFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Invoice::class;
    }

    protected function definition(): array
    {
        return [
            'number' => 'INV-2026-001',
            'status' => 'draft',
            'due_date' => '2026-04-15',
            'date' => '2026-03-15',
            'created_at' => '2026-03-15T09:00:00.000+00:00',
            'updated_at' => '2026-03-15T09:00:00.000+00:00',
            'total' => '12500.00',
            'subtotal' => '11363.64',
            'tax' => '1136.36',
            'currency' => 'USD',
            'notes' => 'Payment due within 30 days',
            'last_activity_at' => '2026-03-15T09:00:00.000+00:00',
        ];
    }
}
