<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Membership;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Membership>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class MembershipFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Membership::class;
    }

    protected function definition(): array
    {
        return [
            'access_type_id' => 1,
            'dynamic_group_id' => null,
            'options' => [],
            'target_type' => 'project',
            'type_id' => 1,
        ];
    }
}
