<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Notification;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Notification>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class NotificationFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Notification::class;
    }

    protected function definition(): array
    {
        return [
            'target_id' => 120501,
            'target_type' => 'task',
            'target_title' => '#42: Implement user authentication',
            'target_label' => 'task',
            'parent_id' => 6899,
            'parent_type' => 'project',
            'parent_title' => 'Website Redesign',
            'title' => 'Alex Smith changed the status to In Progress',
            'read' => false,
            'dismissed' => false,
            'new_activities_count' => 1,
            'excerpt' => 'Status changed from Open to In Progress',
            'last_action_at' => '2026-03-15T10:30:00.000+00:00',
            'first_unread_activity_id' => 259275372,
            'important' => false,
            'mention' => false,
            'made_by_automation' => false,
            'root_id' => 6899,
            'root_type' => 'project',
        ];
    }
}
