<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\PageVersion;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<PageVersion>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class PageVersionFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return PageVersion::class;
    }

    protected function definition(): array
    {
        return [
            'version_number' => 3,
            'created_at' => '2026-03-10T15:00:00.000+00:00',
        ];
    }
}
