<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Person;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Person>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class PersonFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Person::class;
    }

    protected function definition(): array
    {
        return [
            'agent' => false,
            'avatar_url' => null,
            'contact' => [],
            'deactivated_at' => null,
            'email' => 'alex.smith@example.com',
            'first_name' => 'Alex',
            'last_name' => 'Smith',
            'nickname' => 'alex',
            'title' => 'Senior Developer',
            'role_id' => 1,
            'status_emoji' => null,
            'status_text' => null,
            'status_expires_at' => null,
            'time_off_status_sync' => false,
            'archived_at' => null,
            'autotracking' => false,
            'joined_at' => '2026-01-01T00:00:00.000+00:00',
            'last_seen_at' => '2026-03-15T10:00:00.000+00:00',
            'invited_at' => null,
            'is_user' => true,
            'user_id' => 456,
            'tag_list' => [],
            'virtual' => false,
            'custom_fields' => null,
            'created_at' => '2026-01-01T00:00:00.000+00:00',
            'placeholder' => false,
            'color_id' => '5',
            'two_factor_auth' => false,
            'availabilities' => [[8, 0, 0, 0, 0]],
            'hrm_type_id' => 1,
            'champion' => false,
            'offboarding_status' => null,
            'offboarding_id' => null,
            'time_tracking_policy_id' => null,
        ];
    }
}
