<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\PlaceholderUsage;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<PlaceholderUsage>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class PlaceholderUsageFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return PlaceholderUsage::class;
    }

    protected function definition(): array
    {
        return [
            'target_id' => 7388879,
            'target_type' => 'Ticket',
            'field' => 'assignee',
            'placeholder_id' => 88,
            'interval_value' => null,
            'interval_unit' => null,
            'interval_direction' => null,
            'skip_weekends' => false,
            'interval_enabled' => false,
            'created_at' => '2026-09-02T11:48:44.135+02:00',
            'updated_at' => '2026-09-02T11:48:44.135+02:00',
        ];
    }
}
