<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Placeholder;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Placeholder>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class PlaceholderFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Placeholder::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Employee',
            'category' => 'project',
            'color' => 'electric',
            'icon' => 'icon-cowboy-hat-filled',
            'created_at' => '2026-09-02T11:48:32.010+02:00',
            'updated_at' => '2026-09-02T11:48:42.251+02:00',
        ];
    }
}
