<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\ProposalReport;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<ProposalReport>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class ProposalReportFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return ProposalReport::class;
    }

    protected function definition(): array
    {
        return [
            'total' => '45000.00',
            'status' => 'sent',
            'deal_id' => 89,
            'company_id' => 65111,
            'currency' => 'USD',
        ];
    }
}
