<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Section;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Section>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class SectionFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Section::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Design Phase',
            'position' => 1,
            'preferences' => [],
            'editor_config' => [],
        ];
    }
}
