<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Service;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Service>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class ServiceFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Service::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Frontend Development',
            'position' => 1,
            'deleted_at' => null,
            'description' => 'Building React components and user interfaces',
            'time_tracking_enabled' => true,
            'expense_tracking_enabled' => false,
            'booking_tracking_enabled' => true,
            'origin_service_id' => null,
            'initial_service_id' => 1856422,
            'editor_config' => [],
            'custom_fields' => null,
            'billing_type_id' => 1,
            'limitation_type' => 'no_limitation',
            'worked_time' => 4800,
            'billable_time' => 4800,
            'estimated_time' => 8000,
            'budgeted_time' => 8000,
            'currency' => 'USD',
        ];
    }
}
