<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\SurveyReport;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<SurveyReport>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class SurveyReportFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return SurveyReport::class;
    }

    protected function definition(): array
    {
        return [
            'response_count' => 42,
            'avg_score' => 4.2,
            'survey_id' => 7,
            'project_id' => 6899,
        ];
    }
}
