<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\TaskList;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<TaskList>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class TaskListFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return TaskList::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Sprint 42',
            'position' => 1,
            'placement' => 1000000,
            'archived_at' => null,
            'email_key' => 'a1b2c3d4e5f6789012345678901234ab',
        ];
    }
}
