<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\TaskReport;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<TaskReport>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class TaskReportFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return TaskReport::class;
    }

    protected function definition(): array
    {
        return [
            'billable_time' => 480,
            'nonbillable_time' => 60,
            'total_time' => 540,
            'initial_estimate' => 480,
            'remaining_time' => 0,
            'task_id' => 120501,
            'project_id' => 6899,
        ];
    }
}
