<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\TaxRate;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<TaxRate>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class TaxRateFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return TaxRate::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Standard VAT 20%',
            'primary_component_name' => 'VAT',
            'primary_component_value' => '0.2',
            'secondary_component_name' => null,
            'secondary_component_value' => null,
            'archived_at' => null,
        ];
    }
}
