<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Template;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Template>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class TemplateFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Template::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Offboarding: General',
            'description' => 'Popis stvari koje trebamo obaviti kada osoba odlazi iz firme',
            'target_id' => '258974',
            'target_type' => 'project',
            'color_id' => null,
            'created_at' => '2023-01-24T14:08:06.857+01:00',
            'updated_at' => '2026-04-29T12:27:06.627+02:00',
            'deleted_at' => null,
        ];
    }
}
