<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\TimeTrackingPolicy;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<TimeTrackingPolicy>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class TimeTrackingPolicyFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return TimeTrackingPolicy::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Standard Policy',
            'track_method_ids' => [1, 2],
            'default_track_method_id' => 1,
            'daily_limit' => 720,
            'requires_task' => false,
            'requires_service' => true,
        ];
    }
}
