<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\TimesheetReport;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<TimesheetReport>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class TimesheetReportFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return TimesheetReport::class;
    }

    protected function definition(): array
    {
        return [
            'status' => 'submitted',
            'week_starting' => '2026-03-10',
            'total_time' => 2400,
            'submitted_at' => '2026-03-17T09:00:00.000+00:00',
            'approved_at' => null,
        ];
    }
}
