<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\User;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<User>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class UserFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return User::class;
    }

    protected function definition(): array
    {
        return [
            'email' => 'alex.smith@example.com',
            'first_name' => 'Alex',
            'last_name' => 'Smith',
            'time_zone' => 'America/New_York',
            'avatar_url' => null,
            'default_organization_id' => 109,
            'default_organization_slug' => 'myagency',
            'locale' => 'en',
            'two_factor_auth' => false,
            'newsletter_consent' => true,
            'preferences' => [],
            'updated_at' => '2026-03-15T10:00:00.000+00:00',
        ];
    }
}
