<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Webhook;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Webhook>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class WebhookFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Webhook::class;
    }

    protected function definition(): array
    {
        return [
            'url' => 'https://hooks.example.com/productive',
            'events' => ['task.created', 'time_entry.created', 'invoice.paid'],
            'active' => true,
            'secret' => null,
            'created_at' => '2026-01-01T00:00:00.000+00:00',
        ];
    }
}
