<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\WorkflowStatus;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<WorkflowStatus>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class WorkflowStatusFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return WorkflowStatus::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'In Progress',
            'color_id' => '5',
            'position' => 2,
            'category_id' => 2,
        ];
    }
}
