<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Testing\Factories;

use Axyr\Productive\Data\Models\Workflow;

/**
 * Defaults are the attributes of the example in Productive's API reference.
 *
 * @extends Factory<Workflow>
 *
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final class WorkflowFactory extends Factory
{
    public static function new(): self
    {
        return new self();
    }

    protected function model(): string
    {
        return Workflow::class;
    }

    protected function definition(): array
    {
        return [
            'name' => 'Default Workflow',
            'archived_at' => null,
        ];
    }
}
