<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\AutomationReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * @see https://developer.productive.io/reference/resources/reports
 */
final class AutomationReportResource extends Resource
{
    protected const string TYPE = 'automation_reports';

    protected const string PATH = 'reports/automation_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get automation reports.
     *
     * GET /reports/automation_reports
     *
     * @return PendingQuery<AutomationReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(AutomationReport::class, 'reports.automation_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
