<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\BookingReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated booking report row grouping scheduled bookings by configurable dimensions with capacity, utilization, and cost metrics.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class BookingReportResource extends Resource
{
    protected const string TYPE = 'booking_reports';

    protected const string PATH = 'reports/booking_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get booking reports.
     *
     * GET /reports/booking_reports
     *
     * @return PendingQuery<BookingReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(BookingReport::class, 'reports.booking_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
