<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\CompanyReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated company report row grouping client companies by configurable dimensions with revenue, invoicing, and relationship metrics.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class CompanyReportResource extends Resource
{
    protected const string TYPE = 'company_reports';

    protected const string PATH = 'reports/company_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get company reports.
     *
     * GET /reports/company_reports
     *
     * @return PendingQuery<CompanyReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(CompanyReport::class, 'reports.company_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
