<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\DealFunnelReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated deal funnel report showing pipeline conversion rates, stage progression, and win/loss analysis. Each row represents deals grouped by pipeline stage (deal status), with counts of active and lost deals and total financial values. Used to visualize funnel drop-off and conversion across the sales pipeline.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class DealFunnelReportResource extends Resource
{
    protected const string TYPE = 'deal_funnel_reports';

    protected const string PATH = 'reports/deal_funnel_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get funnel reports.
     *
     * GET /reports/deal_funnel_reports
     *
     * @return PendingQuery<DealFunnelReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(DealFunnelReport::class, 'reports.deal_funnel_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
