<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\DealReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated deal report row. Deal reports group deals by configurable dimensions and calculate financial totals, pipeline metrics, and conversion rates.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class DealReportResource extends Resource
{
    protected const string TYPE = 'deal_reports';

    protected const string PATH = 'reports/deal_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get deal reports.
     *
     * GET /reports/deal_reports
     *
     * @return PendingQuery<DealReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(DealReport::class, 'reports.deal_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
