<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\InvoiceReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated invoice report row grouping invoices by configurable dimensions with payment totals, aging analysis, and billing metrics. Each row represents one group (e.g. by company, subsidiary, or time period) and exposes the invoice's financial fields — amount, tax, paid, unpaid, written off, and credited — along with period groupings and relationship pointers to company, issuer, and creator.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class InvoiceReportResource extends Resource
{
    protected const string TYPE = 'invoice_reports';

    protected const string PATH = 'reports/invoice_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get invoice reports.
     *
     * GET /reports/invoice_reports
     *
     * @return PendingQuery<InvoiceReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(InvoiceReport::class, 'reports.invoice_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
