<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\LineItemReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated line item report row grouping invoice line items by configurable dimensions with amount metrics.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class LineItemReportResource extends Resource
{
    protected const string TYPE = 'line_item_reports';

    protected const string PATH = 'reports/line_item_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get line item reports.
     *
     * GET /reports/line_item_reports
     *
     * @return PendingQuery<LineItemReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(LineItemReport::class, 'reports.line_item_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
