<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\PaymentReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated payment report row grouping invoices and payments by configurable dimensions with payment amount metrics.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class PaymentReportResource extends Resource
{
    protected const string TYPE = 'payment_reports';

    protected const string PATH = 'reports/payment_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get payment reports.
     *
     * GET /reports/payment_reports
     *
     * @return PendingQuery<PaymentReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(PaymentReport::class, 'reports.payment_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
