<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\PayrollItemReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated payroll item report row grouping payroll entries by configurable dimensions with cost metrics.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class PayrollItemReportResource extends Resource
{
    protected const string TYPE = 'payroll_item_reports';

    protected const string PATH = 'reports/payroll_item_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get payroll item reports.
     *
     * GET /reports/payroll_item_reports
     *
     * @return PendingQuery<PayrollItemReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(PayrollItemReport::class, 'reports.payroll_item_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
