<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\ResourceRequestReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * @see https://developer.productive.io/reference/resources/reports
 */
final class ResourceRequestReportResource extends Resource
{
    protected const string TYPE = 'resource_request_reports';

    protected const string PATH = 'reports/resource_request_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get resource request reports.
     *
     * GET /reports/resource_request_reports
     *
     * @return PendingQuery<ResourceRequestReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(ResourceRequestReport::class, 'reports.resource_request_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
