<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\ServiceReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated service report row grouping services by configurable dimensions with financial totals, time metrics, and billing analysis.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class ServiceReportResource extends Resource
{
    protected const string TYPE = 'service_reports';

    protected const string PATH = 'reports/service_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get service reports.
     *
     * GET /reports/service_reports
     *
     * @return PendingQuery<ServiceReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(ServiceReport::class, 'reports.service_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
