<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\TimeReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * A time report row aggregating tracked hours by configurable dimensions with utilization, capacity, and overtime calculations.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class TimeReportResource extends Resource
{
    protected const string TYPE = 'new_time_reports';

    protected const string PATH = 'reports/time_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get time reports.
     *
     * GET /reports/time_reports
     *
     * @return PendingQuery<TimeReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(TimeReport::class, 'reports.time_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
