<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\TimeEntryReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * Time entry report record — aggregates tracked time with financial metrics including cost, revenue, and approval status.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class TimeEntryReportResource extends Resource
{
    protected const string TYPE = 'time_entry_reports';

    protected const string PATH = 'reports/time_entry_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get time entry reports.
     *
     * GET /reports/time_entry_reports
     *
     * @return PendingQuery<TimeEntryReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(TimeEntryReport::class, 'reports.time_entry_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
