<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Resources\Reports;

use Axyr\Productive\Data\Models\TimesheetReport;
use Axyr\Productive\Http\RateLimit;
use Axyr\Productive\Resources\PendingQuery;
use Axyr\Productive\Resources\Resource;

/**
 * An aggregated timesheet report row grouping timesheet records by configurable dimensions with time metrics.
 *
 * @see https://developer.productive.io/reference/resources/reports
 */
final class TimesheetReportResource extends Resource
{
    protected const string TYPE = 'timesheet_reports';

    protected const string PATH = 'reports/timesheet_reports';

    protected const bool SUPPORTS_CURSOR = false;

    /**
     * Get timesheet reports.
     *
     * GET /reports/timesheet_reports
     *
     * @return PendingQuery<TimesheetReport>
     */
    public function query(): PendingQuery
    {
        return $this->newQuery(TimesheetReport::class, 'reports.timesheet_reports.index');
    }

    protected function rateLimits(): array
    {
        return [RateLimit::reports()];
    }
}
