<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for the "approve" action on a expense.
 */
final readonly class ApproveExpenseData extends InputData
{
    public function __construct(
        public int|string|Undefined|null $approverId = Undefined::Value,
        public string|Undefined|null $note = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'approver_id' => $this->approverId,
            'note' => $this->note,
        ]);
    }
}
