<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;

/**
 * Attributes for the "change workflow" action on a project.
 */
final readonly class ChangeWorkflowProjectData extends InputData
{
    /**
     * @param  array<string, int>  $map  Mapping from each status ID in the project's current workflow to a status ID in the target workflow. Every status in the current workflow must appear as a key, and each value must be a valid status in the target workflow.
     */
    public function __construct(
        public int|string $workflowId,
        public array $map,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'workflow_id' => $this->workflowId,
            'map' => $this->map,
        ]);
    }
}
