<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for the "copy" action on a project.
 */
final readonly class CopyProjectData extends InputData
{
    public function __construct(
        public string $name,
        public int|string $templateId,
        public int|string $projectTypeId,
        public int|string|Undefined|null $companyId = Undefined::Value,
        public bool|Undefined|null $copyAsTemplate = Undefined::Value,
        public string|Undefined|null $description = Undefined::Value,
        public int|string|Undefined|null $projectColorId = Undefined::Value,
        public int|string|Undefined|null $projectManagerId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'name' => $this->name,
            'template_id' => $this->templateId,
            'project_type_id' => $this->projectTypeId,
            'company_id' => $this->companyId,
            'copy_as_template' => $this->copyAsTemplate,
            'description' => $this->description,
            'project_color_id' => $this->projectColorId,
            'project_manager_id' => $this->projectManagerId,
        ]);
    }
}
