<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a approval policy.
 */
final readonly class CreateApprovalPolicyData extends InputData
{
    public function __construct(
        public int|string $typeId,
        public bool|Undefined|null $custom = Undefined::Value,
        public bool|Undefined|null $default = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'type_id' => $this->typeId,
            'custom' => $this->custom,
            'default' => $this->default,
            'name' => $this->name,
        ]);
    }
}
