<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a agent config.
 */
final readonly class CreateAgentConfigData extends InputData
{
    public function __construct(
        public int|string $agentId,
        public string|Undefined|null $aiModel = Undefined::Value,
        public string|Undefined|null $instructions = Undefined::Value,
        public string|Undefined|null $reasoningEffort = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'agent_id' => $this->agentId,
            'ai_model' => $this->aiModel,
            'instructions' => $this->instructions,
            'reasoning_effort' => $this->reasoningEffort,
        ]);
    }
}
