<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a filter.
 *
 * @SuppressWarnings("PHPMD.ExcessiveParameterList")
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final readonly class CreateFilterData extends InputData
{
    /**
     * @param  array<string, mixed>|Undefined|null  $exchangeDate  A JSON object defining the date or date range used for currency exchange rate lookups in this filter.
     */
    public function __construct(
        public int|string|Undefined|null $chartTypeId = Undefined::Value,
        public string|Undefined|null $columnSettings = Undefined::Value,
        public string|Undefined|null $columns = Undefined::Value,
        public string|Undefined|null $exchangeCurrency = Undefined::Value,
        public array|Undefined|null $exchangeDate = Undefined::Value,
        public string|Undefined|null $filterableCollection = Undefined::Value,
        public int|string|Undefined|null $filterableId = Undefined::Value,
        public string|Undefined|null $filterableType = Undefined::Value,
        public string|Undefined|null $formulas = Undefined::Value,
        public string|Undefined|null $groupBy = Undefined::Value,
        public bool|Undefined|null $hidden = Undefined::Value,
        public int|string|Undefined|null $layoutId = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
        public string|Undefined|null $params = Undefined::Value,
        public string|Undefined|null $predefinedId = Undefined::Value,
        public bool|Undefined|null $public = Undefined::Value,
        public bool|Undefined|null $report = Undefined::Value,
        public int|string|Undefined|null $reportCategoryId = Undefined::Value,
        public int|string|Undefined|null $reportLayoutId = Undefined::Value,
        public string|Undefined|null $settings = Undefined::Value,
        public string|Undefined|null $sortBy = Undefined::Value,
        public string|Undefined|null $transposeBy = Undefined::Value,
        public int|string|Undefined|null $typeId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'chart_type_id' => $this->chartTypeId,
            'column_settings' => $this->columnSettings,
            'columns' => $this->columns,
            'exchange_currency' => $this->exchangeCurrency,
            'exchange_date' => $this->exchangeDate,
            'filterable_collection' => $this->filterableCollection,
            'filterable_id' => $this->filterableId,
            'filterable_type' => $this->filterableType,
            'formulas' => $this->formulas,
            'group_by' => $this->groupBy,
            'hidden' => $this->hidden,
            'layout_id' => $this->layoutId,
            'name' => $this->name,
            'params' => $this->params,
            'predefined_id' => $this->predefinedId,
            'public' => $this->public,
            'report' => $this->report,
            'report_category_id' => $this->reportCategoryId,
            'report_layout_id' => $this->reportLayoutId,
            'settings' => $this->settings,
            'sort_by' => $this->sortBy,
            'transpose_by' => $this->transposeBy,
            'type_id' => $this->typeId,
        ]);
    }
}
