<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;
use DateTimeInterface;

/**
 * Attributes for creating a contract.
 */
final readonly class CreateContractData extends InputData
{
    public function __construct(
        public int|string $intervalId,
        public mixed $templateId,
        public bool|Undefined|null $copyExpenses = Undefined::Value,
        public bool|Undefined|null $copyPurchaseOrderNumber = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $endsOn = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $nextOccurrenceOn = Undefined::Value,
        public bool|Undefined|null $useRolloverHours = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'interval_id' => $this->intervalId,
            'template_id' => $this->templateId,
            'copy_expenses' => $this->copyExpenses,
            'copy_purchase_order_number' => $this->copyPurchaseOrderNumber,
            'ends_on' => self::date($this->endsOn),
            'next_occurrence_on' => self::date($this->nextOccurrenceOn),
            'use_rollover_hours' => $this->useRolloverHours,
        ]);
    }
}
