<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a team.
 */
final readonly class CreateTeamData extends InputData
{
    public function __construct(
        public string $name,
        public int|string|Undefined|null $colorId = Undefined::Value,
        public string|Undefined|null $iconId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'name' => $this->name,
            'color_id' => $this->colorId,
            'icon_id' => $this->iconId,
        ]);
    }
}
