<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;
use DateTimeInterface;

/**
 * Attributes for creating a bill.
 */
final readonly class CreateBillData extends InputData
{
    public function __construct(
        public int|string $purchaseOrderId,
        public int|string|Undefined|null $attachmentId = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $date = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $dueDate = Undefined::Value,
        public string|Undefined|null $invoiceNumber = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'purchase_order_id' => $this->purchaseOrderId,
            'attachment_id' => $this->attachmentId,
            'date' => self::date($this->date),
            'due_date' => self::date($this->dueDate),
            'invoice_number' => $this->invoiceNumber,
        ]);
    }
}
