<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for the "create with markdown" action on a page.
 *
 * @SuppressWarnings("PHPMD.ExcessiveParameterList")
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final readonly class CreateWithMarkdownPageData extends InputData
{
    /**
     * @param  list<int|string>|Undefined|null  $attachmentIds  IDs of attachments associated with this page.
     * @param  array<string, mixed>|Undefined|null  $customFields  Custom field values set on this page. Only available on root pages that belong to a project.
     * @param  array<string, mixed>|Undefined|null  $preferences  Page-level display preferences such as layout width, font size and default edit access.
     */
    public function __construct(
        public string $markdown,
        public array|Undefined|null $attachmentIds = Undefined::Value,
        public string|Undefined|null $coverImageUrl = Undefined::Value,
        public array|Undefined|null $customFields = Undefined::Value,
        public string|Undefined|null $iconId = Undefined::Value,
        public int|string|Undefined|null $parentPageId = Undefined::Value,
        public int|Undefined|null $position = Undefined::Value,
        public array|Undefined|null $preferences = Undefined::Value,
        public int|string|Undefined|null $projectId = Undefined::Value,
        public int|string|Undefined|null $rootPageId = Undefined::Value,
        public string|Undefined|null $title = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'markdown' => $this->markdown,
            'attachment_ids' => $this->attachmentIds,
            'cover_image_url' => $this->coverImageUrl,
            'custom_fields' => $this->customFields,
            'icon_id' => $this->iconId,
            'parent_page_id' => $this->parentPageId,
            'position' => $this->position,
            'preferences' => $this->preferences,
            'project_id' => $this->projectId,
            'root_page_id' => $this->rootPageId,
            'title' => $this->title,
        ]);
    }
}
