<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a expense line item.
 */
final readonly class CreateExpenseLineItemData extends InputData
{
    public function __construct(
        public string $name,
        public float|int $quantity,
        public int $unitPrice,
        public int|string $expenseId,
        public int|Undefined|null $position = Undefined::Value,
        public int|string|Undefined|null $taxRateId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'name' => $this->name,
            'quantity' => $this->quantity,
            'unit_price' => $this->unitPrice,
            'expense_id' => $this->expenseId,
            'position' => $this->position,
            'tax_rate_id' => $this->taxRateId,
        ]);
    }
}
