<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a agent.
 */
final readonly class CreateAgentData extends InputData
{
    public function __construct(
        public string $name,
        public int|string $managerId,
        public string|Undefined|null $avatarUrl = Undefined::Value,
        public int|string|Undefined|null $customRoleId = Undefined::Value,
        public string|Undefined|null $title = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'name' => $this->name,
            'manager_id' => $this->managerId,
            'avatar_url' => $this->avatarUrl,
            'custom_role_id' => $this->customRoleId,
            'title' => $this->title,
        ]);
    }
}
