<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a pipeline.
 */
final readonly class CreatePipelineData extends InputData
{
    public function __construct(
        public string $name,
        public string|Undefined|null $iconId = Undefined::Value,
        public int|string|Undefined|null $pipelineTypeId = Undefined::Value,
        public int|Undefined|null $position = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'name' => $this->name,
            'icon_id' => $this->iconId,
            'pipeline_type_id' => $this->pipelineTypeId,
            'position' => $this->position,
        ]);
    }
}
