<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a widget.
 *
 * @SuppressWarnings("PHPMD.ExcessiveParameterList")
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final readonly class CreateWidgetData extends InputData
{
    /**
     * @param  list<int|string>|Undefined|null  $attachmentIds  IDs of attachments to associate with this widget.
     */
    public function __construct(
        public int $height,
        public int $width,
        public int|string $widgetTypeId,
        public int|string $dashboardId,
        public array|Undefined|null $attachmentIds = Undefined::Value,
        public int|Undefined|null $columnPosition = Undefined::Value,
        public string|Undefined|null $content = Undefined::Value,
        public int|string|Undefined|null $filterId = Undefined::Value,
        public int|Undefined|null $rowPosition = Undefined::Value,
        public string|Undefined|null $title = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'height' => $this->height,
            'width' => $this->width,
            'widget_type_id' => $this->widgetTypeId,
            'dashboard_id' => $this->dashboardId,
            'attachment_ids' => $this->attachmentIds,
            'column_position' => $this->columnPosition,
            'content' => $this->content,
            'filter_id' => $this->filterId,
            'row_position' => $this->rowPosition,
            'title' => $this->title,
        ]);
    }
}
