<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a custom field section.
 */
final readonly class CreateCustomFieldSectionData extends InputData
{
    public function __construct(
        public string $name,
        public mixed $customizableType = Undefined::Value,
        public int|Undefined|null $position = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'name' => $this->name,
            'customizable_type' => $this->customizableType,
            'position' => $this->position,
        ]);
    }
}
