<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;

/**
 * Attributes for creating a service assignment.
 */
final readonly class CreateServiceAssignmentData extends InputData
{
    public function __construct(
        public int|string $serviceId,
        public int|string $personId,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'service_id' => $this->serviceId,
            'person_id' => $this->personId,
        ]);
    }
}
