<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a custom domain.
 */
final readonly class CreateCustomDomainData extends InputData
{
    public function __construct(
        public bool|Undefined|null $allowUserEmail = Undefined::Value,
        public string|Undefined|null $emailSenderAddress = Undefined::Value,
        public string|Undefined|null $emailSenderName = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'allow_user_email' => $this->allowUserEmail,
            'email_sender_address' => $this->emailSenderAddress,
            'email_sender_name' => $this->emailSenderName,
            'name' => $this->name,
        ]);
    }
}
