<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a skill.
 */
final readonly class CreateSkillData extends InputData
{
    /**
     * @param  list<string>|Undefined|null  $smartActionLocations
     */
    public function __construct(
        public string $name,
        public string $description,
        public bool|Undefined|null $autoLoad = Undefined::Value,
        public string|Undefined|null $instructions = Undefined::Value,
        public array|Undefined|null $smartActionLocations = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'name' => $this->name,
            'description' => $this->description,
            'auto_load' => $this->autoLoad,
            'instructions' => $this->instructions,
            'smart_action_locations' => $this->smartActionLocations,
        ]);
    }
}
