<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a tax rate.
 */
final readonly class CreateTaxRateData extends InputData
{
    public function __construct(
        public string $name,
        public int|string $subsidiaryId,
        public string|Undefined|null $primaryComponentName = Undefined::Value,
        public float|int|Undefined|null $primaryComponentValue = Undefined::Value,
        public string|Undefined|null $secondaryComponentName = Undefined::Value,
        public float|int|Undefined|null $secondaryComponentValue = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'name' => $this->name,
            'subsidiary_id' => $this->subsidiaryId,
            'primary_component_name' => $this->primaryComponentName,
            'primary_component_value' => $this->primaryComponentValue,
            'secondary_component_name' => $this->secondaryComponentName,
            'secondary_component_value' => $this->secondaryComponentValue,
        ]);
    }
}
