<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for creating a bank account.
 */
final readonly class CreateBankAccountData extends InputData
{
    public function __construct(
        public string|Undefined|null $bankAddress = Undefined::Value,
        public string|Undefined|null $bankName = Undefined::Value,
        public string|Undefined|null $currency = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
        public string|Undefined|null $number = Undefined::Value,
        public int|string|Undefined|null $subsidiaryId = Undefined::Value,
        public string|Undefined|null $swiftCode = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'bank_address' => $this->bankAddress,
            'bank_name' => $this->bankName,
            'currency' => $this->currency,
            'name' => $this->name,
            'number' => $this->number,
            'subsidiary_id' => $this->subsidiaryId,
            'swift_code' => $this->swiftCode,
        ]);
    }
}
