<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;

/**
 * Attributes for creating a task dependency.
 */
final readonly class CreateTaskDependencyData extends InputData
{
    public function __construct(
        public int|string $dependentTaskId,
        public int|string $taskId,
        public int|string $typeId,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'dependent_task_id' => $this->dependentTaskId,
            'task_id' => $this->taskId,
            'type_id' => $this->typeId,
        ]);
    }
}
