<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;

/**
 * Attributes for creating a rate card.
 */
final readonly class CreateRateCardData extends InputData
{
    public function __construct(
        public string $name,
        public int|string $companyId,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'name' => $this->name,
            'company_id' => $this->companyId,
        ]);
    }
}
