<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for the "send" action on a purchase order.
 */
final readonly class SendPurchaseOrderData extends InputData
{
    /**
     * @param  list<string>  $to  List of recipient email addresses. At least one is required.
     * @param  list<int>|Undefined|null  $attachmentIds  Attachment IDs to include with the email.
     * @param  list<string>|Undefined|null  $bcc  List of BCC recipient email addresses.
     * @param  list<string>|Undefined|null  $cc  List of CC recipient email addresses.
     */
    public function __construct(
        public array $to,
        public string $subject,
        public string $body,
        public array|Undefined|null $attachmentIds = Undefined::Value,
        public array|Undefined|null $bcc = Undefined::Value,
        public array|Undefined|null $cc = Undefined::Value,
        public string|Undefined|null $from = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'to' => $this->to,
            'subject' => $this->subject,
            'body' => $this->body,
            'attachment_ids' => $this->attachmentIds,
            'bcc' => $this->bcc,
            'cc' => $this->cc,
            'from' => $this->from,
        ]);
    }
}
