<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a task dependency. Fields left out are not changed; null clears a field.
 */
final readonly class UpdateTaskDependencyData extends InputData
{
    public function __construct(
        public int|string|Undefined|null $dependentTaskId = Undefined::Value,
        public int|string|Undefined|null $taskId = Undefined::Value,
        public int|string|Undefined|null $typeId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'dependent_task_id' => $this->dependentTaskId,
            'task_id' => $this->taskId,
            'type_id' => $this->typeId,
        ]);
    }
}
