<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a survey. Fields left out are not changed; null clears a field.
 */
final readonly class UpdateSurveyData extends InputData
{
    public function __construct(
        public int|string|Undefined|null $projectId = Undefined::Value,
        public string|Undefined|null $submissionAccess = Undefined::Value,
        public string|Undefined|null $title = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'project_id' => $this->projectId,
            'submission_access' => $this->submissionAccess,
            'title' => $this->title,
        ]);
    }
}
