<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;
use DateTimeInterface;

/**
 * Attributes for updating a user. Fields left out are not changed; null clears a field.
 *
 * @SuppressWarnings("PHPMD.ExcessiveParameterList")
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final readonly class UpdateUserData extends InputData
{
    public function __construct(
        public DateTimeInterface|string|Undefined|null $accountAccessExpiresAt = Undefined::Value,
        public string|Undefined|null $avatarUrl = Undefined::Value,
        public int|string|Undefined|null $defaultOrganizationId = Undefined::Value,
        public string|Undefined|null $email = Undefined::Value,
        public string|Undefined|null $firstName = Undefined::Value,
        public string|Undefined|null $icalToken = Undefined::Value,
        public string|Undefined|null $lastName = Undefined::Value,
        public string|Undefined|null $locale = Undefined::Value,
        public mixed $newsletterConsent = Undefined::Value,
        public string|Undefined|null $preferences = Undefined::Value,
        public string|Undefined|null $timeZone = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'account_access_expires_at' => $this->accountAccessExpiresAt,
            'avatar_url' => $this->avatarUrl,
            'default_organization_id' => $this->defaultOrganizationId,
            'email' => $this->email,
            'first_name' => $this->firstName,
            'ical_token' => $this->icalToken,
            'last_name' => $this->lastName,
            'locale' => $this->locale,
            'newsletter_consent' => $this->newsletterConsent,
            'preferences' => $this->preferences,
            'time_zone' => $this->timeZone,
        ]);
    }
}
