<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;
use DateTimeInterface;

/**
 * Attributes for updating a purchase order. Fields left out are not changed; null clears a field.
 *
 * @SuppressWarnings("PHPMD.ExcessiveParameterList")
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final readonly class UpdatePurchaseOrderData extends InputData
{
    /**
     * @param  list<int|string>|Undefined|null  $subscriberIds  Array of IDs of users subscribed to receive notifications about this purchase order.
     */
    public function __construct(
        public int|string|Undefined|null $attachmentId = Undefined::Value,
        public string|Undefined|null $currency = Undefined::Value,
        public int|string|Undefined|null $dealId = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $deliveryOn = Undefined::Value,
        public int|string|Undefined|null $documentTypeId = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $issuedOn = Undefined::Value,
        public mixed $note = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $sentOn = Undefined::Value,
        public int|string|Undefined|null $statusId = Undefined::Value,
        public string|Undefined|null $subject = Undefined::Value,
        public array|Undefined|null $subscriberIds = Undefined::Value,
        public int|string|Undefined|null $vendorId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'attachment_id' => $this->attachmentId,
            'currency' => $this->currency,
            'deal_id' => $this->dealId,
            'delivery_on' => self::date($this->deliveryOn),
            'document_type_id' => $this->documentTypeId,
            'issued_on' => self::date($this->issuedOn),
            'note' => $this->note,
            'sent_on' => self::date($this->sentOn),
            'status_id' => $this->statusId,
            'subject' => $this->subject,
            'subscriber_ids' => $this->subscriberIds,
            'vendor_id' => $this->vendorId,
        ]);
    }
}
