<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a workflow status. Fields left out are not changed; null clears a field.
 */
final readonly class UpdateWorkflowStatusData extends InputData
{
    public function __construct(
        public int|string|Undefined|null $categoryId = Undefined::Value,
        public int|string|Undefined|null $colorId = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
        public int|Undefined|null $position = Undefined::Value,
        public int|string|Undefined|null $workflowId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'category_id' => $this->categoryId,
            'color_id' => $this->colorId,
            'name' => $this->name,
            'position' => $this->position,
            'workflow_id' => $this->workflowId,
        ]);
    }
}
