<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;
use DateTimeInterface;

/**
 * Attributes for updating a salary. Fields left out are not changed; null clears a field.
 *
 * @SuppressWarnings("PHPMD.ExcessiveParameterList")
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final readonly class UpdateSalaryData extends InputData
{
    /**
     * @param  array<string, mixed>|Undefined|null  $workingHours  The weekly working hours schedule for this salary record.
     */
    public function __construct(
        public bool|Undefined|null $alternatingHours = Undefined::Value,
        public int|Undefined|null $cost = Undefined::Value,
        public string|Undefined|null $currency = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $endedOn = Undefined::Value,
        public mixed $holidayCalendarId = Undefined::Value,
        public mixed $note = Undefined::Value,
        public bool|Undefined|null $overhead = Undefined::Value,
        public int|string|Undefined|null $personId = Undefined::Value,
        public int|string|Undefined|null $salaryTypeId = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $startedOn = Undefined::Value,
        public array|Undefined|null $workingHours = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'alternating_hours' => $this->alternatingHours,
            'cost' => $this->cost,
            'currency' => $this->currency,
            'ended_on' => self::date($this->endedOn),
            'holiday_calendar_id' => $this->holidayCalendarId,
            'note' => $this->note,
            'overhead' => $this->overhead,
            'person_id' => $this->personId,
            'salary_type_id' => $this->salaryTypeId,
            'started_on' => self::date($this->startedOn),
            'working_hours' => $this->workingHours,
        ]);
    }
}
