<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a placeholder. Fields left out are not changed; null clears a field.
 */
final readonly class UpdatePlaceholderData extends InputData
{
    public function __construct(
        public string|Undefined|null $category = Undefined::Value,
        public string|Undefined|null $color = Undefined::Value,
        public string|Undefined|null $icon = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
        public int|string|Undefined|null $projectId = Undefined::Value,
        public string|Undefined|null $type = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'category' => $this->category,
            'color' => $this->color,
            'icon' => $this->icon,
            'name' => $this->name,
            'project_id' => $this->projectId,
            'type' => $this->type,
        ]);
    }
}
