<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a einvoice identity. Fields left out are not changed; null clears a field.
 */
final readonly class UpdateEinvoiceIdentityData extends InputData
{
    public function __construct(
        public string|Undefined|null $buyerReference = Undefined::Value,
        public int|string|Undefined|null $companyId = Undefined::Value,
        public string|Undefined|null $dir3FiscalCode = Undefined::Value,
        public string|Undefined|null $dir3PagadorCode = Undefined::Value,
        public string|Undefined|null $dir3ReceptorCode = Undefined::Value,
        public string|Undefined|null $direCode = Undefined::Value,
        public bool|Undefined|null $isGovernmentEntity = Undefined::Value,
        public string|Undefined|null $peppolId = Undefined::Value,
        public int|string|Undefined|null $subsidiaryId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'buyer_reference' => $this->buyerReference,
            'company_id' => $this->companyId,
            'dir3_fiscal_code' => $this->dir3FiscalCode,
            'dir3_pagador_code' => $this->dir3PagadorCode,
            'dir3_receptor_code' => $this->dir3ReceptorCode,
            'dire_code' => $this->direCode,
            'is_government_entity' => $this->isGovernmentEntity,
            'peppol_id' => $this->peppolId,
            'subsidiary_id' => $this->subsidiaryId,
        ]);
    }
}
