<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a approval policy. Fields left out are not changed; null clears a field.
 */
final readonly class UpdateApprovalPolicyData extends InputData
{
    public function __construct(
        public bool|Undefined|null $custom = Undefined::Value,
        public bool|Undefined|null $default = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
        public int|string|Undefined|null $typeId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'custom' => $this->custom,
            'default' => $this->default,
            'name' => $this->name,
            'type_id' => $this->typeId,
        ]);
    }
}
