<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a deal status. Fields left out are not changed; null clears a field.
 *
 * @SuppressWarnings("PHPMD.ExcessiveParameterList")
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final readonly class UpdateDealStatusData extends InputData
{
    public function __construct(
        public bool|Undefined|null $bookingTrackingEnabled = Undefined::Value,
        public int|string|Undefined|null $colorId = Undefined::Value,
        public bool|Undefined|null $expenseTrackingEnabled = Undefined::Value,
        public bool|Undefined|null $lostReasonEnabled = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
        public int|string|Undefined|null $pipelineId = Undefined::Value,
        public int|Undefined|null $position = Undefined::Value,
        public int|Undefined|null $probability = Undefined::Value,
        public bool|Undefined|null $probabilityEnabled = Undefined::Value,
        public int|string|Undefined|null $statusId = Undefined::Value,
        public bool|Undefined|null $timeTrackingEnabled = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'booking_tracking_enabled' => $this->bookingTrackingEnabled,
            'color_id' => $this->colorId,
            'expense_tracking_enabled' => $this->expenseTrackingEnabled,
            'lost_reason_enabled' => $this->lostReasonEnabled,
            'name' => $this->name,
            'pipeline_id' => $this->pipelineId,
            'position' => $this->position,
            'probability' => $this->probability,
            'probability_enabled' => $this->probabilityEnabled,
            'status_id' => $this->statusId,
            'time_tracking_enabled' => $this->timeTrackingEnabled,
        ]);
    }
}
