<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a password. Fields left out are not changed; null clears a field.
 */
final readonly class UpdatePasswordData extends InputData
{
    public function __construct(
        public mixed $password = Undefined::Value,
        public mixed $passwordConfirmation = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'password' => $this->password,
            'password_confirmation' => $this->passwordConfirmation,
        ]);
    }
}
