<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;
use DateTimeInterface;

/**
 * Attributes for updating a person. Fields left out are not changed; null clears a field.
 *
 * @SuppressWarnings("PHPMD.ExcessiveParameterList")
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final readonly class UpdatePersonData extends InputData
{
    /**
     * @param  array<string, mixed>|Undefined|null  $contact  Additional contact data for the person, such as phone numbers and addresses.
     * @param  array<string, mixed>|Undefined|null  $customFields  Custom field values for this person.
     * @param  array<string, mixed>|Undefined|null  $granularNotificationPreferences  Granular notification preferences for this person.
     * @param  list<int|string>|Undefined|null  $subscriberIds  IDs of people subscribed to follow this person.
     */
    public function __construct(
        public mixed $accountId = Undefined::Value,
        public string|Undefined|null $aiAssistantInstructions = Undefined::Value,
        public bool|Undefined|null $autotracking = Undefined::Value,
        public string|Undefined|null $avatarUrl = Undefined::Value,
        public int|string|Undefined|null $companyId = Undefined::Value,
        public array|Undefined|null $contact = Undefined::Value,
        public array|Undefined|null $customFields = Undefined::Value,
        public int|string|Undefined|null $customRoleId = Undefined::Value,
        public string|Undefined|null $email = Undefined::Value,
        public string|Undefined|null $firstName = Undefined::Value,
        public array|Undefined|null $granularNotificationPreferences = Undefined::Value,
        public int|string|Undefined|null $jobRoleId = Undefined::Value,
        public string|Undefined|null $lastName = Undefined::Value,
        public int|string|Undefined|null $managerId = Undefined::Value,
        public string|Undefined|null $nickname = Undefined::Value,
        public int|string|Undefined|null $roleId = Undefined::Value,
        public string|Undefined|null $statusEmoji = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $statusExpiresAt = Undefined::Value,
        public string|Undefined|null $statusText = Undefined::Value,
        public array|Undefined|null $subscriberIds = Undefined::Value,
        public int|string|Undefined|null $subsidiaryId = Undefined::Value,
        public string|Undefined|null $tagList = Undefined::Value,
        public bool|Undefined|null $timeOffStatusSync = Undefined::Value,
        public int|string|Undefined|null $timeTrackingPolicyId = Undefined::Value,
        public bool|Undefined|null $timeUnlocked = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $timeUnlockedEndDate = Undefined::Value,
        public int|Undefined|null $timeUnlockedInterval = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $timeUnlockedOn = Undefined::Value,
        public int|string|Undefined|null $timeUnlockedPeriodId = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $timeUnlockedStartDate = Undefined::Value,
        public bool|Undefined|null $timesheetSubmissionDisabled = Undefined::Value,
        public string|Undefined|null $title = Undefined::Value,
        public bool|Undefined|null $virtual = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'account_id' => $this->accountId,
            'ai_assistant_instructions' => $this->aiAssistantInstructions,
            'autotracking' => $this->autotracking,
            'avatar_url' => $this->avatarUrl,
            'company_id' => $this->companyId,
            'contact' => $this->contact,
            'custom_fields' => $this->customFields,
            'custom_role_id' => $this->customRoleId,
            'email' => $this->email,
            'first_name' => $this->firstName,
            'granular_notification_preferences' => $this->granularNotificationPreferences,
            'job_role_id' => $this->jobRoleId,
            'last_name' => $this->lastName,
            'manager_id' => $this->managerId,
            'nickname' => $this->nickname,
            'role_id' => $this->roleId,
            'status_emoji' => $this->statusEmoji,
            'status_expires_at' => $this->statusExpiresAt,
            'status_text' => $this->statusText,
            'subscriber_ids' => $this->subscriberIds,
            'subsidiary_id' => $this->subsidiaryId,
            'tag_list' => $this->tagList,
            'time_off_status_sync' => $this->timeOffStatusSync,
            'time_tracking_policy_id' => $this->timeTrackingPolicyId,
            'time_unlocked' => $this->timeUnlocked,
            'time_unlocked_end_date' => self::date($this->timeUnlockedEndDate),
            'time_unlocked_interval' => $this->timeUnlockedInterval,
            'time_unlocked_on' => self::date($this->timeUnlockedOn),
            'time_unlocked_period_id' => $this->timeUnlockedPeriodId,
            'time_unlocked_start_date' => self::date($this->timeUnlockedStartDate),
            'timesheet_submission_disabled' => $this->timesheetSubmissionDisabled,
            'title' => $this->title,
            'virtual' => $this->virtual,
        ]);
    }
}
