<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a expense line item. Fields left out are not changed; null clears a field.
 */
final readonly class UpdateExpenseLineItemData extends InputData
{
    public function __construct(
        public int|string|Undefined|null $expenseId = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
        public int|Undefined|null $position = Undefined::Value,
        public float|int|Undefined|null $quantity = Undefined::Value,
        public int|string|Undefined|null $taxRateId = Undefined::Value,
        public int|Undefined|null $unitPrice = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'expense_id' => $this->expenseId,
            'name' => $this->name,
            'position' => $this->position,
            'quantity' => $this->quantity,
            'tax_rate_id' => $this->taxRateId,
            'unit_price' => $this->unitPrice,
        ]);
    }
}
