<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a board. Fields left out are not changed; null clears a field.
 */
final readonly class UpdateBoardData extends InputData
{
    public function __construct(
        public bool|Undefined|null $hidden = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
        public int|Undefined|null $position = Undefined::Value,
        public int|string|Undefined|null $projectId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'hidden' => $this->hidden,
            'name' => $this->name,
            'position' => $this->position,
            'project_id' => $this->projectId,
        ]);
    }
}
