<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a overhead. Fields left out are not changed; null clears a field.
 */
final readonly class UpdateOverheadData extends InputData
{
    /**
     * @param  array<string, mixed>|Undefined|null  $facilityCostsBreakdown  A breakdown of facility costs by category (e.g. rent, utilities) for this overhead period.
     * @param  array<string, mixed>|Undefined|null  $overheadControls  A set of flags controlling which overhead types (facility, work, time-off, expense, undertime, overtime) are included in cost calculations.
     */
    public function __construct(
        public int|Undefined|null $averagingPeriod = Undefined::Value,
        public int|Undefined|null $facilityCosts = Undefined::Value,
        public array|Undefined|null $facilityCostsBreakdown = Undefined::Value,
        public array|Undefined|null $overheadControls = Undefined::Value,
        public bool|Undefined|null $useOverhead = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'averaging_period' => $this->averagingPeriod,
            'facility_costs' => $this->facilityCosts,
            'facility_costs_breakdown' => $this->facilityCostsBreakdown,
            'overhead_controls' => $this->overheadControls,
            'use_overhead' => $this->useOverhead,
        ]);
    }
}
