<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;
use DateTimeInterface;

/**
 * Attributes for updating a todo. Fields left out are not changed; null clears a field.
 */
final readonly class UpdateTodoData extends InputData
{
    public function __construct(
        public int|string|Undefined|null $assigneeId = Undefined::Value,
        public bool|Undefined|null $closed = Undefined::Value,
        public int|string|Undefined|null $dealId = Undefined::Value,
        public string|Undefined|null $description = Undefined::Value,
        public DateTimeInterface|string|Undefined|null $dueDate = Undefined::Value,
        public int|Undefined|null $position = Undefined::Value,
        public int|string|Undefined|null $taskId = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'assignee_id' => $this->assigneeId,
            'closed' => $this->closed,
            'deal_id' => $this->dealId,
            'description' => $this->description,
            'due_date' => self::date($this->dueDate),
            'position' => $this->position,
            'task_id' => $this->taskId,
        ]);
    }
}
