<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a widget. Fields left out are not changed; null clears a field.
 *
 * @SuppressWarnings("PHPMD.ExcessiveParameterList")
 * @SuppressWarnings("PHPMD.ExcessiveMethodLength")
 */
final readonly class UpdateWidgetData extends InputData
{
    /**
     * @param  list<int|string>|Undefined|null  $attachmentIds  IDs of attachments to associate with this widget.
     */
    public function __construct(
        public array|Undefined|null $attachmentIds = Undefined::Value,
        public int|Undefined|null $columnPosition = Undefined::Value,
        public string|Undefined|null $content = Undefined::Value,
        public int|string|Undefined|null $dashboardId = Undefined::Value,
        public int|string|Undefined|null $filterId = Undefined::Value,
        public int|Undefined|null $height = Undefined::Value,
        public int|Undefined|null $rowPosition = Undefined::Value,
        public string|Undefined|null $title = Undefined::Value,
        public int|string|Undefined|null $widgetTypeId = Undefined::Value,
        public int|Undefined|null $width = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'attachment_ids' => $this->attachmentIds,
            'column_position' => $this->columnPosition,
            'content' => $this->content,
            'dashboard_id' => $this->dashboardId,
            'filter_id' => $this->filterId,
            'height' => $this->height,
            'row_position' => $this->rowPosition,
            'title' => $this->title,
            'widget_type_id' => $this->widgetTypeId,
            'width' => $this->width,
        ]);
    }
}
