<?php

declare(strict_types=1);

// Generated by `composer generate` from resources/openapi/productive.json. Do not edit by hand.

namespace Axyr\Productive\Data\Input;

use Axyr\Productive\Data\InputData;
use Axyr\Productive\Data\Undefined;

/**
 * Attributes for updating a payment reminder sequence. Fields left out are not changed; null clears a field.
 */
final readonly class UpdatePaymentReminderSequenceData extends InputData
{
    public function __construct(
        public bool|Undefined|null $defaultSequence = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
    ) {}

    public function toAttributes(): array
    {
        return self::filter([
            'default_sequence' => $this->defaultSequence,
            'name' => $this->name,
        ]);
    }
}
